codeforamerica/michigan-benefits

Gemfile, Gemfile.lock, spec/rails_helper.rb
**WHY**: This is mostly dev-only stuff that Cylinder folks won't use.
Plus, better not to have dev-specific stuff in the Gemfile when
possible.
=> Remove unnecessary dependencies

.overcommit.yml, Gemfile, Gemfile.lock, bin/setup
* The [overcommit] gem allows for installation of git commit hooks.
* This can provide a way to run checks like Rubocop when committing, as opposed running tests or on CI, which are further down the code lifecycle.
[overcommit]: https://github.com/brigade/overcommit
Changes
=======
* Add the overcommit gem to the Gemfile
* Add overcommit installation to setup script
* Add the default configuration file.
Minor
=====
* Add a helper to detect if a cli is installed or now.
=> Add overcommit gem

config/environments/development.rb, config/environments/production.rb, config/smtp.rb
**WHY**: this makes it easier to keep things organized. Also, before it
was inconsistent between prod and dev
=> Put SMTP config into its own file

.gitignore, .rspec, app/jobs/send_application_job.rb, app/mailers/application_mailer.rb, app/models/dhs1171_pdf.rb, config/brakeman.ignore, spec/jobs/send_application_job_spec.rb, spec/models/dhs1171_pdf_spec.rb, spec/spec_helper.rb
* Much of what we were doing manually with files (creating them, randomizing names, cleaning them up after use) is managed by Ruby's [tempfile] library.
[tempfile]: https://docs.ruby-lang.org/en/2.4.0/Tempfile.html
Changes
=======
* In the generation of the completed `Dhs1171Pdf` file, use `tempfile`s in the pdf generation and return the resulting `tempfile`.
* Be sure to close the `tempfile` explicitly in this class.
* In the job class, generate and close the tempfile after sending is complete.
Minor
-----
* No need to profile all specs on every run.
* gitignore .rspec because those are personal preferences, not team ones
=> Use Ruby's tempfiles for temporary files

.foreman, Gemfile, Gemfile.lock, Procfile.dev, config/environments/development.rb
In order for mailcatcher to work, we have to boot it up alongside both the
rails and worker processes. A small wrinkle attached to this is that we don't
want this process to start via the main, canonical, Procfile.  We'll need a
separate, dev-specific, Profile that we can run locally - `Profile.dev`. In
order for this procfile to run in the dev environment we can add a .foreman
file that will point to the other file - `Profile.dev`.
* Move mailcatcher to development gem group
* Configure mailcatcher in config/environments/development.rb
=> Add and configure mailcatcher

CONTRIBUTING.md, Gemfile, Gemfile.lock, app/models/fax.rb, config/secrets.yml, spec/models/fax_spec.rb
The sfax gem has been taken over by another project so pointing to the
CFA fork that the GCF team has set up is the best bet.
This commit adds an adapter class to interface with the SFax gem and
tests that it is being called correctly, using the credentials places in
the Rails secret yaml file.
NOTE: Adding faraday is necessary, for some reason to get things to
function reliably.
=> Add sfax, corresponding fax adapter and test

Procfile, bin/release_tasks
* We auto-deploy to `staging` when we merge to the `master` branch.
* Sometimes, we can forget to run the database migrations.
* We can automate this!
Changes
=======
* Use the [release-phase] option on Heroku to automatically run a script upon release.
* Set it to run a task that runs the migrations
[release-phase]: https://devcenter.heroku.com/articles/release-phase
=> Automatically migrate database when releasing

Gemfile, Gemfile.lock, app/views/address/edit.html.erb, spec/controllers/address_controller_spec.rb
* Users often are not aware of their county name.
* As such, asking them to fill in a form with the county name may not be productive.
Changes
=======
* Lock the usage to users of Genesee county only.
Minor
-----
* Add the `awesome_print` gem for colorful debugging (use `ap` instead of `puts`)
=> Serve only Genesee County

app/views/address/edit.html.erb, spec/features/snap_app_spec.rb
* The HTML directive is `disabled: true` with a "d" at the end. I had it as `disable: true` accidentally.
* See [reference].
[reference]: https://www.w3schools.com/jsref/prop_text_disabled.asp
Changes
=======
* Fix typo.
Minor
-----
* Add note specifying we are currently only serving Genesee County, so people aren't upset about the disabled text box.
=> Fix typo for disabling a field

app/controllers/address_controller.rb, app/steps/address.rb, app/views/address/edit.html.erb, spec/controllers/address_controller_spec.rb, spec/features/snap_app_spec.rb
**WHY**: We are setting defaults for these for now.
Part of https://trello.com/c/Wcz2Uf6z/81-as-an-mdhhs-worker-i-want-to-know-the-clients-phone-number-and-email-so-i-can-follow-up-with-them
I am opening this as a separate PR because I am unsure if this is the best place to implement this. Alternative would be DB-level default.
=> Remove state and county fields from address page

app/controllers/mailing_address_controller.rb, app/controllers/residential_address_controller.rb, app/controllers/steps_controller.rb, app/helpers/mb_form_builder.rb, app/models/address.rb, app/models/snap_application.rb, app/steps/mailing_address.rb, app/steps/residential_address.rb, app/steps/step_navigation.rb, app/views/mailing_address/edit.html.erb, app/views/residential_address/edit.html.erb, config/initializers/inflections.rb, db/migrate/20170808220230_add_mailing_address_same_as_residential_address_to_snap_applications.rb, db/migrate/20170808225329_create_addresses.rb, db/migrate/20170809000628_add_unstable_housing_to_snap_applications.rb, db/schema.rb, spec/controllers/contact_information_controller_spec.rb, spec/controllers/mailing_address_controller_spec.rb, spec/controllers/residential_address_controller_spec.rb, spec/factories/address.rb, spec/factories/snap_applications.rb, spec/features/snap_app_spec.rb
* This is skipped if the client indicates mailing and residential are
the same
* To do in follow up PRs:
- save mailing address in the "addresses" table instead of on the snap
app
- make sure "back" works with "skip" functionality
=> Add residential address step

app/controllers/steps_controller.rb, spec/features/snap_app_spec.rb
* Before, `skip` logic would always send the user forward
=> Client can go "Back" if home and residential addresses are same

app/models/member.rb
```
DEPRECATION WARNING: ssn is not an attribute known to Active Record.
This behavior is deprecated and will be removed in the next version of
Rails. If you'd like ssn to be managed by Active Record, add `attribute :ssn to your class.
```
Adding the attribute to the model fixes and removes this deprecation
warning.
=> Fix deprecation re: encrypted attribute

spec/features/snap_app_spec.rb, spec/support/feature_helper.rb
* was getting this error on `master` after styles were updated:
```
Capybara::Poltergeist::MouseEventFailed:
Firing a click at co-ordinates [342.5, 11.5] failed. Poltergeist detected another element with CSS selector 'html body.template--step div.page-wrapper div.step-header' at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click').
./spec/support/feature_helper.rb:16:in `block in select_radio'
./spec/support/feature_helper.rb:15:in `select_radio'
./spec/features/snap_app_spec.rb:259:in `answer_household_more_info_questions'
./spec/features/snap_app_spec.rb:110:in `block (3 levels) in <top (required)>'
./spec/support/feature_helper.rb:22:in `on_page' …
```
=> Fix overlapping element issue in test

app/steps/income_details_per_member.rb, app/views/income_details_per_member/edit.html.erb, spec/steps/income_details_per_member_spec.rb
**WHY**: this was a product requirement that was accidentally overlooked
the first time around
=> Only show work detail forms for employed and self employed

app/jobs/send_application_job.rb, spec/jobs/send_application_job_spec.rb
IF a phone number is set in the FAX_NUMBER environment variable, the job
will trigger the faxing of the pdf document. If there's no fax number,
it will not be sent.
=> Send a fax upon application submission

app/controllers/address_controller.rb, app/controllers/mailing_address_controller.rb, app/controllers/residential_address_controller.rb, app/views/sign_and_submit/edit.html.erb, app/views/success/edit.html.erb, db/migrate/20170821164112_add_default_true_to_mailing_address_same_as_residential_address.rb, db/schema.rb, spec/controllers/mailing_address_controller_spec.rb
1. Set default to be "mailing address same as residential" (true)
2. Change FAB to FAP (typo)
3. Reverse order of contents on success page so "what to expect next"
is more prominent (email section below)
success page:
=> Three small but distinct changes

.gitignore, Gemfile, Gemfile.lock, bin/setup, circle.yml, lib/find_chrome.rb, spec/rails_helper.rb, spec/support/chrome_browser.rb, spec/support/chrome_headless.rb, spec/support/feature_helper.rb
When our JS-enabled tests run we should use (headless) chrome and
chromedriver as the driver. This removes the dependency of poltergeist
but adds the need for chromedriver. As a result:
1. Add the installation of chromedriver to our setup script
2. Add the installation of chromedriver to circle.yml
Because the platforms we test on install chrome(driver) in different
locations this commit adds a `FindChrome` class that will locate chrome
and chromedriver in either the most common locations, or a location we
can specify with the ENV variables `CHROME_PATH` or `CHROMEDRIVER_PATH`.
If they're not found - raise an exception.
Default JS driver is `:headless_chrome` but can be changed to `:chrome`
in `rails_helper.rb` if we want to watch those tests in a real chrome
browser.
Also:
* Update …
=> Use headless chrome instead of poltergeist

.gitignore, README.md, app/controllers/preferences_interview_controller.rb, app/steps/preferences_interview.rb, app/steps/step_navigation.rb, app/views/preferences_interview/edit.html.erb, db/migrate/20170823185812_add_interview_preference_to_snap_application.rb, db/schema.rb, spec/controllers/preferences_interview_controller_spec.rb, spec/features/snap_app_spec.rb
* We should ask clients how they would like to be interviewed by the county.
Change
======
* Create a "Preferences" subsection
* Add a step for interview preferences.
Minor
=====
* Add a note in the `README.md` on skipping around the steps.
* Remove migration command related to paperclip. After removing paperclip, the migration using `add_attachment` no longer works. The suggestion [here][1] was to just rename the columns in the migration.
[1]: https://github.com/thoughtbot/paperclip/issues/1351#issuecomment-29522904
=> Ask clients how they would like to be interviewed

spec/controllers/contact_information_controller_spec.rb, spec/controllers/household_add_member_controller_spec.rb, spec/controllers/household_more_info_controller_spec.rb, spec/controllers/income_employment_status_controller_spec.rb, spec/controllers/income_other_assets_controller_spec.rb, spec/controllers/introduce_yourself_controller_spec.rb, spec/controllers/legal_agreement_controller_spec.rb, spec/controllers/mailing_address_controller_spec.rb, spec/controllers/personal_detail_controller_spec.rb, spec/controllers/preferences_interview_controller_spec.rb, spec/controllers/residential_address_controller_spec.rb, spec/controllers/sign_and_submit_controller_spec.rb, spec/support/shared_examples/param_validation.rb, spec/support/shared_examples/step_controller.rb
* Some steps don't have validation associated.
* Combining the validation shared example with the other ones then becomes brittle.
Changes
=======
* Split the shared examples into one for general steps and one for param validation.
=> Split shared examples

Gemfile, Gemfile.lock, app/steps/concerns/social_security_number.rb, app/steps/household_add_member.rb, app/steps/personal_detail.rb, spec/controllers/personal_detail_controller_spec.rb, spec/features/snap_app_spec.rb, spec/steps/household_add_member_spec.rb, spec/steps/personal_detail_spec.rb, spec/support/shared_examples/social_security_number.rb
**WHY**: So we can know that it is 9 digits when entering it,
digit-by-digit, into the 1171 PDF.
Also adds auto-strip-attributes so that if someone has an extra
whitespace when entering their SSN it is auto-stripped
This approach was inspired by the SSN formatting in GCF, which I had a
hand in.
=> Validate length of SSN

Gemfile, Gemfile.lock, app/models/snap_application_attributes.rb, app/steps/contact_information.rb, app/validators/ten_digit_phone_number_validator.rb, spec/controllers/contact_information_controller_spec.rb, spec/features/snap_app_spec.rb, spec/models/snap_application_attributes_spec.rb, spec/validators/ten_digit_phone_number_validator_spec.rb
* Moves away from phony rails, which was not working 100% of the time
* This is better for PDF filling because we want 10 digits for the PDF
* In future, might be good to allow spaces or dashes for readability.
=> Validate 10 digit phone number

app/controllers/general_anything_else_controller.rb, app/controllers/general_interview_preference_controller.rb, app/controllers/preferences_interview_controller.rb, app/steps/general_anything_else.rb, app/steps/general_interview_preference.rb, app/steps/step_navigation.rb, app/views/general_anything_else/edit.html.erb, app/views/general_interview_preference/edit.html.erb, db/migrate/20170406224506_add_anything_else_to_app.rb, db/migrate/20170824170659_add_anything_else_to_snap_application.rb, db/schema.rb, spec/controllers/general_anything_else_controller_spec.rb, spec/controllers/general_interview_preference_controller_spec.rb, spec/features/snap_app_spec.rb
* Allowing clients to add additional information about their current situation, _in their own words_ has proven valuable for food assistance applications.
Changes
=======
* Add a step in the Preferences section at the end, just before signatures.
Minor
-----
* Remove warning for hash key defined twice.
=> Allow clients to add additional information

app/views/income_additional_sources/edit.html.erb
Resolves a minor typo in the additional income types step.
=> Fix typo for unemployment insurance radio button

app/mailers/application_mailer.rb
* We are launching shortly with a non-functioning customer service email address (hello@michiganbenefits.org).
* For now, sending email to Alan is fine.
Changes
=======
* Replace the default "from" email address.
=> Replace hello@michiganbenefits.org

app/controllers/success_controller.rb, app/jobs/email_application_job.rb, app/jobs/fax_application_job.rb, app/models/snap_application.rb, db/migrate/20170829193351_add_faxed_at_to_snap_application.rb, db/schema.rb, lib/tasks/queue_faxes.rake, spec/controllers/success_controller_spec.rb, spec/jobs/email_application_job_spec.rb, spec/jobs/fax_application_job_spec.rb, spec/models/snap_application_spec.rb
Previously, we had tied together the notion of faxing the office an application with emailing the applicant. This changes it so that signed applications are automatically faxed after 30 minutes.
Changes
=======
* Split out SendApplicationJob into EmailApplicationJob and FaxApplicationJob
* Add to `SnapApplication` `#faxed_at`, `#faxed?`, and `.faxable` methods
* Write rake task to enqueue faxes `:queue_faxes`
Minor
=====
* N/A?
Risks
=====
* If we do not add a worker with a schedule, we will not send faxes
* If the queues get super backed up it's possible we could queue multiple faxes for the same application; and if both of those execute at the same time we may double fax.
=> Fax signed applications after 30 minutes of inactivity

app/assets/stylesheets/atoms/_layout.scss
I wound up accidentally pushing what I thought was a PR branch up to master; which had a bug where it hides the terms and conditions for non-mobile users.
This fixes that.
=> Don't apply mobile styles to non-mobile clients

lib/tasks/queue_faxes.rake
This is what happens when you test via the command line and not the actual rake task.
=> Load the environment when using Rails models in rake tasks

app/assets/stylesheets/michigan-benefits/atoms/_typography.scss, app/steps/success.rb, app/views/success/edit.html.erb, spec/steps/success_spec.rb
- Iconography/Illustration at the top
- "Blue Text" that says "Congratulations"
- Change the headline text
- Include subheader text that gives the client the date submitted.
- Include the specification of which program was submitted, using the icons that represent the FAP program (found on the homepage as well).
=> Update style of success page

app/controllers/success_controller.rb, app/jobs/email_application_job.rb, app/jobs/fax_application_job.rb, app/models/snap_application.rb, spec/controllers/success_controller_spec.rb, spec/jobs/email_application_job_spec.rb, spec/jobs/fax_application_job_spec.rb, spec/models/snap_application_spec.rb
@jessieay made the good point that we want our export jobs to be consistent; so I took some time to:
1. Pull up the shared behavior of PDF generation into the SnapApplication (and test it there)
2. Simplify the tests to focus on the behavior of the export
3. Simplify the Jobs themselves now that the SnapApplication owns the PDF itself.
=> Refactor pass for fax changes

app/views/contact_information/edit.html.erb, app/views/expenses_additional/edit.html.erb, app/views/expenses_housing/edit.html.erb, app/views/household_add_member/edit.html.erb, app/views/income_details_per_member/edit.html.erb, app/views/income_other_assets_continued/edit.html.erb, app/views/introduce_yourself/edit.html.erb, app/views/mailing_address/edit.html.erb, app/views/personal_detail/edit.html.erb, app/views/residential_address/edit.html.erb, app/views/shared/_address.html.erb, app/views/sign_and_submit/edit.html.erb
**WHY**: easier to use!
Note that money fields already use this because we set `type: tel` in
the money input helper method (I confirmed that this worked on mobile)
Minor: extracted shared partial for addresses since I noticed that our
two address forms were already diverging in some small ways.
=> Use numeric keyboard on mobile for number fields

config/offices.yml, spec/models/fax_recipient_spec.rb
Because [Lena said that union doesn't frequently check their fax and hasn't had training](https://cfa.slack.com/archives/C4BRQQEUU/p1504196503000049), while Clio has.
Also, because Unions fax number was wrong :X :X :X
=> Fallback office is clio, fix unions number

config/application.rb
Logging social security numbers is A Bad Idea
=> Filter out ssns from logging statements in params

README.md
* The staging link used is slightly unexpected, so it's good to document it.
Changes
=======
* Note the difference between the correct staging URL and herokuapp URL.
* Add a note about how this affects document upload on staging.
Minor
-----
* Add a section on how to get set up with Ruby on Rails.
=> Update README staging links and Ruby instructions

bin/setup
* It is required for local development but NOT in the Gemfile.
* This could be confusing.
* Why not just set it up in `bin/setup`?
Changes
=======
* Add a step to install the `foreman` gem.
=> Install foreman as part of bin/setup

bin/setup, circle.yml
**WHY**: The system command `chromedriver` starts up chromedriver, which
causes the setup script to hang indefinitely if chromedriver is already
installed.
=> Fix bin/setup chromedriver check

config/environments/production.rb
**WHY**: `debug` is the most verbose level of logging and includes SQL
logs, which was resulting in logging of our `encrypted_ssn_in`, which is
a potential security risk.
With `info`, the second most verbose level, there is no SQL logging. It
is also the default for production in Rails, so that seems like a good
place to go.
Reference:
* http://guides.rubyonrails.org/v3.2/debugging_rails_applications.html#log-levels
=> Change log level to 'info' in prod env

lib/mi_bridges/driver.rb, lib/mi_bridges/driver/benefits_selector_page.rb, lib/mi_bridges/driver/create_account_page.rb, lib/mi_bridges/driver/personal_information_page.rb, lib/mi_bridges/driver/program_benefits_page.rb
There are two benefit overview pages that the driver can click through
before coming to a more involved form page where they enter personal
information:
* Name
* Gender
* Birth date
* Address/Location
* Phone number
If the client has an address that MIBridges considers an invalid physical
address it will re-display that personal information page and confirm that
the client *still* wants to submit with that street address. If so, this
will confirm that this is, indeed, the address we would like to continue
with.
Also...
-------
* Use more specific selector for agreement checkbox
* Remove demo preable w/google search page. For demo purposes we had the driver
go to Google to search for MI Bridges before starting an application. For
purposes of actually driving the application, however, we do …
=> Click through benefits and fill in personal info

app/assets/stylesheets/atoms/_base.scss
* Make mobile layout full width
* https://trello.com/c/UliifK3D/235-sitewide-full-width-mobile-layout
Changes
=======
* Remove left/right padding on mobile
=> Make mobile layout fill width

app/assets/stylesheets/atoms/_typography.scss
* Reduce padding on bulleted lists
* https://trello.com/c/h97Zmaja/233-household-introduction-fix-padding-on-subheaders
=> Fix padding on bulleted lists

app/controllers/application_controller.rb, app/lib/feature.rb, config/environments/production.rb
**Why?** Because we're dealing with hella sensitive data here; so HTTPS should be the de-rigor.
=> Enforce SSL on production-like environments

app.json
What this will do is whenever a PR is created, it will spin up some free dynos on Heroku with our initially seeded database so we can do some pre-merge smoke testing.
=> Enable Heroku Review Apps

app/controllers/steps_controller.rb, spec/support/shared_examples/step_controller.rb
**WHAT**: this changes redirect from root path to first step. It also
ensures that someone cannot visit '/steps' without a current snap app.
**WHY**:  Experience from new teammate that was confusing:
"If I tried to click on any of the links from /steps it kicks
back to the homepage (but it doesn’t actually throw an error)"
=> Redirect to first step if there is no current app

app/controllers/contact_confirm_phone_number_controller.rb, app/steps/contact_confirm_phone_number.rb, app/steps/step_navigation.rb, app/views/contact_confirm_phone_number/edit.html.erb, app/views/contact_preference/edit.html.erb, spec/controllers/contact_confirm_phone_number_controller_spec.rb, spec/controllers/contact_preference_controller_spec.rb, spec/features/snap_app_spec.rb
**WHAT**: removing email consent option, allows client to update phone
number if they opt into SMS.
=> Update design and flow for SMS consent

Gemfile, Gemfile.lock, app/assets/stylesheets/michigan-benefits/administrate-extensions.scss, app/controllers/admin/snap_applications_controller.rb, app/controllers/success_controller.rb, app/dashboards/snap_application_dashboard.rb, app/jobs/email_application_job.rb, app/jobs/fax_application_job.rb, app/models/export.rb, app/models/funnel_stage.rb, app/models/snap_application.rb, app/views/admin/snap_applications/_collection.html.erb, app/views/admin/snap_applications/_funnel_stage.html.erb, app/views/admin/snap_applications/index.html.erb, config/initializers/administrate.rb, config/initializers/assets.rb, config/routes.rb, config/secrets.yml, db/migrate/20170831164445_create_exports.rb, db/schema.rb, lib/tasks/one_offs.rake, spec/controllers/success_controller_spec.rb, spec/factories/exports.rb, spec/factories/snap_applications.rb, spec/jobs/email_application_job_spec.rb, spec/jobs/fax_application_job_spec.rb, spec/models/export_spec.rb, spec/models/funnel_stage_spec.rb, spec/models/snap_application_spec.rb
**Why?** Administration is going to be more important as we go from 0 snap applications a day to > 9000 (OK OK, 10)
=> First pass at putting together the shape of a metrics dashboard

app/assets/javascripts/form_exit.js.erb
Since we have several new links that need to be accounted for -- namely
privacy and terms -- this JS can/should be changed to be more amenable
to changes.
This update creates a whitelist of strings that the js will look for
and, if the link contains any of those strings, it will not consider it
an external link.
TLDR, if these are substrings of something you click, the warning
message won't pop up.
=> Refactor js that warns when exiting application

app/dashboards/snap_application_dashboard.rb
**Why**? - Because sometimes not writing a feature test bites you *faster* than expected.
=> Missed a rename on merge conflict resolution

app/controllers/introduce_yourself_controller.rb, app/controllers/pages_controller.rb, app/jobs/fax_application_job.rb, app/models/fax_recipient.rb, app/steps/introduce_yourself.rb, app/views/introduce_yourself/edit.html.erb, app/views/layouts/application.html.erb, app/views/pages/_home_page_bottom_section.html.erb, app/views/pages/clio.html.erb, app/views/pages/index.html.erb, app/views/pages/union.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_demo_banner.html.erb, config/routes.rb, db/migrate/20170911213216_add_office_location_to_snap_applications.rb, db/schema.rb, spec/controllers/introduce_yourself_controller_spec.rb, spec/features/office_specific_landing_pages_spec.rb, spec/jobs/fax_application_job_spec.rb, spec/models/fax_recipient_spec.rb, spec/routing/pages_routing_spec.rb
* Starting an app from either of these pages sets the "office location"
attribute, which receives highest priority when deciding who to fax.
=> Add office-specific landing pages for Union and Clio

lib/tasks/one_offs.rake, lib/tasks/queue_faxes.rake
*Why* Because the 30m enqueue job is currently not working.
See https://trello.com/c/0uVGs3b3/275-the-rake-task-that-queues-up-unsent-faxes-should-not-fail
Sentry: https://sentry.io/app73768247herokucom-6k/app73768247herokucom/issues/347534988/?referrer=slack
=> Fix rake tasks that got overlooked in refactor passes

app/assets/stylesheets/templates/_homepage.scss, app/views/pages/clio.html.erb, app/views/pages/union.html.erb, spec/features/office_specific_landing_pages_spec.rb
* Updates to Office home pages
* https://trello.com/c/8KhTAItA/248-as-a-client-i-want-to-visit-an-office-homepage-so-that-i-can-be-seen-immediately
Changes
=======
* Update subheader and button copy
* Add link back to main homepage
=> Update Office homepage copy and links

app/views/personal_detail/edit.html.erb, lib/mi_bridges/driver.rb, lib/mi_bridges/driver/base_page.rb, lib/mi_bridges/driver/basic_information_summary_page.rb, lib/mi_bridges/driver/click_next_page.rb, lib/mi_bridges/driver/debugger_page.rb, lib/mi_bridges/driver/disability_or_blindness_review_page.rb, lib/mi_bridges/driver/finish_page.rb, lib/mi_bridges/driver/household_member_questions_page.rb, lib/mi_bridges/driver/household_members_summary_page.rb, lib/mi_bridges/driver/housing_bills_page.rb, lib/mi_bridges/driver/housing_utility_bills_page.rb, lib/mi_bridges/driver/housing_utility_bills_summary_page.rb, lib/mi_bridges/driver/job_income_information_page.rb, lib/mi_bridges/driver/job_income_summary_page.rb, lib/mi_bridges/driver/liquid_assets_page.rb, lib/mi_bridges/driver/liquid_assets_summary_page.rb, lib/mi_bridges/driver/mailing_address_page.rb, lib/mi_bridges/driver/money_other_sources_page.rb, lib/mi_bridges/driver/money_other_sources_summary_page.rb, lib/mi_bridges/driver/other_assets_page.rb, lib/mi_bridges/driver/other_assets_summary_page.rb, lib/mi_bridges/driver/people_listed_page.rb, lib/mi_bridges/driver/school_details_page.rb, lib/mi_bridges/driver/submit_page.rb, lib/mi_bridges/driver/utility_bills_page.rb, lib/mi_bridges/driver/your_other_bills_expenses_page.rb, lib/mi_bridges/driver/your_other_bills_expenses_summary_page.rb
Quick-start to trying this
-------------------------
```
$ bundle exec rake db:seed
Creating minimal snap application...
Minimal application created (or found) with id: 3
Creating a more complete snap application...
More complete application created (or found) with id: 4
```
Take note of the "minimal application" id (3) as it will be used when you test the driving.
```
$ bundle exec rails runner "DriverApplication.destroy_all"
$ WEB_DRIVER=chrome DEBUG_DRIVE=true ./bin/rails runner "MiBridges::Driver.new(snap_application: SnapApplication.find(3)).run"
```
Destroying all the `driver_applications` records ensures you are creating a brand new MIBridges application instead of signing in with an existing one.
Abstract the conditional checking of boxes
========================================== …
=> Fill out more driving pages and abstract some common patterns

bin/setup
`gs` is a dependency of our test suite. After running into a
**command `gs` not found** error I reckon this should be added to the
setup script for future developers.
=> Add ghostscript to setup script

lib/mi_bridges/driver/housing_utility_bills_page.rb
* While testing a driving code PR, an error was caught.
* That error was `undefined local variable or method 'check_utility_bills' for #<MiBridges::Driver::HousingUtilityBillsPage:0x007fa7a7b31b30>`.
* This led me to realize this method was not defined.
Changes
=======
* Remove the method call.
=> Remove undefined method call

app/assets/javascripts/upload_setup.js, app/assets/stylesheets/atoms/_utilities.scss, app/assets/stylesheets/organisms/_document-preview.scss, app/views/documents/_document.html.erb, app/views/documents/_uploading.html.erb, app/views/documents/edit.html.erb
As a step towards locking down access to files uploaded to S3 we must no
longer display the successful image URL after the file is uploaded.
Instead, let's just keep the preview element there and let the JS show the
contents of the file that way.
Also pull in the work Rachel and Zee did to display upload errors inline
within the preview element. Including:
* Allow files up to 8Mb in size
* Don't show the warning by default
* Add error message for small photo sizes
=> Do not display newly uploaded file post-upload

bin/release-diff
* Our deploy script opens up a giant diff every time because the production server hadn't had a real git push in a long long time. This wasn't very usable because it had lots of noise and stuff outside of the actual changes between production and staging. This tightens it up to comparing the latest production deploy to the latest staging deploy.
* https://trello.com/c/fZg67unC/306-improve-readability-of-deploy-diffs
=> Tighten up that release diff

CONTRIBUTING.md, bin/drive, bin/drive_demo, bin/drive_dev, lib/mi_bridges/driver.rb
* I kept having to look up docs on how to run the driver against a particular app, so I scripted it?
Minor
=====
* I got rid of that `destroy_all` in the Driver setup, since I don't think we actually want to be destroying all?
=> Make it easier to drive a given application

app/dashboards/snap_application_dashboard.rb, app/jobs/fax_application_job.rb, app/models/fax_recipient.rb, app/models/snap_application.rb, config/offices.yml, spec/jobs/fax_application_job_spec.rb, spec/models/fax_recipient_spec.rb
* When working on another ticket, I had noticed that we said "Michigan Bridges" as the recipient which is... annoying at best and misleading at worst. I wanted to make sure we could more easily answer the question of "Which office did the fax go to?" and "Which office did should the fax go to?"
=> Expose the office name in the dashboard

app.json
* Heroku kept saying deploys failed, which was making me worried we can't use review apps very effectively when they are useful. I think it's because `db:setup` does a create operation which fails.
=> OK, maybe this won't fail on first build?

lib/mi_bridges/driver/create_account_page.rb
* During sign IN, MI Bridges only lets you answer security questions
with answers up to 20 chars
* 32 is default string length for SecureRandom
=> Limit MI Bridges secret question answer char count

app/assets/stylesheets/atoms/_buttons.scss
* https://trello.com/c/dk9B6ndW/303-full-width-continue-button-on-mobile
* Make Next button full width on mobile
=> Make Next button full width on mobile

app/models/remote_document.rb, config/secrets.yml
* AWS requires us to tell it which region to check against when downloading files; however Bucketeer's `BUCKETEER_REGION` isn't picked up automatically by the S3 gem.
* https://trello.com/c/G9MsDFD1/325-awsregion-missing-on-staging-prod
=> Use the correct region when retrieving files

app/models/export.rb, app/models/snap_application.rb, spec/models/export_spec.rb
* Closing the PDF also opened it, which seems unnecessary.
* Debugging exports was weird because we would say the export succeeded, even if the Job still existed because an exception was raised as part of our ensure statement.
* https://trello.com/c/pcoLnZzS/326-fail-exports-appropriately-when-ensure-fails
Minor Changes
=======
* If we fail at any time, let's mark the export as failed.
=> Don't close PDFs if they haven't been opened

app/assets/stylesheets/michigan-benefits/administrate-extensions.scss, app/controllers/success_controller.rb, app/jobs/client_email_application_job.rb, app/jobs/office_email_application_job.rb, app/mailers/application_mailer.rb, app/models/export.rb, app/models/export_factory.rb, app/models/office_recipient.rb, app/models/snap_application.rb, app/views/admin/snap_applications/index.html.erb, app/views/application_mailer/office_application_notification.html.erb, config/offices.yml, spec/controllers/success_controller_spec.rb, spec/factories/exports.rb, spec/factories/snap_applications.rb, spec/features/admin_dashboard_spec.rb, spec/jobs/client_email_application_job_spec.rb, spec/models/export_factory_spec.rb, spec/models/export_spec.rb, spec/models/office_recipient_spec.rb
Once a snap application is submitted, in order to make the review of the
application as quick as possible we should email the field office that best
corresponds to the address of the submitting client.
In order to do so:
* Change :email to :client_email and add :office_email. Until now we've only
emailed the application to a client, but now want to email the application to
the appropriate field office when the application is done. This changes
:email to :client_email to be more specific, and adds :office_email as a
possible destination for the export process.
* Rename `EmailApplicationJob` to `ClientEmailApplicationJob`.  This is one use
case for emailing the generate PDF and should be qualified as such. The next
commit will introduce an `OfficeEmailApplicationJob` that will send an email …
=> Send email to field office after submission

bin/drive_dev
* It wasn't clear that an ID needed to be passed to `bin/drive_dev` until inspecting the script.
Changes
=======
* Just a bit of script UI logic.
=> Driver script needs an argument

lib/mi_bridges/driver.rb, lib/mi_bridges/driver/base_page.rb, lib/mi_bridges/driver/mailing_address_page.rb, lib/mi_bridges/driver/more_about_self_employment_page.rb, lib/mi_bridges/driver/pregnancy_information_page.rb
Page objects for "Mailing Address", "Pregnancy Information", and
"More about <PERSON>'s Self Employment". A bigger change as a result of
the "Self-Employment" section is that the string we're testing against
in the H1 can now be dynamic - it can reference a member of the
application as per this example.
As a result this commit will check for both equality of the string, and
whether there is a match in the chance we make `TITLE` a regular
expression.
=> Pages for mailing addr, pregnancy, self-employment

lib/mi_bridges/driver/base_page.rb, lib/mi_bridges/driver/people_listed_page.rb, lib/mi_bridges/driver/personal_information_page.rb
**WHY**:
If a household has more than 1 member, the "People listed" form needs to
be filled out for each additional member.
For non-primary members, required fields are:
- first name
- last name
- marital status
- gender
- DOB
- whether they live in the same household as the primary member
To test, run the driving code with `bin/drive_dev` using the ID of a Snap Application that has more than one household member.
We are determining which household members have not yet been added by checking to see whose "first_name_and_age" is not already on the page. See:
=> Add personal information for additional household members

app/models/member.rb, lib/mi_bridges/driver/base_page.rb, lib/mi_bridges/driver/household_member_questions_page.rb, lib/mi_bridges/driver/housing_utility_bills_page.rb, lib/mi_bridges/driver/job_income_information_page.rb, lib/mi_bridges/driver/liquid_assets_page.rb, lib/mi_bridges/driver/money_other_sources_page.rb, lib/mi_bridges/driver/more_about_self_employment_page.rb, lib/mi_bridges/driver/other_assets_page.rb, lib/mi_bridges/driver/people_listed_page.rb, lib/mi_bridges/driver/personal_information_page.rb, lib/mi_bridges/driver/your_other_bills_expenses_page.rb, spec/models/member_spec.rb
**WHY**:
- MI Bridges has a 15 char limit
- Shorten name differentiator by removing "age" from parens
- Only include first 10 chars of name so that age never cut off
=> Improve first name formatting for MI Bridges

db/seeds.rb, lib/mi_bridges/driver.rb, lib/mi_bridges/driver/relationship_information_page.rb
* This was a doozy!
* The way MI Bridges handles this is that it starts with a page for the
primary member and asks how that person is related to every other
household member.
* The next page asks how the second household member is related to every
other member who is not the primary member
* The third page asks how the third household member is related to ever
member who is not the first or second member
* Etc etc
I tested this locally using a household with 4 members so I have pretty
high confidence that it will work for a household of any size.
NOTE that there are a few weird things here:
1. The relationship mapping is flipped. In our app, we ask 'What is their relationship to you?',
but MI Bridges asks the relationship of the first person to the second.
So if I am the primary member, …
=> Add relationship details for all household members

bin/release-diff, config/offices.yml
* Grep for "deploy" in heroku releases (if the last change to heroku was
updating an ENV var, the `bin/release-diff` command opens up an invalid
URL because there is not a commit SHA in the latest heroku "release"
* Set up "staging" app release stage for faxes and emails.
* Send staging test emails to hello@michiganbenefits.org, which goes to
front so we all have access to it / can view it.
Screenshot of invalid diff (before "GREP"):
=> Improvements to release script

Gemfile.lock, bin/drive_demo
Like the script in `bin/drive_dev` the `drive_demo` script should enforce that
an id has been passed to the script as an argument
=> Ensure id is passed as argument to `drive_demo`

.rubocop.yml
```sh
Warning: unrecognized cop Naming/BinaryOperatorParameter found in .rubocop.yml
```
=> Remove `Naming/BinaryOperatorParameter` cop

app/models/member.rb, app/views/income_details_per_member/edit.html.erb, lib/mi_bridges/driver.rb, lib/mi_bridges/driver/job_income_more_about_page.rb, lib/mi_bridges/driver/other_types_of_income_page.rb, lib/mi_bridges/errors.rb, spec/features/snap_application_with_maximum_info_spec.rb
In addition, add more information about when we hit the specific error
when a page's title is not found in our registry of page objects.
Why? Because it will tell us exactly what the page title is that is
being searched for, therefore allowing us to add a page that adheres to
the pattern.
=> Add "More about <user>'s income'" page

db/seeds.rb, lib/mi_bridges/driver/personal_information_page.rb
**WHY**
* We do not validate residential street / city / zip if unstable address
* MI Bridges has same behavior/
* If someone's address is unstable and we do not mark as homeless,
driving could fail because we may not have street/city/zip
TO TEST:
* re run rake db:seed
* run driver with minimal application
=> Check "homeless" box if address is unstable

lib/mi_bridges/driver/money_other_sources_page.rb
**WHY**: I didn't catch this before because MI Bridges only shows this
question if there is someone under 18 in the household.
The tricky thing about this is that we know if *anyone* receives child
support income in a household, but MI Bridges wants to know which child.
After you select a name, it follows up with a queston about the amount
of child support income for each name selected.i
Options are:
- always say "no one" (easiest - already done via this PR)
- always select first child (second easiest)
- collect more granular child support data in MI Benefits so we can fill
this out accurately (hardest)
In order to know which is best, it would be good to get context on the
importance of this question for the county workers.
question:
screen you see if you check a box next to a name:
=> Add default response for Child support question

.env.sample, app/views/application_mailer/office_application_notification.html.erb, config/environments/production.rb, config/environments/test.rb, config/offices.yml, spec/models/office_recipient_spec.rb
**WHY**:
- "staging_sfax" made more sense when this file represented fax numbers,
but now it represents offices. When we set the zip to 12345, we want to
send an email/fax to the "test" office. Se we renamed it "test office" !
- the production URL used to be hardcoded into the email signature. Now
it's dynamic.
email footer:
=> Rename "test" office and add URL to email signature

lib/mi_bridges/driver.rb
* The way the logic was before, it would exit out of the `while` once it
got to the `SubmitPage`, but we want it to arrive there so that we can
inspect the outcome. 
* This is pre-work for the next step, which is
submitting then app and then uploading documents.
=> Visit SubmitPage during MI Bridges flows

app/models/driver_application.rb, app/models/driver_error.rb, db/migrate/20171002204734_create_driver_errors.rb, db/schema.rb, lib/mi_bridges/driver.rb, spec/factories/driver_errors.rb, spec/models/driver_application_spec.rb, spec/models/driver_error_spec.rb
When driving errors out, we should get some visibility into _why_ things
failed. The information we have available upon exceptions being caught
are the exceptions themselves, the message property in the exception,
the current page object we are attempting to run, and the contents of
the page we are on currently.
=> Save error info for all failed driving attempts

app/models/member.rb, app/services/hourly_income_calculator.rb, app/services/monthly_income_calculator.rb, lib/mi_bridges/driver/more_about_job_income_page.rb, spec/models/member_spec.rb, spec/services/hourly_income_calculcator_spec.rb, spec/services/monthly_income_calculator_spec.rb
**WHY**:
- we known pay quantity "per interval". Before, we were filling in the
hourly rate as whatever the pay quantity was, which is only accurate if
the interval happens to be hourly. For all other intervals, slightly
more complex calculations are required.
- took this opp to move the monthly income calculator into its own class
as well.
=> Calculate hourly wage based on pay interval

app/jobs/office_email_application_job.rb, app/mailers/application_mailer.rb, app/views/application_mailer/in_office_application_notification.html.erb, app/views/application_mailer/office_application_notification.html.erb, spec/mailers/application_mailer_spec.rb
**WHY**: to alert office staff
=> Use different email subject/body when client in office

Gemfile, bin/re_drive_prod, config/database.yml, config/environments/production.rb
**WHY**:
- if a drive fails, this is the simplest way to debug
**HOW**:
- run `bin/re_drive_prod`
- script prompts you for the id of a Snap App and which env you're
targeting
- note that this only works for Snap Apps that have *already* been driven once (logs in with existing driver account in MI Bridges, which will fail if there is no existing account)
- try it out yourself with ID 236 and staging env!
=> Add script for re-driving applications from Heroku

app/controllers/success_controller.rb, app/jobs/drive_application_job.rb, spec/controllers/success_controller_spec.rb, spec/rails_helper.rb, spec/support/background_jobs.rb
* When success page is reached, app is driven
* If app was already driven, do not re-drive
* We are not submitting apps on MI Bridges yet, we only get to the
submit page, but this will allow us to test our driving
code with real data so we can feel more confident when we do start
submitting.
Minor:
* Add helper for running background jobs immediately, h/t https://robots.thoughtbot.com/process-jobs-inline-when-running-acceptance-tests
=> Drive all new Snap Apps

lib/mi_bridges.rb, lib/mi_bridges/driver.rb
Rails' auto-loading might be having a hard time pulling in all of the
driving code because the MiBridges module, which we namespace all our
driving code inside of, is not defined in its own file.
Also:
* In `save_error`, if latest_drive_attempt is null we should not try to
tap into it.
=> Add MiBridges module to fix autoloading

config/environments/development.rb, config/environments/test.rb, config/initializers/extensions.rb, lib/mi_bridges.rb
* set `eager_load` to true in all envs to reproduce issue
* add initializer to require files in lib dir
* later, move Driver code elsewhere
* See
https://stackoverflow.com/questions/38198668/rails-5-load-lib-files-in-production/40019108#40019108
for more
=> Attempt to fix autoloading issue on prod env

app.json, app/steps/household_add_member.rb, app/steps/personal_detail.rb, lib/capybara/drivers/headless_chrome.rb, lib/find_chrome.rb
There are a number of dependencies needed to get things driving properly. This PR gets everything set up so that things work.
1. Add chrome and chromedriver buildpacks
2. Use the ENV provided by the Chrome buildpack for the chrome binary
3. Fix issue where we require a concern twice. It breaks due to the callback run upon requiring the file
4. Set `WED_DRIVER` ENV so that the driver doesn't try to run it with the full chrome browser experience
5. Use a fork of the PDFTK buildpack due to a bug that causes conflicts with the other buildpacks
6. Add `no-sandbox` to the list of options provided to the headless chrome driver configuration. Otherwise it crashes
7. Update app.json to inherit attr_encrypted secrets instead of generating them
=> Add chrome and chromedriver buildpacks to app.json

db/migrate/20171005165616_add_driven_at_to_driver_errors.rb, db/schema.rb, lib/mi_bridges/driver.rb, lib/mi_bridges/driver/create_account_page.rb, lib/mi_bridges/driver/home_log_in_page.rb, spec/factories/driver_application.rb, spec/factories/driver_errors.rb
When we create and drive an application we are saving the information about
the drive to a `driver_applications` record. When these drives occur we
should be recording the date and time WHEN the drive is occurring. In
addition, the associated errors should have the same time set to them so
that errors can be grouped by the time they were all run by its parent
`DriverApplication` object.
=> Record when apps (and its errors) are driven

app/controllers/medicaid/intro_location_controller.rb, app/controllers/standard_steps_controller.rb
Let `existing_attributes` and `step_class` defer to their super classes.
Existing attributes can have the nil object problem fixed with the
lonely `&` operator. This well return nil and get wrapped by the
HashWithIndifferentAccess ... returning an empty hash
```ruby
HashWithIndifferentAccess.new(nil) => {}
```
`step_class` successfully infers the correct, namespaced, class from the
controller path as it is -- not sure why it didn't work for us in
development mode earlier.
=> Small refactor of IntroLocationController

Gemfile, Gemfile.lock, Rakefile, config/initializers/strong_migrations.rb, db/schema.rb
There are two reasons why I'm suggesting we add these gems.
1. We're running into odd issues with the schema file being generated
and causing diff issues when something like overcommit is run. This has
prevented several people from rebasing a branch and can be mitigated if
the schema has a more predictable diff, and is generated only when it's
necessary. `strong_migrations` helps us with that. See:
* https://github.com/ankane/strong_migrations#schema-sanity
* https://github.com/ankane/strong_migrations#faster-migrations
2. We're continuing to generate and run many new migrations - therefore
the constraints inherant with these gems will help us move more
carefully, and in some places with more speed. Constraints are good.
In this commit I've added initialization configuration as suggested …
=> Add good and strong migrations gems

app/models/export_factory.rb, app/models/snap_application.rb, lib/tasks/queue_faxes.rake, spec/models/export_factory_spec.rb
* We are now emailing applications to MDHHS instead of faxing them.
* We would also like to keep our valuable fax machinery intact, just in case.
Changes
=======
* Remove the rake task which sends unfaxed applications.
* The Heroku scheduler task had already been shut off - this is just to make sure.
Minor
=======
* Rename the spec to match the method name.
=> Remove fax rake task

app/assets/javascripts/form_exit.js.erb
Add the "dual-index" path to the white-list of paths that will not cause
the "you are exiting the app" message to pop up.
=> No alert after completing Medicaid application

app/controllers/medicaid/confirmation_controller.rb, app/views/medicaid/confirmation/edit.html.erb
Overriding both the back_path var AND the previous_path method to both
return nil will result in the back arrow not showing up.
=> Do not display back arrow on final submission page

app/controllers/steps_controller.rb, spec/controllers/medicaid/amounts_expenses_controller_spec.rb, spec/controllers/medicaid/contact_home_address_controller_spec.rb, spec/controllers/medicaid/contact_homeless_controller_spec.rb, spec/controllers/medicaid/contact_mailing_address_controller_spec.rb, spec/controllers/medicaid/contact_other_address_controller_spec.rb, spec/controllers/medicaid/contact_residential_no_mail_address_controller_spec.rb, spec/controllers/medicaid/income_job_number_controller_spec.rb
This commit adds some tests to back the recently created medicaid flow
controllers. The logic around skipping to the next page needs some
robust test coverage to ensure the logic does not break in the future.
Also move the `next_path` method to the public method space so we can
call it from the specs to test that they are skipping to the correct
"next" path.
=> Add test coverage for controllers re: skip logic

app/steps/medicaid/contact_home_address.rb, app/steps/medicaid/contact_mailing_address.rb, app/steps/medicaid/contact_residential_no_mail_address.rb, spec/steps/medicaid/contact_home_address_spec.rb, spec/steps/medicaid/contact_mailing_address_spec.rb, spec/steps/medicaid/contact_residential_no_mail_address_spec.rb
There is some duplication here, but we are likely going to change the address flow soon anyway so didn't seem worth time investment to add a shared example until we are clearer on which forms we are keeping.
=> Validate address forms for Medicaid flow

app/controllers/success_controller.rb, app/models/snap_application.rb, spec/controllers/success_controller_spec.rb, spec/models/snap_application_spec.rb
If there is no signature on a snap application then they should *not* be
sent to the offices in MI. This can occasionally happen if someone is
skipping steps or bouncing around the application and not filling
everything out sufficiently.
This commit introduces a guard clause in the final success controller
that will bail out of the Export/Driving work if the application is not
"done" enough. For now this checks for only the signature being present.
In the future it stands to reason that there will be further conditions
that define whether or not an application is "done".
=> Only export apps when they're sufficiently done

app/controllers/admin/exports_controller.rb, app/dashboards/export_dashboard.rb, app/dashboards/member_dashboard.rb, app/dashboards/snap_application_dashboard.rb, config/routes.rb, db/seeds.rb
In order to get more visibility as to *where* and *when* applications are sent
to the offices in MI we can display the exports in the admin in the context of
their parent snap application.
This commit adds the resource to the admin and adjusts the seed task to create
some fake data for local testing and demo'ing.
=> Display exports for snap apps in admin/dashboard

app/controllers/steps_controller.rb, app/models/medicaid_application.rb, app/models/snap_application.rb, app/views/steps/index.html.erb, config/routes.rb, spec/controllers/steps_controller_spec.rb
The steps page had run into some issues sometime in the recent past and
was 500'ing out. This commit fixes that issue, as well as:
1. Adds the medicaid steps to the steps index
2. Displays either/or/both the snap and medicaid steps only if there's
a respective id present in the session.
3. If there is no id present, user is redirected to the homepage
4. Add a controller spec to ensure this continues to be functional
5. Join the two application sections in the routes
=> Fix steps page and display medicaid steps

.gitignore, app/controllers/medicaid/intro_household_controller.rb, app/controllers/medicaid/intro_household_member_controller.rb, app/controllers/medicaid/intro_name_controller.rb, app/dashboards/member_dashboard.rb, app/models/medicaid_application.rb, app/models/member.rb, app/models/snap_application.rb, app/steps/medicaid/intro_household.rb, app/steps/medicaid/intro_household_member.rb, app/steps/medicaid/intro_name.rb, app/views/medicaid/intro_household/edit.html.erb, app/views/medicaid/intro_household_member/edit.html.erb, app/views/medicaid/intro_name/edit.html.erb, db/migrate/20171017191829_extract_members_from_medicaid_app.rb, db/schema.rb, db/seeds.rb, lib/mi_bridges/driver/services/submit_relationship.rb, spec/factories/member.rb, spec/factories/snap_applications.rb, spec/features/medicaid_spec.rb, spec/jobs/fax_application_job_spec.rb, spec/steps/medicaid/intro_name_spec.rb
For single member flow, it made sense to save some user details on the application.
Now with multiple members, it made sense to move that information from the application and into the member class. To do this, we made applications (Snap and Medicaid) a polymorphic association on the Member class.
To test, create a Medicaid application and confirm you can add multiple members.
=> Allow multiple members for Medicaid application

app/controllers/medicaid/income_job_number_continued_controller.rb, app/controllers/medicaid/income_job_number_controller.rb, app/steps/medicaid/income_job_number.rb, app/steps/medicaid/income_job_number_continued.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/income_job_number_continued/edit.html.erb, db/migrate/20171018174809_number_of_jobs_to_integer.rb, db/schema.rb, spec/controllers/income_expenses_job_number_controller_spec.rb, spec/controllers/medicaid/income_job_number_continued_spec.rb, spec/controllers/medicaid/income_job_number_controller_spec.rb
* This PR adds a "new_job_number" column, which is an integer rather
than a string. The old job number column will be removed in a follow up
PR and `new_job_number` renamed to `job_number`.
* Next up is adding income inputs for each job.
* Open question:
* How do we feel about defaulting the number to 4 on the "continued" page?
=> Allow clients to select up to 10 jobs

app/jobs/office_email_application_job.rb
When an export is executed, the block we pass to it can accept a logger
object which, when written/outputted to, will save to the export object
AND log to stdout.
Our email job has not been doing this so this commit changes it to do so
with not only the receiving office, but the id of the client who is
submitting it.
=> Log info about email to both export & logger

app/models/driver_application.rb
When running the test suite we see a LOT of instances of the following:
```
DEPRECATION WARNING: user_id is not an attribute known to Active Record.
This behavior is deprecated and will be removed in the next version of
Rails. If you'd like user_id to be managed by Active Record, add
`attribute :user_id to your class. (called from block (3 levels) in <top
(required)> at ./spec/models/snap_application_spec.rb:235)
```
This is due to the `attribute` class method not liking being given an
array of symbols as a parameter. Passing each attribute to the
`attribute` method fixes this.
=> Silence deprecation errors re: AR + attr_encrypted

app/controllers/medicaid/insurance_needed_controller.rb, app/controllers/medicaid/intro_college_controller.rb, app/controllers/medicaid/intro_college_member_controller.rb, app/controllers/medicaid/many_member_steps_controller.rb, app/steps/medicaid/intro_college.rb, app/steps/medicaid/intro_college_member.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/intro_college/edit.html.erb, app/views/medicaid/intro_college_member/edit.html.erb, config/locales/en.yml, db/migrate/20171020000142_rename_college_student_to_anyone_in_college.rb, db/schema.rb, spec/controllers/medicaid/amounts_income_controller_spec.rb, spec/controllers/medicaid/intro_college_controller_spec.rb, spec/controllers/medicaid/intro_college_member_controller_spec.rb, spec/features/medicaid_spec.rb, spec/steps/medicaid/intro_college_member_spec.rb
* Uses I18N for pluralization of page title for member college selection. If there is a single member, show "Are you currently a college student?" as title. Otherwise, show "Is anyone currently a college student?" as title.
* Changes 'college_student' field to 'anyone_in_college' on medicaid_application table
* On single-member, mark primary member as in_college after college intro screen
=> Specify which members are in college for multi-member flow

app/controllers/medicaid/income_job_number_continued_controller.rb, app/controllers/medicaid/insurance_needed_controller.rb, spec/controllers/medicaid/income_job_number_continued_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb
* Needed to update `skip` logic in `IncomeJobNumberContinuedController`
* This was not surfaced earlier due to insufficient testing, so took
this opportunity to reorganize and add more meat to our feature specs.
=> Fix Medicaid bug for unemployed clients

app/views/fields/date_time/_index.html.erb, app/views/fields/date_time/_show.html.erb, spec/controllers/medicaid/amounts_income_controller_spec.rb, spec/features/admin_dashboard_spec.rb
Customizes a partial for administrate to convert and format any DateTime fields on detail pages to the same way they're shown elsewhere in the app for SNAP applications (using SnapApplication#signed_at_est as guide). End result should be that all full timestamps in the admin dashboard are now shown in EST rather than UTC.
Does not convert Date objects on index pages to EST.
Pages & fields affected:
**On snap_application#show (e.g. admin/snap_applications/1):**
* Created at
* Updated at
* Signed at
**On export#show (e.g. admin/exports/2):**
* Completed at
* Created at
* Updated at
**On member#show (e.g. admin/member/2):**
* Created at
* Updated at
=> Convert all timestamps in admin dashboard to EST.

config/environments/development.rb
* We set this so we could see same setup as prod
* This leads to annoying occassional errors in dev mode
* Previous load issue is no longer around so we can safely go back to
`eager_load: false`, which is the Rails default
=> Set eager_load to false in dev mode

app/controllers/skip_send_applications_controller.rb, app/controllers/snap_steps_controller.rb, app/controllers/success_controller.rb, spec/controllers/success_controller_spec.rb
**WHY**: This is a better UX and will prevent people from re-applying
from the wrong page when testing the app when in offices.
=> Redirect to office-specific landing pages after SNAP submitted

app/controllers/medicaid/income_job_number_continued_controller.rb, app/controllers/medicaid/income_job_number_controller.rb, app/controllers/medicaid/income_job_number_member_controller.rb, app/controllers/medicaid/insurance_needed_controller.rb, app/controllers/medicaid/many_member_steps_controller.rb, app/controllers/medicaid_steps_controller.rb, app/models/member.rb, app/steps/medicaid/income_job_number_member.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/income_job/edit.html.erb, app/views/medicaid/income_job_number_member/_header.html.erb, app/views/medicaid/income_job_number_member/edit.html.erb, config/locales/en.yml, db/migrate/20171024000703_add_number_of_jobs_to_members.rb, db/schema.rb, spec/controllers/medicaid/income_expenses_job_number_controller_spec.rb, spec/controllers/medicaid/income_job_number_continued_spec.rb, spec/controllers/medicaid/income_job_number_controller_spec.rb, spec/controllers/medicaid/income_job_number_member_controller_spec.rb, spec/factories/medicaid_applications.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/support/feature_helper.rb
* This is mostly complete but will required a follow up PR to:
- update employment_status, employed_job_number attrs on primary member when only one member present
- remove job_number field from medicaid_applicatiomns table
- rename `employed` on medicaid_applications, since that column is meant to indicate whether *anyone* is employed
=> Add employed / job number steps for multi-member flow

app/controllers/medicaid/citizens_controller.rb, app/steps/many_members_step.rb, app/steps/medicaid/citizen.rb, app/steps/medicaid/intro_citizen.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/citizens/edit.html.erb, app/views/medicaid/intro_citizen/edit.html.erb, config/locales/en.yml, db/migrate/20171024202046_rename_citizen_to_everyone_a_citizen.rb, db/schema.rb, spec/controllers/medicaid/citizens_controller_spec.rb, spec/controllers/medicaid/intro_citizen_controller_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb
If the primary client answers that there is someone in the household that
is not a US citizen then they should be taken to a page that asks them
*who* is not a citizen.
=> Verify us citizenship across all household members

Gemfile, Gemfile.lock, spec/factories/address.rb, spec/factories/driver_application.rb, spec/factories/driver_errors.rb, spec/factories/exports.rb, spec/factories/medicaid_applications.rb, spec/factories/member.rb, spec/factories/snap_applications.rb, spec/factories/users.rb, spec/models/snap_application_spec.rb, spec/support/factory_bot.rb, spec/support/factory_girl.rb
The folks at thoughtbot have made the name switch from `girl` to `bot`.
https://robots.thoughtbot.com/factory_bot
Moving forward, all versions of the gem will continue with the new name.
(Editorial note: I, for one, welcome the change. If this made even one
person uncomfortable, let alone many, then the name needs changing)
=> FactoryGirl is no more. FactoryBot is here.

app/controllers/medicaid/amounts_expenses_controller.rb, app/controllers/medicaid/amounts_income_controller.rb, app/controllers/medicaid/income_self_employment_controller.rb, app/controllers/medicaid/income_self_employment_member_controller.rb, app/models/member.rb, app/steps/medicaid/income_self_employment.rb, app/steps/medicaid/income_self_employment_member.rb, app/steps/medicaid/intro_college_member.rb, app/steps/medicaid/step_navigation.rb, app/views/income_details_per_member/edit.html.erb, app/views/medicaid/amounts_expenses/edit.html.erb, app/views/medicaid/amounts_income/edit.html.erb, app/views/medicaid/income_self_employment/edit.html.erb, app/views/medicaid/income_self_employment_member/edit.html.erb, config/locales/en.yml, db/migrate/20171025170306_add_self_employed_to_members.rb, db/migrate/20171025173052_rename_self_employed_to_anyone_self_employed_on_medicaid_applications.rb, db/schema.rb, spec/controllers/medicaid/amounts_expenses_controller_spec.rb, spec/controllers/medicaid/amounts_income_controller_spec.rb, spec/controllers/medicaid/income_self_employment_controller_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/steps/medicaid/income_self_employment_member_spec.rb
* If anyone is self employed, show page with checkboxes to indicate WHO
* If single member household, mark member as self employed if "yes" to
general question of "are you self employed"
* Rename `self_employed` to `anyone_self_employed` on medicaid apps for
consistency
* Add `self_employed` boolean field to `members` table because a member
can be self employed AND employed in medicaid flow, so string for `employment_status` was
not enabling our medicaid app flow.
* Remove `self_employed?` method on `Member` to avoid collision with
boolean predicate methods provided by Rails.
=> Add self-employed multi-member flow for Medicaid

app/controllers/medicaid/income_job_controller.rb, app/models/member.rb, app/views/income_details_per_member/edit.html.erb, db/migrate/20171025173052_rename_self_employed_to_anyone_self_employed_on_medicaid_applications.rb, db/migrate/20171025184755_add_employed_as_boolean_to_medicaid.rb, db/schema.rb, spec/controllers/medicaid/income_job_controller_spec.rb
Also removes `employed?` method from Member, and updates SNAP flows that were using accordingly.
=> Add boolean employed field to members for Medicaid flow

app/controllers/medicaid/income_other_income_type_controller.rb, app/steps/medicaid/income_other_income.rb, app/views/medicaid/income_other_income/edit.html.erb, config/locales/en.yml, db/migrate/20171025225850_rename_income_not_from_job_to_anyone_other_income.rb, db/schema.rb, spec/controllers/medicaid/income_other_income_type_controller_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb
* Adds dynamic title to other income page (for household size)
* Renames field to `anyone_other_income` for consistency
* Next steps:
* add `other_income` boolean to members table
* update single member household based on `yes/no` page
* add page to determine which members receive other income for
multi-member flow
* add page to determine what kind of other income those people receive
(in multi-member context, we already have that for single member)
=> Part I of "other income" for multi-member flow

app/controllers/introduction_change_office_location_controller.rb, app/steps/introduction_change_office_location.rb, app/steps/step_navigation.rb, app/views/introduction_change_office_location/edit.html.erb, app/views/introduction_complete/edit.html.erb, db/migrate/20171025184755_add_employed_as_boolean_to_medicaid.rb, spec/features/snap_application_change_location_spec.rb
**WHY**:
- this surfaces the office location after the "Introduction" section of
the SNAP application flow
- if the office location is not what is expected, it can be changed.
- this is useful when someone is applying in an MDHHS office but their
address maps to a different location. We have office-specific landing
pages to override this, but sometimes people forget to use those and
they should be able to correct the location before submission.
=> Enable SNAP clients to change office location

app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss, app/assets/stylesheets/michigan-benefits/organisms/_main-footer.scss, app/views/contact_preference/edit.html.erb, app/views/general_anything_else/edit.html.erb, app/views/income_change/edit.html.erb, app/views/shared/_footer.html.erb
* Add persistent lock icon and security message
* https://trello.com/c/7pl1FU9W/499-add-lock-and-security-message-to-footer
=> Add security icon and message to footer

app/controllers/steps_controller.rb, app/steps/medicaid/health_pregnancy.rb, app/views/medicaid/health_pregnancy/edit.html.erb, config/locales/en.yml, spec/factories/member.rb, spec/views/medicaid/health_pregnancy/edit.html.erb_spec.rb
Because the pregnancy question is specific to how many females are among
the members, the question for this should be catered to several
different contexts, or states:
1. Multiple members. One female. That female is you. - "Are YOU pregnant"
2. Multiple members. One female. That female is someone else - "Is SHE pregnant"
3. Multiple members. Several females. "Is ANYONE pregnant"
When there is a single female in the household that's pregnant we should
not show them the page where we ask who. It's a given that if there's
only one female in the house, and someone is pregnant - then she is that
person.
This commit revises the view and the locale to specify how those
questions start and personalizes them accordingly.
A view spec is added as well so we don't exercise the entirety of the …
=> Better prompt when asking about household pregnancy

app/assets/stylesheets/atoms/_variables.scss, app/assets/stylesheets/michigan-benefits/organisms/_step-header.scss, app/models/medicaid_application.rb, app/models/snap_application.rb, app/views/layouts/step.html.erb, db/migrate/20171025184755_add_employed_as_boolean_to_medicaid.rb
* Add "Medicaid" or "Food Assistant Application" to header
* Visual reminder for users coming from `/dual-index` on which application they are completing. 
Note to engineers: The label content will need to change based on the application.
=> Add benefit label label to header

app/controllers/medicaid/insurance_current_controller.rb, app/controllers/medicaid/insurance_current_member_controller.rb, app/controllers/medicaid/insurance_current_type_controller.rb, app/models/medicaid_application.rb, app/models/member.rb, app/steps/medicaid/insurance_current.rb, app/steps/medicaid/insurance_current_member.rb, app/steps/medicaid/insurance_current_type.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/insurance_current/edit.html.erb, app/views/medicaid/insurance_current_member/edit.html.erb, app/views/medicaid/insurance_current_type/edit.html.erb, config/locales/en.yml, db/migrate/20171020215318_move_insurance_info_to_member.rb, db/migrate/20171025233008_rename_anyone_is_insured.rb, db/schema.rb, db/seeds.rb, spec/controllers/medicaid/insurance_current_controller_spec.rb, spec/controllers/medicaid/insurance_current_type_controller_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/steps/medicaid/insurance_current_member_spec.rb, spec/steps/medicaid/insurance_current_type_spec.rb, spec/support/feature_helper.rb
Add a multi-member flow for entering information about additional insurance.
This PR ended up being a big one, and I'd love input! I used a lot of the patterns we used before, but kept the insurance type selection in one controller (rather than splitting for single member and multi member). This might be something to refactor—there's a good amount of view logic and some potentially off language for the single-member flow as a result. But, wanted to get this up for review!
Here are the changes, with expected behavior:
**/steps/medicaid/insurance-current**
Asks whether any household members seeking insurance are currently insured 
If single-member, updates `anyone_is_insured` accordingly on primary member.
If multi-member, continues to page to select who is insured. …
=> Ch multi current insurance

app/controllers/household_add_member_controller.rb, app/controllers/personal_detail_controller.rb, app/models/medicaid_application.rb, app/models/member.rb, app/steps/concerns/social_security_number.rb, app/steps/household_add_member.rb, app/steps/medicaid/contact_social_security.rb, app/steps/personal_detail.rb, app/views/household_add_member/edit.html.erb, app/views/medicaid/contact_social_security/edit.html.erb, app/views/personal_detail/edit.html.erb, db/migrate/20171031224843_add_last_four_ssn_to_member_and_medicaid_application.rb, db/schema.rb, spec/controllers/household_add_member_controller_spec.rb, spec/controllers/personal_detail_controller_spec.rb, spec/factories/member.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/snap_application_with_maximum_info_spec.rb, spec/steps/personal_detail_spec.rb, spec/support/shared_examples/social_security_number.rb
Applies to both Medicaid and SNAP flows.
Keeps SSN as a field on both member and medicaid_application, to be pulled over to last_four_ssn in a future migration.
We have a legacy SSN field on SNAP applications, which we should also migrate away.
[#152420489]
=> Collect only the last 4 digits of someone's SSN

app/controllers/medicaid/insurance_current_type_controller.rb, app/models/member.rb, app/steps/medicaid/insurance_current_type.rb, app/views/medicaid/insurance_current_type/edit.html.erb, config/locales/en.yml, spec/controllers/medicaid/insurance_current_type_controller_spec.rb, spec/factories/member.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/models/member_spec.rb, spec/steps/medicaid/insurance_current_type_spec.rb
We want to loop through each user and ask them what their current insurance
plan is through. To do so we must break out of our current, codified,
patterns. We have to start with *A* member, and move to the next member
after submitting and saving, until we've reached the last user.
To complicate things, we have to be able to go *back* from the next
page/section and allow the client to re-enter adjust the insurance type if
they decide to go back.
To accomplish this we need to create the concept of a _current_member_ and
determine the next and previous members and the accompanying paths.
=> Collect insurance type per client, per page

Gemfile, Gemfile.lock, app/controllers/admin/application_controller.rb, app/models/admin_user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20171102182715_devise_create_admin_users.rb, db/schema.rb, spec/controllers/admin/snap_application_controller_spec.rb, spec/factories/admin_users.rb, spec/features/admin_dashboard_members_spec.rb, spec/features/admin_dashboard_spec.rb, spec/features/admin_user_login_spec.rb, spec/rails_helper.rb
[Finishes #152367741]
**NOTES**:
- chose Devise bc it will be easy to add 2FA later
- did not include "registerable" functionality so all new accounts will
need to be created via Rails console
- attempted to throw a "sign out" link in there but that was proving to
be difficult CSS-wise and was not a requirement in the ticket so I left
it out.
- confirmed that reset password email does work
- we still need the ADMIN_PASSWORD and ADMIN_USER env vars for delayed
job.
=> Add Devise auth for admin dashboard

db/seeds.rb
Seeds were out of date, causing `bin/setup` to fail. This updates them to use our new last_four_ssn field.
=> Update seeds to use last_four_ssn rather than ssn

app/controllers/medicaid/income_other_income_type_controller.rb, app/controllers/medicaid/insurance_current_type_controller.rb, app/controllers/medicaid/member_steps_controller.rb, app/models/member.rb, app/steps/medicaid/income_other_income_type.rb, app/views/medicaid/amounts_income/edit.html.erb, app/views/medicaid/income_other_income_type/edit.html.erb, config/locales/en.yml, db/migrate/20171102231333_move_other_income_types_to_members.rb, db/schema.rb, spec/controllers/medicaid/income_other_income_type_controller_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/steps/medicaid/income_other_income_type_spec.rb
**WHY**:
- before, this was saved on the medicaid app as a series of booleans
- now, we are saving each type as as string in an array field called
"other_income_types" that is on the member.
- extracted some common controller code into an inheritance structure
- part III of https://trello.com/c/tHLD1PgG/441-medicaid-mm-flow-current-income-does-anyone-in-the-household-get-income-thats-not-from-a-job-nested-2
TODO:
- remove / migrate the old boolean fields on medicaid
- refine the "back" logic. Right now, going back from any
member page goes to '/medicaid/income-other-income-member' and going
back from "/medicaid/expenses-alimony" goes to
"/medicaid/income-other-income-type" for the primary member (rather than
going back through the pages in the member order)
=> Select other income types per-member for Medicaid

app/views/medicaid/insurance_current_type/edit.html.erb, spec/features/medicaid_application_with_multiple_members_spec.rb
- Remove "Insurance Plans" to keep subheader patter consistent
=> Remove Insurance Plans sub-header copy

app/models/concerns/submittable.rb, app/models/medicaid_application.rb, app/models/office_recipient.rb, app/models/snap_application.rb, app/views/medicaid/success/edit.html.erb, db/migrate/20171102231334_add_office_location_to_medicaid_applications.rb, db/schema.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/models/office_recipient_spec.rb
* Make it look more like SNAP
* Needed to add `office_location` to MedicaidApplications so we could use office location logic to show the phone number.
Medicaid:
SNAP:
[Finishes #152423848]
=> Update copy / design on Medicaid success page

app/controllers/medicaid/contact_home_address_controller.rb, app/helpers/mb_form_builder.rb, db/migrate/20171107204738_remove_default_value_for_medicaid_applications_mailing_address_same_as_residential.rb, db/schema.rb, spec/controllers/medicaid/contact_home_address_controller_spec.rb, spec/controllers/medicaid/contact_mailing_address_controller_spec.rb, spec/features/medicaid_address_flow_spec.rb
* Was true before, which made it difficult to know if someone had
actually answered that question or not
* This makes our control flow logic easier to parse
=> Set default value for mailing_address_same_as_residential to nil

app/controllers/medicaid/intro_marital_status_controller.rb, app/models/member.rb, app/steps/medicaid/intro_marital_status.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/intro_household/edit.html.erb, app/views/medicaid/intro_marital_status/edit.html.erb, app/views/personal_detail/edit.html.erb, config/locales/en.yml, db/migrate/20171107224111_add_anyone_married_to_medicaid_application.rb, db/migrate/20171108010437_add_married_to_member.rb, db/schema.rb, spec/controllers/medicaid/intro_marital_status_controller_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb
Specifying which members of the family are married and to whom for multi-member household come in the next step.
We've kept married status independent from SNAP's marital status, because they are used and defined differently across the two applications.
[Finishes #152548726]
https://www.pivotaltracker.com/story/show/152548726
=> In Medicaid flow, ask if anyone in household is married.

app/controllers/medicaid/contact_home_address_controller.rb, app/controllers/medicaid/contact_mailing_address_controller.rb, app/controllers/steps_controller.rb, app/models/address.rb, app/models/medicaid_application.rb, app/models/snap_application.rb, app/steps/medicaid/contact_home_address.rb, app/steps/medicaid/contact_mailing_address.rb, app/views/medicaid/contact_home_address/edit.html.erb, app/views/medicaid/contact_mailing_address/edit.html.erb, db/migrate/20171108012317_extract_addresses_from_medicaid_applications.rb, db/schema.rb, spec/controllers/mailing_address_controller_spec.rb, spec/controllers/medicaid/contact_home_address_controller_spec.rb, spec/controllers/medicaid/contact_mailing_address_controller_spec.rb, spec/controllers/residential_address_controller_spec.rb, spec/models/dhs1171_pdf_spec.rb, spec/models/medicaid_application_spec.rb, spec/models/snap_application_attributes_spec.rb, spec/models/snap_application_spec.rb, spec/steps/medicaid/contact_home_address_spec.rb, spec/steps/medicaid/contact_mailing_address_spec.rb
* Make polymorphic relationship between addresses and benefit_application
* Introduce `application_params` to decouple step and application
attributes
[Finishes #152622153]
=> Migrate addresses from MedicaidApplication

app/views/medicaid/amounts_income/edit.html.erb, spec/features/medicaid_application_with_multiple_members_spec.rb
* These styles were added at
https://github.com/codeforamerica/michigan-benefits/pull/433 but some
were lost in a recent merge conflict.
=> Fix subheaders on `/medicaid/steps/amounts-income`

spec/controllers/medicaid/expenses_student_loan_member_controller_spec.rb, spec/controllers/medicaid/health_disability_member_controller_spec.rb, spec/controllers/medicaid/income_job_number_member_controller_spec.rb, spec/controllers/medicaid/income_other_income_member_controller_spec.rb, spec/controllers/medicaid/intro_college_member_controller_spec.rb, spec/controllers/medicaid/intro_marital_status_member_controller_spec.rb
* We had this before but it was not being used everywhere
* The only controllers for `_member` where we cannot use this is
Pregnancy, because that has gender-specific behavior, and Citizen,
because citizen status affects control flow in the opposite way that
other member controllers do (usually "True" for an attribute means you
see the associated member controller but "True" for "Everyone a citizen"
means you do NOT see the citizen member controller)
=> Use shared example group in `_member` controllers

app/controllers/medicaid/intro_marital_status_indicate_spouse_controller.rb, app/controllers/medicaid/member_steps_controller.rb, app/models/medicaid_application.rb, app/models/member.rb, app/models/other_spouse.rb, app/steps/medicaid/intro_marital_status_indicate_spouse.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/intro_marital_status_indicate_spouse/edit.html.erb, config/locales/en.yml, db/migrate/20171108220855_add_spouse_id_to_members.rb, db/schema.rb, spec/controllers/medicaid/intro_marital_status_indicate_spouse_controller_spec.rb, spec/controllers/medicaid/intro_marital_status_member_controller_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/steps/medicaid/intro_marital_status_indicate_spouse_spec.rb
* [Finishes #152550364]
GIVEN I am multi-member Medicaid applicant
WHEN I select which members are currently married
THEN I should go to a NEW page (for each member), where I can select which person they are married to
* Only show members of household who have marked that they were married on previous step.
NOTE: the following was included as part of the feature request:
* If someone has indicated they are married to someone in the same
household, we should assume that person is also married to the original
person and not ask them.
If it is indicated that Person 1 is married to Person 2, I am marking
Person 1 as the spouse of Person 2 as well. *BUT* I am not skipping over
Person 2. The reason for this is that if we go back and update the
spouse of Person 1 to Person 3, we would need to …
=> Select spouses for all married people

app/dashboards/snap_application_dashboard.rb
When viewing a snap application the admin would like to see all (this is
assuming there are no more than 20 members of a household) of the
members in a household.
Previously, the limit was the default of 5 records returned. To get
around having to paginate those members and to view them all in one
page, we can change the default option.
***
References bug: https://sentry.io/app73768247herokucom-6k/app73768247herokucom/issues/402208117/
```
ActionView::Template::Errorapp/views/admin/snap_applications/_collection.html.erb in block in _app_views_admin_snap_applications__collection_html_erb___1318627924288171491_53775620 at line 31
found unpermitted parameter: :members
```
[Finishes #152736200]
=> Show most members in snap application dashboard

app/controllers/admin/medicaid_applications_controller.rb, app/dashboards/medicaid_application_dashboard.rb, app/models/dhs1171_pdf.rb, app/models/dhs1426_pdf.rb, app/models/medicaid_application.rb, app/models/medicaid_application_attributes.rb, app/models/medicaid_application_member_attributes.rb, app/views/admin/medicaid_applications/_collection.html.erb, app/views/admin/medicaid_applications/index.html.erb, config/routes.rb, spec/features/admin_medicaid_applications_dashboard_spec.rb, spec/models/dhs1171_pdf_spec.rb, spec/models/dhs1426_pdf_spec.rb, spec/models/medicaid_application_attributes_spec.rb, spec/models/medicaid_application_member_attributes_spec.rb, spec/support/pdf_helper.rb
Allows admins to download a 1426 PDF application in the admin dashboard.
Only fills out first name and last name of primary member, and signature.
https://www.pivotaltracker.com/story/show/152726754
[Finishes #152726754]
=> Bootstrap filling out 1426 PDF

app/controllers/medicaid/contact_home_address_controller.rb, app/controllers/medicaid/contact_mailing_address_controller.rb, app/controllers/medicaid/expenses_alimony_controller.rb, app/controllers/medicaid/expenses_student_loan_controller.rb, app/controllers/medicaid/health_disability_controller.rb, app/controllers/medicaid/health_pregnancy_controller.rb, app/controllers/medicaid/income_job_controller.rb, app/controllers/medicaid/income_job_number_member_controller.rb, app/controllers/medicaid/income_other_income_controller.rb, app/controllers/medicaid/income_self_employment_controller.rb, app/controllers/medicaid/insurance_current_controller.rb, app/controllers/medicaid/intro_citizen_controller.rb, app/controllers/medicaid/intro_college_controller.rb, app/controllers/medicaid/intro_marital_status_controller.rb, app/controllers/medicaid/intro_marital_status_indicate_spouse_controller.rb, app/controllers/medicaid/many_member_steps_controller.rb, app/controllers/residential_address_controller.rb, app/controllers/steps_controller.rb, app/controllers/success_controller.rb
* Still can update the current application with step params with no
boilerplate
* Add additional behavior to the happy path update with a call to super
* Replace the call entirely without needing a noop update
Signed-off-by: Joel Oliveira <joel.oliveira@gmail.com>
I don't particularly care if we merge this, but I wanted to show an example for a new style of inheritance, one where we can explicitly show which fields go from the step to a specific db model.
This is going to be more important as we move fields out of the application model.
`app/controllers/residential_address_controller.rb` shows a good example of this transformation.
Let's discuss!
@jayroh @jessieay @hartsick @bengolder
=> New pattern for our update inheritance structure

app/views/admin/application/_navigation.html.erb, spec/features/admin_dashboard_spec.rb
Accepting some stories about Admin User authentication was difficult, because we don't have an easy way to sign out. To address this, I added a "Sign Out" link to the admin dashboard that destroys the user session upon clicking.
https://www.pivotaltracker.com/story/show/152826538
[Finishes #152826538]
=> Add 'Sign Out' link for Admin dashboard

config/application.rb, lib/delayed_job_web_logger.rb
Using some rack middleware we can log the actions of whoever is
accessing the DelayedJob web admin.
[Finishes #152762754]
=> Log DelayedJob access

.env.sample, app.json, config.ru, config/routes.rb, spec/features/admin_user_delayed_job_spec.rb
Using devise's built in route helpers we can restrict access to both
delayed job AND the admin. This allows users who visit the admin or DJ
to be forced to log in first, and then be redirected back to their
intended destination.
More information can be found here:
https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
=> Devise route constraints for admin-only DJ access

app/controllers/medicaid/amounts_expenses_controller.rb, app/controllers/medicaid/amounts_overview_controller.rb, app/models/medicaid_application.rb, app/models/member.rb, spec/controllers/medicaid/amounts_overview_controller_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/models/medicaid_application_spec.rb
Conditionally skip expenses in the AmountsExpenses step
Refactored queries used for skip logic into the medicaid_application
@jayroh We decided not to break this out into a SkipHelper, instead we put it on the model, which solved the code duplication problem. Happy to discuss adding a skiphelper if you think it would help what we have here! Both @bengolder and I are happy with this commit but we'll let you approve the merge.
=> Skip amounts conditionally

app/models/medicaid_application.rb, spec/controllers/mailing_address_controller_spec.rb, spec/controllers/medicaid/contact_home_address_controller_spec.rb, spec/controllers/medicaid/contact_mailing_address_controller_spec.rb, spec/controllers/residential_address_controller_spec.rb, spec/factories/address.rb, spec/models/dhs1171_pdf_spec.rb, spec/models/medicaid_application_attributes_spec.rb, spec/models/medicaid_application_spec.rb, spec/models/snap_application_attributes_spec.rb, spec/models/snap_application_spec.rb
* Explanation:
The PDF for the Medicaid application (1426) displays a home address and
a mailing address if that address is different.
Previously, we were not rendering these properly because our application
collects residential address and then mailing only IF they are
different, but our ruby logic returned mailing address and residential
address only IF they are different. This makes sense for how the SNAP
flow works, but resulted in not returning correct data for Medicaid.
To clarify the behavior in tests, we removed the `address` factory so
that only `residential_address` or `mailing_address` factories can be
used.
* [Finishes #152564632]
=> BUGFIX: Show addresses correctly in 1426 PDF

bin/release, bin/setup
https://www.pivotaltracker.com/story/show/152831563
- Edits `bin/release` to show a diff of keys between stage and production.
- Does _not_ show values of env vars
- Uses `jq` CLI to separate out the keys, then bash to diff arrays of keys
- Adds `brew install jq` install to `bin/setup`
- Edits last step of `bin/release` which falsely said it was deploying if you answerered `"N"` to the final question.
=> Update release script to show diff of env var keys

app/assets/stylesheets/atoms/_variables.scss, app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss, app/assets/stylesheets/organisms/_demo-banner.scss
- https://trello.com/c/4bLxAkuJ/125-update-color-pallet-to-pass-accessibility-contract-ratio-tests
=> Update color palette accessible friendly

db/migrate/20171115014535_add_filing_taxes_with_primary_member_to_members.rb
* This migration was accidentally updated incorrectly after it was
migrated but before it was merged. This migration is currently blocking
deploys to staging because it is an invalid migration.
=> Fix migration

.rubocop.yml, Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/models/admin_user.rb, app/views/admin/application/_navigation.html.erb, app/views/devise_otp/tokens/show.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/locales/devise.otp.en.yml, db/migrate/20171114160332_devise_otp_add_to_admin_users.rb, db/schema.rb, spec/features/admin_user_delayed_job_spec.rb, spec/features/admin_user_login_spec.rb
[Finishes #152368004]
Using a fork of the `devise-otp` gem here:
https://github.com/pynixwang/devise-otp
... we are able to integrate with Google Authenticator to add an added
layer of security for admins logging into the app.
After signing in, as usual, and heading to `/admin` you can see `2FA`
link in the left navigation where you can enable it and scan a QR code
with the Google Authenticator app:
* https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8
* https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en
Once enabled, every subsequent sign-in will require that your 2FA code
is provided after the usual email and password step.
=> Allow 2-factor authentication for admins

app/views/medicaid/contact_social_security/edit.html.erb, spec/views/medicaid/contact_social_security/edit.html.erb_spec.rb
[Finishes #152623445]
This commit cleans up the contact SSN page and ensures that an error
displays at all times for instances where a social security number is
not formatted correctly.
=> Display SSN errors consistently

app/assets/stylesheets/atoms/_buttons.scss, app/assets/stylesheets/atoms/_form-elements.scss, app/assets/stylesheets/atoms/_variables.scss
* Add focus styles to allow for clear "keyboard-only" navigation
* https://trello.com/c/tsKFB0F4/126-add-consistent-obvious-focus-pseudo-selector-style-for-all-interactive-elements-buttons-links-inputs-radios-etc
=> Add focus styles

app/controllers/medicaid/tax_claimed_as_dependent_controller.rb, app/controllers/medicaid/tax_filing_with_household_members_relationship_controller.rb, app/models/member.rb, app/steps/medicaid/step_navigation.rb, app/steps/medicaid/tax_filing_with_household_members_relationship.rb, app/views/medicaid/tax_filing_with_household_members_relationship/edit.html.erb, db/migrate/20171115182700_add_tax_relationship_to_member.rb, db/schema.rb, spec/controllers/medicaid/tax_filing_with_household_members_member_controller_spec.rb, spec/controllers/medicaid/tax_filing_with_household_members_relationship_controller_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/steps/medicaid/tax_filing_with_household_members_relationship_spec.rb
Updates primary member's tax relationship (filing status, effectively) to "Single"
if noone in household is filing jointly, and "Joint" if one other member of household
has indicated they are filing jointly.
Also introduces pattern of redefining step members in the controller, so that the controller
is scoped to only consider applicable members (in this case, tax household members).
https://www.pivotaltracker.com/story/show/152561623
[Finishes #152561623]
=> Ask for tax filing status for tax household members

app/controllers/medicaid/intro_citizen_controller.rb, spec/controllers/medicaid/intro_citizen_controller_spec.rb
* We were updating for a single member but not in a multi-member context
* For most questions, if the "anyone_" question is false, we do not want
to update any members because they all have an attribute as FALSE (or
nil). In the case of citizenship, the logic is reversed: when everyone is a
citizen we want to set an attribute ("citizen") to be TRUE.
* This bug became apparent when filling out the 1426 PDF for a
multi-member household where I'd said everyone was a citizen but members
were all being marked as not a citizen because they had a `nil` value in
the database for the `citizen` field
=> Update all members if "everyone a citizen"

app/views/medicaid/income_other_income_type/edit.html.erb, spec/views/medicaid/income_other_income_type/edit.html.erb_spec.rb
[Finishes #152702632]
The `Other Income Type` page was not displaying the validation error. This
commit fixes that.
=> Validate that at least one other income type given

app/controllers/medicaid/health_pregnancy_controller.rb, spec/controllers/medicaid/health_pregnancy_controller_spec.rb
* Usually, we update a single member if the answer to yes/no question is
"yes".
* Pregnancy is an edge case where if there is a multi-member household
but only one member is a female, we can update the `new_mom` attribute
of that single woman after the yes/no question about pregnancy.
* This will fix a bug found via the 1426 form when "new mom" field was
not checked for a dual household with one female. The female was not
marked as a new mom in the database even though the `anyone_new_mom` was
set to true on the Medicaid app.
=> Bug: pregnancy in multi-member household w/single female

app/controllers/medicaid/contact_social_security_controller.rb, app/controllers/medicaid/health_pregnancy_controller.rb, app/controllers/steps_controller.rb, app/controllers/success_controller.rb, app/models/medicaid_application.rb, app/steps/medicaid/contact_social_security.rb, app/steps/medicaid/expenses_alimony.rb, app/steps/medicaid/expenses_student_loan.rb, app/views/medicaid/contact_social_security/edit.html.erb, app/views/medicaid/expenses_alimony/edit.html.erb, app/views/medicaid/expenses_student_loan/edit.html.erb, spec/controllers/medicaid/contact_social_security_controller_spec.rb, spec/controllers/medicaid/health_pregnancy_controller_spec.rb, spec/models/medicaid_application_spec.rb
* Controllers that directly inherit from StepsController now have to
explicitly call super and set it, instead of having it done for you
based on if your attributes include members
* Remove the edit hook in favor of calling `super`
* ManyMembersStepController's children override edit anyways so they
did not need to be changed as part of this commit.
Feedback please!
[#152975776]
=> More explicitly setting members in controllers

app/models/medicaid_application.rb, app/models/snap_application.rb, app/models/verification_document.rb, db/schema.rb, spec/models/verification_document_spec.rb
* We were getting an error on staging related to a `nil` birthday.
Medicaid applicants will not always have a birthday, so we have to check
for birthday before calling `strftime` on it.
* [Finishes #152564700] (again)
* Also removes unused `birthday` field on `medicaid_applications` table
=> Bugfix: PDF with documents

app/views/static_pages/privacy.html.erb
Removes AWS GovCloud reference from our Privacy Policy, since we're not using it!
Also updates the effective date.
Here's what it looks like after the change:
=> Remove AWS GovCloud from Privacy Policy

config/initializers/devise.rb
Fixes a bug where 2FA codes were overwriting each other when on multiple environments (i.e. staging and production).
[Fixes #152983494]
https://www.pivotaltracker.com/story/show/152983494
=> Set OTP issuer name based on Rails environment

app/controllers/medicaid/intro_marital_status_indicate_spouse_controller.rb, app/controllers/medicaid/intro_marital_status_member_controller.rb, app/steps/medicaid/intro_marital_status_indicate_spouse.rb, spec/controllers/medicaid/intro_marital_status_indicate_spouse_controller_spec.rb, spec/controllers/medicaid/intro_marital_status_member_controller_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb
* If we know member1 is married to member2, we previously were asking
this twice. Now we will skip the step and not ask the user.
* We always clear all spouse information to account for scenario where spouse
is selected and the applicant goes back.
[#153069298]
=> [PAIR] Do not ask for spouses if we already know spouse

app/models/medicaid_application_attributes.rb, spec/models/dhs1426_pdf_spec.rb, spec/models/medicaid_application_attributes_spec.rb, spec/support/shared_examples/insurance_type.rb
* if person has Medicare, then we should automatically check "Yes" on the
1426 field, "Do you need help paying Medicare premiums?"
[Finishes #152727191]
https://www.pivotaltracker.com/story/show/152727191
=> Checkbox for medicare premium help

config/initializers/delayed_job.rb
**WHY**:
- we'd been running some failed DriveAttempt jobs over and over again.
- the default number of max runs is 25, default max run time is 4 hours
- these seem like more reasonable defaults. And, which the use of ENV
vars, we can change them without doing a deploy
- reference: https://github.com/collectiveidea/delayed_job#gory-details
- [Finishes #153097654]
https://www.pivotaltracker.com/story/show/153097654
=> Customize config for delayed job

.env.sample, Gemfile, Gemfile.lock, app/controllers/mailing_address_controller.rb, app/controllers/medicaid/contact_home_address_controller.rb, app/controllers/residential_address_controller.rb, app/controllers/steps_controller.rb, app/services/county_finder.rb, app/steps/mailing_address.rb, app/steps/medicaid/contact_home_address.rb, app/steps/medicaid/contact_mailing_address.rb, app/steps/residential_address.rb, config/initializers/geocoder.rb, config/secrets.yml, db/migrate/20171127231016_remove_not_null_constraint_on_address.rb, db/schema.rb, spec/controllers/mailing_address_controller_spec.rb, spec/controllers/medicaid/contact_home_address_controller_spec.rb, spec/controllers/residential_address_controller_spec.rb, spec/factories/address.rb, spec/models/snap_application_attributes_spec.rb, spec/services/county_finder_spec.rb, spec/spec_helper.rb, spec/steps/residential_address_spec.rb
Creates CountyFinder service object that talks to one of two geocoding services that returns county information (opencagedata), then writes that county information to the PDF.
Info on Opencagedata usage [here](https://github.com/alexreisner/geocoder#opencagedata-opencagedata), login info in LastPass
Continues to route application PDFs based on zipcode.
https://www.pivotaltracker.com/story/show/152981944
=> Remove hardcoded county from SNAP and Medicaid application

app/controllers/medicaid/contact_mailing_address_controller.rb, app/controllers/residential_address_controller.rb, app/steps/medicaid/contact_mailing_address.rb, spec/controllers/medicaid/contact_mailing_address_controller_spec.rb, spec/controllers/residential_address_controller_spec.rb
Also fixes a bug where people with residential addresses were being marked as Homeless in the SNAP flow.
[Finishes #152981944]
=> Remove leftover hardcoded county

app/helpers/mb_form_builder.rb, app/views/expenses_additional/edit.html.erb, app/views/household_more_info_per_member/edit.html.erb, app/views/income_additional_sources/edit.html.erb, app/views/income_employment_status/edit.html.erb, app/views/medicaid/contact_text_messages/edit.html.erb, app/views/medicaid/income_other_income_type/edit.html.erb, app/views/residential_address/edit.html.erb, config/locales/en.yml, spec/features/member_not_citizen_spec.rb, spec/rails_helper.rb, spec/support/snap_application_form_helper.rb
* Adds `legend` elements on collections via MbFormBuilder
* Some of these collections do not have `label_text`, so the next step
is to add a hidden `label_text` for those cases so that a screenreader
will have legend text.
* There are still many other fieldsets in the views that do not have
legends.
* [#152761627]
* Part of https://www.pivotaltracker.com/story/show/152761627
Example output HTML for radio collection with a label:
```
<fieldset class="form-group">
<legend class="form-question ">Does your household have ongoing medical expenses?</legend>
<p class="text--help">This includes health insurance, co-pays, prescriptions, dental,
hospital bills, etc.
</p>
<radiogroup class="input-group--block">
<label class="radio-button">
<input type="radio" value="true" name="step[medical]" …
```
=> Improve accessibility of radio and checkbox sets

config/environments/production.rb, config/environments/shared_production.rb, config/environments/staging.rb
This new file is a verbatim copy of production.rb.
This should make it possible to set `RAILS_ENV` and `RACK_ENV` to `staging` for our staging instance. Currently, the staging instance uses `production` for those environment variables.
This will then set the one-time password issuer to "MichiganBenefits.org - staging" for the staging instance.
https://www.pivotaltracker.com/story/show/152983494
=> Add staging.rb

config/database.yml, config/secrets.yml
Needed to set a `RAILS_ENV=staging` on our staging Heroku instance.
=> Declare staging environments

bin/release, bin/release-diff, bin/release_tasks, circle.yml
[Finishes #153272916]
We decided to back out from the pre-prod approach, since we'll have the same issues, i.e. we can't prevent merges while deploying to pre-prod to solve the pain of preventing merge while deploying to prod.
Having a pre-prod branch was introducing a lot of complexity, seen yesterday when noticing a buildpack difference between pre-prod and staging.
Instead, we're removing steps from the release script to make it as quick as we feel responsible at the moment. The goal is to run this script whenever we see a clear acceptance queue in Tracker.
For visibility: @luigi @jessieay @bengolder
=> [PAIR] Remove pre-prod env, speed up deploy instead

app/dashboards/export_dashboard.rb, app/dashboards/member_dashboard.rb, spec/features/admin_dashboard_exports_spec.rb
* From sentry:
```
ActionView::Template::Error: Association named 'snap_application' was not found on Export; perhaps you misspelled it?
Culprit
----------------
app/views/admin/snap_applications/_collection.html.erb in _app_views_admin_snap_applications__collection_html_erb___966721738635953996_62738060 at line 57
```
* This is pre-work for #152982028
=> Fix admin dashboard error on Exports page

app/models/member.rb, spec/models/member_spec.rb
* Previously, a name with a capital letter in the middle would be split
into 2
* Now, we only upcase the first letter of the first and last names and
leave the rest alone.
* [Finishes #153189719]
https://www.pivotaltracker.com/story/show/153189719
Before:
After:
=> Fix last name bug

lib/mi_bridges/driver.rb, lib/mi_bridges/driver/housing_bills_page.rb, lib/mi_bridges/driver/services/submit_relationship.rb, lib/mi_bridges/driver/submit_page.rb, lib/mi_bridges/driver/utility_bills_page.rb, spec/features/mi_bridges_driving_spec.rb
Through the course of exploring our errors, we made some fixes that allowed us to review driven applications more easily. Those fixes are below:
* Update driving tests to complete successfully
* Fix small bug where we were always using 'debug' as log level
* Log 'PageNotFoundError' and 'TooManyAttemptsError' to Driver Errors
* Only catch exceptions for 'run', not 'rerun' with expectation that we do not want to save errors that are redriven because it would be devs doing it manually
* No longer inherit from DebuggerPage on SubmitPage, so driving ends without notice rather than opening a pry
* Don't capitalize member names id in HTML on applications for bills
* MiBridges updated to no longer capitalizing member names on these pages, so we removed our capitalization, as well.
* Updates …
=> SnapApplication webdriving fixes

app/services/update_member_data.rb, lib/mi_bridges/driver/people_listed_page.rb, lib/tasks/one_offs.rake, spec/factories/member.rb, spec/features/mi_bridges_driving_spec.rb, spec/models/dhs1171_pdf_spec.rb, spec/services/update_member_data_spec.rb
Add one-off task to update member data 
* This is to fix driving problems that occur when names have trailing or
leading whitespace *or* nil value for `other_income_types` *or* messed
up SSN.
* [#153377419]
* [#152982028]
Update driving code to have default marital status
* Right now, in SNAP flow only the primary member reports their marital
status but this is a required field for ALL members in MiBridges
* Product/design work required to figure out how to fix this long term,
but for now we are filling in `Never Married` as a default value.
* [#153382734]
=> Add one-off task to update member data, Update driving code to have default marital status

app/services/employments_migrator.rb, spec/services/employments_migrator_spec.rb
=> Do not use employed_number_of_jobs in migrator

app/controllers/medicaid/contact_social_security_controller.rb, app/controllers/medicaid/health_pregnancy_member_controller.rb, app/controllers/medicaid/insurance_current_member_controller.rb, app/controllers/medicaid/many_member_steps_controller.rb, app/controllers/medicaid/tax_filing_with_household_members_member_controller.rb, app/steps/medicaid/health_pregnancy_member.rb, app/steps/medicaid/insurance_current_member.rb, app/steps/medicaid/insurance_needed.rb, app/steps/medicaid/intro_college_member.rb, app/steps/medicaid/intro_marital_status_member.rb, app/views/medicaid/health_pregnancy_member/edit.html.erb, app/views/medicaid/insurance_current_member/edit.html.erb, app/views/medicaid/tax_filing_with_household_members_member/edit.html.erb, spec/controllers/medicaid/health_pregnancy_member_controller_spec.rb, spec/controllers/medicaid/insurance_current_member_controller_spec.rb, spec/controllers/medicaid/tax_filing_with_household_members_member_controller_spec.rb, spec/steps/medicaid/insurance_current_member_spec.rb
* Previously, `ManyMembersStepsController` had to check if attributes
were present, because there were times where only specific members
populate a form, but when assigning attributes, it uses all members in
application
* No steps using `ManyMembersStepsController` have fields in the
application, just on members, so no need to merge attributes
* Remove some unused attributes from steps
[#153526809]
=> [PAIR] Specify members to populate many members steps

app/controllers/medicaid/income_job_number_controller.rb, spec/controllers/medicaid/income_job_number_controller_spec.rb, spec/controllers/medicaid/insurance_current_member_controller_spec.rb
* More explicit override of edit
* Add test for nil case for employed_number_of_jobs
[#153069646]
=> [PAIR] Small refactors to income job number controller

lib/mi_bridges/driver.rb
When we moved exception handling a level higher, we lost the ability for a drive to pick up where the exception was raised. This resets it to the original behavior and adds backtrace logging. It does not handle properly catching and logging problems with logging errors when we hit TooManyAttempts error(?), which moving exception handling up was meant to solve, so will still need to handle that elsewhere.
[#152982028]
=> Reset exception handling within page loop

lib/mi_bridges/driver/more_about_job_income_page.rb
* Hourly is not an option in MiBridges, but it is in our SNAP flow
* Pay interval is a required question for employed members in MiBridges,
so whenever they've reported it to us as Hourly, the flow fails on this
page
* This issue presents a larger product question, but for now the way we
can move past it and continue to drive apps where there is an employed
household member is to select "Other" in this case.
* Tagging the product / design story in here so we can un-do this
default select when we have more clarity on the longer term fix.
* [#153378349]
* I confirmed that this works with the SNAP id referenced in the story
=> Fill in "Other" as pay interval when "Hourly"

app/models/member.rb, spec/controllers/introduce_yourself_controller_spec.rb
* This is important for driving code because in MiBridges we depend on
first name to know which household member we are answering questions
about
* Could have used a gem instead, but this seemed like the simplest solution. See: https://stackoverflow.com/questions/3268053/rails-before-validation-strip-whitespace-best-practices
* [Finishes #153377419]
https://www.pivotaltracker.com/story/show/153377419
=> Strip first name and last name leading/trailing whitespace

lib/mi_bridges/driver.rb, lib/mi_bridges/driver/submit_page.rb, spec/spec_helper.rb
* We used to run it as part of a pre-deploy test so this ENV var made
sense then, but we no longer do that.
=> Rename ENV var that enables MiBridges spec to run

lib/mi_bridges/driver.rb, lib/mi_bridges/driver/dependent_care_page.rb, lib/mi_bridges/driver/your_other_bills_expenses_page.rb, spec/features/mi_bridges_driving_spec.rb
* We were previously saying that "No one" had dependent care expenses;
now we are adding them when present and indicating the amount on the
follow up page.
* [Finishes #153570213]
* Confirmed that this works by adding `dependent_care: true` to the Snap
App in the MIBridges spec and running it - it passes.
https://www.pivotaltracker.com/story/show/153570213
=> MiBridges: Add Dependent care expenses and details

app/dashboards/driver_error_dashboard.rb, app/models/driver_error.rb, db/migrate/20171212193613_add_page_history_to_driver_applications.rb, db/schema.rb, lib/mi_bridges/driver.rb, lib/mi_bridges/driver/base_page.rb, lib/mi_bridges/driver/create_account_page.rb, lib/mi_bridges/driver/services/driver_application_factory.rb, spec/features/admin_dashboard_driver_errors_spec.rb, spec/lib/mi_bridges/driver/pages_spec.rb
* Move driver application creation to earlier in the driving sequence so
we can save the pages visited each time we instantiate a driver page
* Now we can capture errors that occur before or during sign up
* Show Page History for each driver error in admin dashboard
* [Finishes #153521242]
https://www.pivotaltracker.com/story/show/153521242
=> [PAIR] Add Page History to DriverApplication

app/assets/javascripts/upload_setup.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/michigan-benefits/organisms/_document-preview.scss, app/views/shared/_uploadable.html.erb, app/views/shared/_uploadable_uploading.html.erb
* When uploading, only show "Uploading..." (not file name or delete
link)
* When uploaded, show green success checkmark on left of file name and
append delete link.
* [Finishes #152982006]
=> Update uploadable styles

lib/summarizer/application_summary.rb, lib/tasks/slack.rake, spec/lib/summarizer/application_summary_spec.rb
Before we were calculating the day using UTC time. Now our task bases its understanding (and report) of daily stats based on the start and end of day in Detroit (Eastern Standard Time).
=> Compute the daily summary for day *in Detroit*

app/controllers/medicaid/intro_location_controller.rb, app/views/medicaid/welcome/edit.html.erb, db/migrate/20171214235857_remove_michigan_resident_null_constraint.rb, db/schema.rb, spec/controllers/medicaid/intro_location_controller_spec.rb
- On `intro-location`, update `office_location` from get params
- Forward `office_location` param from `welcome` to `intro-location` in link
Implemented for testing medicaid app in specific field offices. Field offices can visit `/steps/medicaid/welcome?office_location=union` and have the stated office be recorded in their application (and routed appropriately).
Can be rolled back—and should be!
=> [PAIR] Quick way to specify office location for Medicaid apps

app/controllers/medicaid/intro_location_controller.rb, spec/controllers/medicaid/intro_location_controller_spec.rb
Previously if someone started an application and clicked back, if they hit the intro-location page we would overwrite the office_location to be empty. This fixes that behavior by only updating office_location if there is an office_location param.
(We thought we had included this in the previous PR, but accidentally left out!)
=> Don't overwrite office location if no params present

app/assets/stylesheets/michigan-benefits/atoms/_form-elements.scss, app/helpers/mb_form_builder.rb, app/views/income_change_explanation/edit.html.erb, app/views/medicaid/amounts_income/edit.html.erb, app/views/medicaid/contact_social_security/edit.html.erb, app/views/medicaid/income_job_number_member/edit.html.erb, app/views/personal_detail/edit.html.erb, config/locales/en.yml, spec/helpers/mb_form_builder_spec.rb
* These labels are in the page header so they are visible to people
looking at a browser but will not be read by a screen reader.
* [#153646862]
=> Add `sr-only` labels for inputs without labels

app/steps/authorized_representative.rb, app/views/authorized_representative/edit.html.erb, spec/controllers/authorized_representative_controller_spec.rb, spec/features/snap_application_with_maximum_info_spec.rb, spec/features/snap_application_with_minimal_info_spec.rb, spec/steps/authorized_representative_spec.rb
* Before, somehow could skip this question
* There was a related bug where if they answered "no" it would require
the auth rep name because "false" was being evaluated to a present value
in the step validation.
* Now, the bug is fixed and we have slightly different behavior too.
* [Finishes #153690105]
=> Require answer to authorized representative question

app/helpers/mb_form_builder.rb
* This cleans up the syntax highlighting on the page
* Consistently use squiggly heredocs since we do not care about
preserving whitespace
Here is the difference btwn the 2, as an example:
```
output = <<~END
This is
a string
END
=> "This is\na string\n"
second_output = <<-END
This is
a string
END
=> "  This is\n  a string\n"
```
=> Small tweaks to MbFormHelpers

app/helpers/mb_form_builder.rb, app/views/authorized_representative/edit.html.erb, app/views/contact_preference/edit.html.erb, app/views/expenses_additional_sources/edit.html.erb, app/views/household_add_member/edit.html.erb, app/views/household_more_info/edit.html.erb, app/views/income_additional_sources/edit.html.erb, app/views/income_change/edit.html.erb, app/views/income_employment_status/edit.html.erb, app/views/income_other_assets/edit.html.erb, app/views/introduction_change_office_location/edit.html.erb, app/views/legal_agreement/edit.html.erb, app/views/mailing_address/edit.html.erb, app/views/medicaid/contact_home_address/edit.html.erb, app/views/medicaid/income_job_number/edit.html.erb, app/views/medicaid/income_job_number_continued/edit.html.erb, app/views/medicaid/income_other_income_type/edit.html.erb, app/views/medicaid/insurance_current_type/edit.html.erb, app/views/medicaid/intro_household_member/edit.html.erb, app/views/medicaid/intro_marital_status_indicate_spouse/edit.html.erb, app/views/medicaid/intro_name/edit.html.erb, app/views/medicaid/legal_agreement/edit.html.erb, app/views/personal_detail/edit.html.erb, app/views/residential_address/edit.html.erb, config/locales/en.yml, spec/helpers/mb_form_builder_spec.rb
* We are not requiring a label for all radio and checkbox sets by having
`label_text` as a required argument for each.
* Using named (as opposed to positional) arguments is easier to read
anyway
* If we want label text that is only visible to a screenreader, we can
pass `sr-only` as the `legend_class` argument.
=> Require label text for all radio and checkbox sets

app/views/static_pages/clio.html.erb, app/views/static_pages/union.html.erb
* The `=` was missing from the ERB tag.
[Resolves #153688176]
=> [PAIR] Fixes blank space on office landing pages.

app/assets/stylesheets/application.scss, app/assets/stylesheets/michigan-benefits/atoms/_buttons.scss, app/assets/stylesheets/michigan-benefits/atoms/_typography.scss, app/assets/stylesheets/michigan-benefits/atoms/_variables.scss, app/assets/stylesheets/michigan-benefits/organisms/_document-preview.scss, app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss
Before:
After:
Before:
After:
Before:
After:
Before:
After:
https://www.pivotaltracker.com/story/show/153647011
=> [PAIR] Improves contrast and text sizing for a11y

app/helpers/mb_form_builder.rb, spec/helpers/mb_form_builder_spec.rb
This is an alternative approach to #597. Instead of monkeypatching Rails, it:
* Drops `date_select` in favor of `select_month`,
`select_day`, `select_year`
* Adds some helper methods to format `id=` and `name=`
It adds the same test as #597.
https://www.pivotaltracker.com/story/show/153646862
=> Add a <label> to each component in a date select

Rakefile, lib/tasks/mi_bridges.rake, spec/features/mi_bridges_driving_spec.rb
* rake mi_bridges:run
* [Finishes #153489246]
https://www.pivotaltracker.com/story/show/153489246
=> Add rake task for running MIBridges spec

app/lib/mi_bridges/driver/relationship_information_page.rb
* For every member, there is a page that asks how that member relates to
the rest of the members. This is the `RelationshipInformationPage`.
* By the time we get to the last member, we know how that member relates
to all of the other members so we do not need to ask any relationship
questions.
* BUT, if that member is a child, MIBridges asks an optional question,
which is "Who acts as a parent for CHILDNAME?"
* When this page is presented, we get an error for
`RelationshipInformationPage`, which always tries to find a dropdown for
identifying relationships.
* We know we are on this edgecase version of the page when it has the
header "More About Childre", so when that is present we will skip the
dropdown logic.
* Was tested / confirmed using the SNAP app id from prod listed in the
tracker …
=> MiBridges: fix relationship bug for households w/ 3+ members & children

app/assets/stylesheets/michigan-benefits/atoms/_variables.scss
**WHY**: Since these vars are defined based on `color-sky`, we need to
re-define them after we have re-defined `color-sky` in our overrides
file.
new button / header stylez:
=> Override all variables related to `color-sky`

app/lib/mi_bridges/driver/absent_parent_information_page.rb
* If both parents are not in the household, MIBridges asks which
children have a common absent parent
* We are selecting "No one" in all cases. This info can be corrected
during an interview.
* Also had to override `skip_infinite_loop_check` since this page shows
up TWICE for each child, which would trigger an infinite loop check if
there are more than 2 children in a household with an absent parent.
* This was confirmed by driving the SNAP app with id mentioned in the
tracker ticket.
* [Finishes #153388256]
https://www.pivotaltracker.com/story/show/153388256
This is what the page looks like (names redacted):
=> Check "no one" for common absent parent question

app/helpers/mb_form_builder.rb, spec/helpers/mb_form_builder_spec.rb
* Was causing an axe-matchers error due to label for= not matching
id= of select element.
https://www.pivotaltracker.com/story/show/153764112
=> Use correct label for= values on nested date selects

app/lib/mi_bridges/driver/privacy_pin_page.rb, app/lib/mi_bridges/driver/submit_page.rb
* The final step was calling `close`, so when the teardown method in
`Driver.rb` tried to close the browser, it got an error because the
driver had already been closed
* This also fixed another bug that popped up recently where the Privacy
PIN  page option was not being selected properly. The error showed up as
`Selenium::WebDriver $ is not defined`. Fixed by calling `find` on the
element so that it is loaded (Capybara waits for it) before clicking on
the id.
* [Finishes #153571372]
=> Fixes "MiBridges: Closing the driver causes an error"

app/lib/mi_bridges/driver.rb, app/lib/mi_bridges/driver/absent_parent_details_summary_page.rb, app/lib/mi_bridges/driver/absent_parent_summary_page.rb, app/lib/mi_bridges/driver/basic_information_summary_page.rb, app/lib/mi_bridges/driver/household_members_summary_page.rb, app/lib/mi_bridges/driver/housing_utility_bills_summary_page.rb, app/lib/mi_bridges/driver/job_income_summary_page.rb, app/lib/mi_bridges/driver/liquid_assets_summary_page.rb, app/lib/mi_bridges/driver/other_assets_summary_page.rb, app/lib/mi_bridges/driver/other_income_summary_page.rb, app/lib/mi_bridges/driver/other_information_summary_page.rb, app/lib/mi_bridges/driver/summary_page.rb, app/lib/mi_bridges/driver/your_other_bills_expenses_summary_page.rb
* Rather than having a separate page for each, we can match on the regex
of "Summary" to determine if we are on a summary page
* All summary pages are ClickNext (no other info added)
=> Use same "page" object for all MiBridges summary pages

app/jobs/medicaid/office_email_application_job.rb, app/jobs/office_email_application_job.rb, app/mailers/application_mailer.rb, spec/jobs/medicaid/office_email_application_job_spec.rb, spec/jobs/office_email_application_job_spec.rb, spec/mailers/application_mailer_spec.rb
* [Finishes #153763281]
* This brings up one thing that is inconsistent between the mailers,
which is that we show a different subject for 1171 if the applicant is
in the office but the subject is always the same for the 1426.
=> Add applicant names to office email subject lines

app/mailers/application_mailer.rb, spec/mailers/application_mailer_spec.rb
* Previously, were using generic names
* This way, case workers can more easily identify which files are for
which applicants
* [Finishes #153763110]
=> Add current date and applicant name to attachment filename

app/assets/stylesheets/organisms/_demo-banner.scss, app/views/layouts/application.html.erb, spec/features/staging_warning_spec.rb
* Inserts `<div>` in main application layout when
Rails.env.staging? is true
[Resolves #153885053]
=> [PAIR] Adds warning message to all pages on staging

app/dashboards/snap_application_dashboard.rb, app/models/snap_application.rb, spec/features/admin_dashboard_snap_applications_spec.rb, spec/models/snap_application_spec.rb
Fixes broken stat in admin dashboard that is super useful for debugging.
[Fixes #154000383]
Going to auto-merge since small change, and should only impact the admin dashboard.
=> Add 'Last emailed office at' to admin dashboard for SNAP

app/dashboards/export_dashboard.rb, config/initializers/delayed_job.rb
When a delayed job failed, a problem with our configuration (storing the number of max attempts as a string) was causing the worker to crash when it tried to reschedule. As a result, the job never got its number of attempts updated and unlocked, so a failed job would continue on forever, blocking any new delayed jobs that got queued. See this ticket for a symptom: https://www.pivotaltracker.com/story/show/153996535.
This PR does two things:
* Converts our configuration to an integer, which is what delayed job expects. This prevents the worker from crashing when it tries to rescheudle a failed job.
* Prevents delayed job from deleting failed jobs (the default). This will allow us to see what jobs are regularly failing in the future—otherwise, they just disappear into the ether. Here's a …
=> Convert max attempts for delayed jobs to integer

app/views/income_other_assets_continued/edit.html.erb
[Finishes #154011478]
Added a missing tag to close div. fixes ui issue.
=> [PAIR] closed div

app/helpers/mb_form_builder.rb, spec/helpers/mb_form_builder_spec.rb
- No ids or aria labelling added for errors on checkbox sets
- No ids or aria labelling added for standalone checkboxes
[#152814700]
=> Add aria labels for checkbox sets

app/helpers/time_zone_helper.rb, app/mailers/application_mailer.rb, app/views/fields/date_time/_index.html.erb, spec/helpers/formatting_helper_spec.rb
Previously we were using Date.today.in_timezone to convert the dates for email attachments to Eastern Standard Time. Because of Rails timezones being confusing, this didn't actually produce today's date in EST.
Instead, we have to use DateTime.now (which holds timezone info, unlike Date.today). Since this isn't straightforward and we do it in another place, I extracted it into a helper.
[Fixes #154011675]
=> Use current date in EST for email attachment names

config/initializers/lograge.rb
Use lograge's custom payload to insert the `current_admin_user`'s email address into each log line.
This fixes a bug where the email address was not being saved for log lines on controller requests:
https://www.pivotaltracker.com/story/show/153882480
As documented on [Stack Overflow](https://stackoverflow.com/questions/11124821/rails-tagged-logging#comment64603906_13371397), the [previous approach](https://github.com/codeforamerica/michigan-benefits/commit/d5a8bfc910a3984c1030326b56ab713edbc2b7e4) used does not work for controller request log lines. The technique does work for logs on ActiveRecord activity, but those aren't logged in staging/production.
=> Log email address of admin user

lib/delayed_job_web_logger.rb
* Log user email
* Don’t log requests for assets
* Don’t log requests for the polling endpoint
https://www.pivotaltracker.com/story/show/154155900
The [original PR](https://github.com/codeforamerica/michigan-benefits/pull/459) added the user email to existing log lines, but those were only generated for ActiveRecord activity, not web requests. This PR explicitly logs web requests.
=> Log all web requests from delayed_job_web

app/helpers/mb_form_builder.rb, spec/helpers/mb_form_builder_spec.rb
* Created method called aria_labelledby
* Moved __label id to the question instead of <label>
* Sanitize ids for situations with objects that have brackets
[#152814700]
=> [PAIR] Adds aria-labelledby support for mb_textarea + mb_select.

app/helpers/mb_form_builder.rb, app/views/household_more_info_per_member/_member_checkboxes.html.erb, app/views/household_more_info_per_member/edit.html.erb, app/views/medicaid/contact_home_address/edit.html.erb, app/views/medicaid/expenses_alimony_member/edit.html.erb, app/views/medicaid/expenses_student_loan_member/edit.html.erb, app/views/medicaid/health_disability_member/edit.html.erb, app/views/medicaid/health_pregnancy_member/edit.html.erb, app/views/medicaid/income_other_income_member/edit.html.erb, app/views/medicaid/income_self_employment_member/edit.html.erb, app/views/medicaid/insurance_current_member/edit.html.erb, app/views/medicaid/insurance_needed/edit.html.erb, app/views/medicaid/intro_caretaker_member/edit.html.erb, app/views/medicaid/intro_citizen_member/edit.html.erb, app/views/medicaid/intro_college_member/edit.html.erb, app/views/medicaid/intro_marital_status_member/edit.html.erb, app/views/medicaid/tax_filing_with_household_members_member/edit.html.erb, spec/helpers/mb_form_builder_spec.rb
* Adds `legend_id` option for use by aria-labelledby.
* Converts `options` to named argument.
* No support for help text, since we don't use it.
[Finishes #152814700]
=> Add aria-labelledby to standalone checkboxes.

Gemfile, Gemfile.lock, Rakefile, circle.yml, config/brakeman.ignore
This adds brakeman to the Circle CI tasks, as a `post` after bundler-audit is run and before the tests are run.
https://www.pivotaltracker.com/story/show/154097597
[#154097597]
=> Add brakeman to Circle CI after bundle-audit

app/lib/pdf_builder.rb, app/models/dhs1171_pdf.rb, app/models/dhs1426_pdf.rb, app/models/remote_document.rb, app/models/snap_application_extra_member_pdf.rb, spec/features/admin_dashboard_medicaid_applications_spec.rb, spec/features/snap_application_with_maximum_info_spec.rb, spec/lib/pdf_builder_spec.rb, spec/models/dhs1171_pdf_spec.rb, spec/models/dhs1426_pdf_spec.rb, spec/models/verification_document_spec.rb, spec/rails_helper.rb, spec/support/pdf_helper.rb
So, I was trying to write a simple integration test that would reproduce what we're seeing locally (application PDF generation failing if there are 2 or more documents uploaded). This *didn't* do that, but seemed like it could still be useful, so wanted to push up.
This does a few things:
* Forces Delayed Jobs to complete in tests. They were hanging around before
* Stubs out requests to example.com/images for our feature specs (done only when we generate a PDF, needed because we're executing delayed jobs in specs)
* Clears out ActionMailer::Base.deliveries (needed because we're executing delayed jobs in specs, and testing the number of deliveries made on a request)
I'd be interested in discussing how we want to treat PDFs in these integration tests. Right now I just tested enough to …
=> Add basic integration test for SNAP flow that checks for PDF attachment

app/models/medicaid_application.rb, lib/summarizer/application_summary.rb, spec/factories/medicaid_applications.rb, spec/factories/snap_applications.rb, spec/lib/summarizer/application_summary_spec.rb, spec/models/medicaid_application_spec.rb
Previously for our Slack daily summary, we just included any applications that had been initiated during the day. This scopes that reporting to only *signed* applications.
=> Only report on signed applications during daily summary

app/controllers/skip_send_applications_controller.rb, app/controllers/snap_steps_controller.rb, spec/controllers/skip_send_applications_controller_spec.rb, spec/controllers/success_controller_spec.rb
Previously, if a user submitted a SNAP application and clicked 'back' after hitting the homepage, they would receive an error if they clicked on 'skip this step'. This commit addresses that by redirecting the user if there isn't a current application when they click 'skip this step', and adds a helpful flash message to let them know they've been redirected to the start of the application.
[Finishes #154097480]
https://www.pivotaltracker.com/story/show/154097480
=> Redirect user after `/success` if they try to access page without app

Gemfile, Gemfile.lock, Rakefile
Recently we began requiring rubocop's rake task when loading the Rakefile (without calling a specific rake task). Because we only required rubocop in test and development environments, using any Rake task in production or staging would break. We saw this on Circle CI when doing staging deploys.
To fix, we now only require 'rubocop/rake_task' when our own `lint:autocorrect` is called. Because rubcop doesn't give a clear way to do this and also call its autocorrect sub-Rake task, we manually call it with `Rake::Task["rubocop:auto_correct"].execute`.
=> Namespace rubocop in Rakefile

app/models/dhs1171_pdf.rb, app/models/dhs1426_pdf.rb, app/models/snap_application.rb, app/models/verification_document.rb, app/pdf_components/assistance_application_form.rb, app/pdf_components/coversheet.rb, app/services/application_pdf_assembler.rb, app/services/pdf_concatenator.rb, spec/models/dhs1171_pdf_spec.rb, spec/models/dhs1426_pdf_spec.rb, spec/models/snap_application_spec.rb, spec/models/verification_document_spec.rb, spec/pdf_components/assistance_application_form_spec.rb, spec/pdf_components/coversheet_spec.rb, spec/services/application_pdf_assembler_spec.rb, spec/services/pdf_concatenator_spec.rb, spec/support/shared_examples/pdf_component.rb
For SNAP applications, if `NEW_FORM_ENABLED` is `true`, we build a barely-filled AssistanceApplicationForm with attached coversheet and verification documents. This will be included in office or applicant emails and downloadable in the admin.
Anything being assembled by the `ApplicationPdfAssembler` should implement a "pdf component" interface (described in a `spec/support/shared_examples/pdf_component`). `PdfConcatenator` will call the `.fill?` method to determine if the component needs to be filled, and will call `.output_file` to retrieve the file object associated with the component.
We updated some existing objects to implement the pdf component interface (`.fill?` and `.output_file`)
[Finishes #154566400]
=> Send blank PDF for SNAP apps if feature flag enabled.

Rakefile, app/assets/stylesheets/molecules/_form-molecules.scss, app/assets/stylesheets/organisms/_form-card.scss, app/controllers/medicaid/contact_social_security_controller.rb, app/controllers/medicaid/contact_ss_dob_controller.rb, app/controllers/medicaid/contact_ss_intro_controller.rb, app/controllers/medicaid/intro_household_member_controller.rb, app/models/member.rb, app/steps/medicaid/contact_ss_intro.rb, app/steps/medicaid/intro_household_member.rb, app/steps/medicaid/intro_name.rb, app/steps/medicaid/step_navigation.rb, app/views/medicaid/contact_social_security/edit.html.erb, app/views/medicaid/contact_ss_intro/edit.html.erb, app/views/medicaid/intro_household_member/edit.html.erb, app/views/medicaid/intro_name/edit.html.erb, config/locales/en.yml, spec/controllers/medicaid/contact_social_security_controller_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/models/employed_member_attributes_spec.rb, spec/models/extra_member_attributes_spec.rb, spec/models/medicaid_application_member_attributes_spec.rb, spec/models/member_spec.rb, spec/models/self_employed_member_attributes_spec.rb, spec/models/snap_application_member_attributes_spec.rb, spec/support/medicaid_application_form_helper.rb
When household has members with same name, use DOB to differentiate  …
* Moves birthday collection to when we register each member (rather than with SSN in Medicaid flow)
* Memoize display name generation on member to reduce database calls
* Fixes styling small styling bug releated to fieldset vs div and pseudoselectors
[#153798110]
=> Differentiate member name

app/controllers/stats/numbers_controller.rb, app/views/stats/numbers/index.html.erb, config/routes.rb, config/secrets.yml, spec/features/numbers_dashboard_spec.rb, spec/support/feature_helper.rb
We built our own dashboard (older GCF-style) after talking a bit with Lou. This solution was quicker and easier (and cheaper!) than Geckoboard since currently all of our data is located inside our application.
User + password info in LastPass. Used same info for staging + production since it's non-sensitive data.
=>  Add `/numbers` dashboard with MichiganBenefits stats

app/controllers/household_more_info_controller.rb, app/controllers/household_more_info_per_member_controller.rb, app/controllers/medicaid_steps_controller.rb, app/controllers/stats/numbers_controller.rb, app/controllers/steps_controller.rb, app/views/household_more_info_per_member/edit.html.erb, spec/controllers/household_more_info_controller_spec.rb, spec/controllers/household_more_info_per_member_controller_spec.rb, spec/controllers/medicaid/intro_citizen_controller_spec.rb, spec/support/feature_helper.rb
Previously in this step on the SNAP flow, when the client selected "everyone is a citizen", we only marked that on the application and didn't update individual members. As a result, when we fill in the PDF, the members were never marked as citizens on the PDF, because we only fill it out based on the member.
This PR fixes that by updating members-> citizen to true when 'everyone_a_citizen' is selected.
This PR also addresses the negative of that problem on the same step, which happens when someone marks 'anyone_blank' as false. Right now we aren't updating the members (as a result, the value for that field is nil). This PR marks those fields as false instead.
Lastly, we now update 'everyone_a_citizen' and similar fields to their proper values based on actual reported members (for example, …
=> Correct incorrect citizen reporting

app/models/concerns/common_benefit_application.rb, spec/support/shared_examples/common_benefit_application.rb
* On Medicaid applications, stable_housing might be nil.
* Rewrite stable_housing? to be true when it’s nil.
* Correct unstable_housing? to return false only on boolean false.
[#154776068]
=> Avoid marking applications as homeless when stable_housing is nil.

app/models/snap_application_attributes.rb, spec/models/snap_application_attributes_spec.rb
* Users are naturally entering $0 for rent/mortgage, property tax, and insurance
* On the 1171 PDF, we should not check those boxes nor fill in those fields when $0 is entered
[#154774358]
=> Don’t fill in shelter expenses when user enters $0

app/views/household_members_overview/edit.html.erb, app/views/medicaid/intro_household/edit.html.erb, app/views/medicaid/tax_filing/edit.html.erb, app/views/medicaid/tax_filing_with_household_members/edit.html.erb, app/views/medicaid/tax_filing_with_household_members_relationship/edit.html.erb, app/views/medicaid/tax_overview/edit.html.erb, app/views/shared/_live_chat.html.erb
- Relies on a `LIVE_CHAT_ENABLED` feature flag
- Uses a shared erb snippet
[Finishes #154901171]
=> Add Olark live chat to some views

app/assets/javascripts/application.js, app/controllers/introduction_applied_before_controller.rb, app/controllers/medicaid/intro_applied_before_controller.rb, app/dashboards/medicaid_application_dashboard.rb, app/dashboards/snap_application_dashboard.rb, app/models/medicaid_application.rb, app/models/snap_application.rb, app/steps/introduction_applied_before.rb, app/steps/medicaid/intro_applied_before.rb, app/steps/medicaid/step_navigation.rb, app/steps/step_navigation.rb, app/views/introduction_applied_before/edit.html.erb, app/views/medicaid/intro_applied_before/edit.html.erb, app/views/shared/_yes_no_enum_form.html.erb, db/migrate/20180207201225_add_applied_before.rb, db/migrate/20180207230234_backfill_applied_before.rb, db/schema.rb, spec/controllers/personal_detail_controller_spec.rb, spec/features/medicaid_application_with_maximum_info_spec.rb, spec/features/medicaid_application_with_minimal_info_spec.rb, spec/features/medicaid_application_with_multiple_members_spec.rb, spec/features/snap_application_with_maximum_info_spec.rb, spec/features/snap_application_with_minimal_info_spec.rb, spec/models/snap_application_spec.rb
- Use enum for unfilled/yes/no.
- Used backfill recommendation via Strong Migrations
https://github.com/ankane/strong_migrations#adding-a-column-with-a-default-value
- Updated yes/no JavaScript to support the enum "yes"/"no" values
[Finishes #154901167]
=> Ask if user has applied before

app/dashboards/driver_error_dashboard.rb, app/dashboards/medicaid_application_dashboard.rb, app/dashboards/member_dashboard.rb, app/dashboards/snap_application_dashboard.rb, spec/features/admin_dashboard_driver_errors_spec.rb, spec/features/admin_dashboard_exports_spec.rb, spec/features/admin_dashboard_medicaid_applications_spec.rb, spec/features/admin_dashboard_members_spec.rb, spec/features/admin_dashboard_snap_applications_spec.rb
* Remove display_name from admin dashboard
Administrate was choking on 'display_name' on search on staging and production (not locally). We disable search, but decided to just use first name and last name in the dashboard instead.
* Add tests for Administrate search and fix other broken fields
Administrate search is easily and sneakily broken if certain fields incompatible with search aren't excluded. To fix this, I added a few simple sanity tests and corrected the offenders.
This should fix search on all the dashboards.
=> Fix members dashboard (and others! and add tests!)

app/controllers/forms_controller.rb, app/controllers/integrated/before_you_start_controller.rb, app/controllers/integrated/benefits_intro_controller.rb, app/controllers/integrated/introduce_yourself_controller.rb, app/forms/form_navigation.rb, app/views/forms/index.html.erb, app/views/integrated/before_you_start/edit.html.erb, spec/controllers/forms_controller_inheritance_spec.rb, spec/controllers/forms_controller_spec.rb, spec/controllers/integrated/before_you_start_controller_spec.rb, spec/controllers/integrated/introduce_yourself_controller_spec.rb, spec/features/integrated_application_navigation_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb
- Added small feature spec for form navigation page.
- Added default redirection if current_application is not present in
session. Skip redirection on first two form controllers.
[Finishes #155523865]
=> Add BeforeYouStart page that clears current_app

app/controllers/forms_controller.rb, app/controllers/integrated/application_submitted_controller.rb, app/forms/form_navigation.rb, app/jobs/integrated/office_email_application_job.rb, app/mailers/application_mailer.rb, app/models/common_application.rb, app/models/integrated/export_factory.rb, app/views/application_mailer/office_integrated_application_notification.html.erb, app/views/application_mailer/office_medicaid_application_notification.html.erb, app/views/integrated/application_submitted/edit.html.erb, spec/controllers/integrated/application_submitted_controller_spec.rb, spec/factories/exports.rb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/features/snap_application_with_maximum_info_spec.rb, spec/jobs/integrated/office_email_application_job_spec.rb, spec/mailers/application_mailer_spec.rb, spec/models/integrated/export_factory_spec.rb, spec/models/medicaid/export_factory_spec.rb, spec/rails_helper.rb
Disables back button and clears session once application has been submitted.
Also:
* Update some specs for ExportFactory that were testing the wrong class
* Stops draining workers after feature specs have been run
* Removes flaky delivery-checking in feature specs
[Finishes #154936523]
=> Add 'Application Submitted' step that sends application via email

app/controllers/integrated/reside_in_state_controller.rb, app/controllers/integrated/reside_out_of_state_controller.rb, app/forms/form_navigation.rb, app/forms/reside_in_state_form.rb, app/models/application_navigator.rb, app/models/common_application.rb, app/views/integrated/_yes_no_form.html.erb, app/views/integrated/reside_in_state/edit.html.erb, app/views/integrated/reside_out_of_state/edit.html.erb, db/migrate/20180227221714_create_application_navigators.rb, db/schema.rb, spec/controllers/integrated/reside_in_state_controller_spec.rb, spec/controllers/integrated/reside_out_of_state_controller_spec.rb, spec/factories/application_navigators.rb, spec/features/integrated_application_non_resident_spec.rb
And directs them to Healthcare.gov if they aren't.
Also creates 'ApplicationNavigator' object, which is intended to store application state and metadata. Should not be used to fill out final form. For now, we're trying out adding database defaults to direct application flow.
[#155521552]
=> Ask applicant whether they are a Michigan resident

app/controllers/integrated/introduce_yourself_controller.rb, app/forms/introduce_yourself_form.rb, app/models/common_application.rb, app/models/concerns/pdf_attributes.rb, app/models/integrated/pdf_attributes.rb, app/pdf_components/assistance_application_form.rb, app/views/integrated/introduce_yourself/edit.html.erb, db/migrate/20180228001545_add_previously_received_assistance_to_common_application.rb, db/schema.rb, spec/controllers/integrated/introduce_yourself_controller_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/pdf_components/assistance_application_form_spec.rb
* Creates special Integrated::PdfAttributes for filling out the new 1171 (old was getting messy, and there's not a ton of overlap with the existing PdfAttributes class)
* Creates database defaults for enums, and sets them to 'unfilled'
* Fills out PDF radio only if field has been answered
[Finishes #155532806]
=> Ask if applicant has previously received benefits

config/routes.rb, spec/routing/forms_routing_spec.rb
Since we're actually submitting applications at this point but the flow isn't finished, let's entirely block access to the path in production to prevent potential fake sends.
The paths will still be accessible on staging, test, and development environments.
[Finishes #155633310]
=> Block access to `/sections` and subpaths on production

app/controllers/forms_controller.rb, app/forms/form.rb, app/forms/introduce_yourself_form.rb, app/forms/living_situation_form.rb, app/forms/reside_in_state_form.rb, app/steps/step.rb, spec/forms/form_spec.rb, spec/steps/step_spec.rb
Creates new 'form' class (based off of 'step') that uses a combination of simple 'member_attributes' and 'application_attributes' to construct one set of common form attributes. Getters for these methods can then be used to filter params as appropriate for their respective models.
For now, 'member_attributes' and 'application_attributes' only accept keys or strings as attributes, unlike 'step_attributes' method, which accepts hashes. We can add this in later as we need it.
[#155522274]
Note: this is step one of the feature (have more on my local machine that I'll push to a WIP on another branch), but thought it'd be useful to get your thoughts sooner rather than later!
=> Refactor 'member_attributes' and 'application_attributes'

config/offices.yml, spec/models/office_recipient_spec.rb
Previously, for applications without a specified office location, we routed unsupported zip codes to Clio. Now they're routed to us (hello@michiganbenefits.org) to review instead.
https://www.pivotaltracker.com/story/show/155658198
=> Route non-supported zip codes to our email, rather than Clio

app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss, app/views/integrated/_next_step.html.erb, app/views/medicaid/contact_introduction/edit.html.erb, app/views/medicaid/contact_social_security/edit.html.erb, app/views/medicaid/contact_ss_intro/edit.html.erb, app/views/medicaid/contact_text_messages/edit.html.erb, app/views/medicaid/health_introduction/edit.html.erb, app/views/medicaid/income_introduction/edit.html.erb, app/views/medicaid/intro_name/edit.html.erb, app/views/medicaid/paperwork_and_legal_introduction/edit.html.erb, app/views/medicaid/tax_introduction/edit.html.erb, app/views/medicaid/welcome/edit.html.erb, app/views/shared/_yes_no_form.html.erb
_Too much space_
_Just right_
Also fixes a bunch of pages in medicaid that broke with the newly-adjusted spacing, for example:
=> Space buttons properly, add arrows, fix layouts

app/controllers/integrated/food_assistance_controller.rb, app/forms/food_assistance_form.rb, app/forms/form_navigation.rb, app/models/common_application.rb, app/models/household_member.rb, app/models/integrated/pdf_attributes.rb, app/pdf_components/assistance_application_form.rb, app/views/integrated/food_assistance/edit.html.erb, db/migrate/20180308214556_add_requesting_food_to_household_member.rb, db/schema.rb, spec/controllers/integrated/food_assistance_controller_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/features/integrated_application_with_single_member_spec.rb, spec/models/common_application_spec.rb, spec/pdf_components/assistance_application_form_spec.rb
When unstable housing, the checkbox screen is skipped, and
all members of the "household" are set to request food.
[#155522792]
Signed-off-by: Christa Harstock <christa@codeforamerica.org>
Co-authored-by: Christa Harstock <christa@codeforamerica.org>
=> Choose household members requesting food assistance.

config/application.rb, lib/generators/section/USAGE, lib/generators/section/section_generator.rb, lib/generators/section/templates/form_controller.template.rb, lib/generators/section/templates/form_controller_spec.template.rb, lib/generators/section/templates/form_model.template.rb, lib/generators/section/templates/form_model_spec.template.rb, lib/generators/section/templates/form_view.template.erb
By running `rails g section SectionName`, we can now generate a minimal scaffolding for what we need (form class and spec, form controller and spec, view). 
Usage instructions here:
```
Usage:
rails generate section NAME [options]
Options:
[--skip-namespace], [--no-skip-namespace]  # Skip namespace (affects only isolated applications)
[--doc], [--no-doc]                        # Include documentation.
Runtime options:
-f, [--force]                    # Overwrite files that already exist
-p, [--pretend], [--no-pretend]  # Run but do not make any changes
-q, [--quiet], [--no-quiet]      # Suppress status output
-s, [--skip], [--no-skip]        # Skip files that already exist
Description:
Create files for adding a new section to the integrated benefit application.
Example:
rails generate …
```
=> Simple generator for section

app/controllers/integrated/food_assistance_controller.rb, spec/controllers/integrated/food_assistance_controller_spec.rb
In the last feature PR, we started adding people to a SNAP household if they had stable housing, were requesting food, and indicated they bought food together. This meant that we wouldn't fill out the SNAP supplement for anyone in unstable housing, because they weren't prompted to indicate who they bought and prepared food with.
This PR adds members to the SNAP household automatically after someone with unstable housing adds them as household members, and also fills out the required fields on the SNAP supplement.
=> Add members to SNAP household when housing unstable

app/assets/stylesheets/atoms/_form-elements.scss, app/assets/stylesheets/atoms/_form-widths.scss, app/assets/stylesheets/atoms/_typography.scss, app/assets/stylesheets/atoms/_variables.scss, app/assets/stylesheets/molecules/_form-molecules.scss, app/controllers/forms_controller.rb, app/controllers/integrated/add_household_member_controller.rb, app/controllers/integrated/introduce_yourself_controller.rb, app/forms/add_household_member_form.rb, app/forms/introduce_yourself_form.rb, app/helpers/mb_form_builder.rb, app/models/concerns/birthday_validations.rb, app/views/integrated/add_household_member/edit.html.erb, app/views/integrated/introduce_yourself/edit.html.erb, config/locales/en.yml, spec/controllers/integrated/add_household_member_controller_spec.rb, spec/controllers/integrated/buy_and_prepare_food_with_other_person_controller_spec.rb, spec/controllers/integrated/introduce_yourself_controller_spec.rb, spec/features/integrated_application_non_resident_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/features/integrated_application_with_single_member_spec.rb, spec/features/integrated_application_with_two_members_spec.rb, spec/forms/add_household_member_form_spec.rb, spec/forms/introduce_yourself_form_spec.rb, spec/helpers/mb_form_builder_spec.rb, spec/support/include_html.rb
- adds new spec helper `include_html`
- only changes inputs for *integrated* flow
- uses new `mb_date_input` method to `MbFormBuilder`
- renders form errors as spans instead of divs
=> Enter birthday as text instead of select dropdown

app/controllers/integrated/share_food_costs_with_household_controller.rb, app/views/integrated/review_food_assistance_members/edit.html.erb, spec/controllers/integrated/share_food_costs_with_household_controller_spec.rb
When all household members are applying and share meals and costs:
Selecting “Yes” to “Do all of you share meals and food costs?” will correctly set `buy_and_prepare_food_together` on each member in the SNAP household.
https://www.pivotaltracker.com/story/show/156136462
=> Bugfix for SNAP household builder

app/controllers/integrated/buy_and_prepare_food_separately_controller.rb, app/controllers/integrated/buy_and_prepare_food_with_other_person_controller.rb, app/controllers/integrated/file_taxes_next_year_controller.rb, app/controllers/integrated/review_food_assistance_members_controller.rb, app/controllers/integrated/share_food_costs_with_household_controller.rb, app/forms/file_taxes_next_year_form.rb, app/forms/form_navigation.rb, app/models/common_application.rb, app/models/household_member.rb, app/pdf_components/food_assistance_supplement.rb, app/pdf_components/healthcare_coverage_supplement.rb, app/services/application_pdf_assembler.rb, app/views/integrated/file_taxes_next_year/edit.html.erb, app/views/integrated/review_food_assistance_members/edit.html.erb, db/migrate/20180320200147_add_filing_taxes_next_year_to_household_member.rb, db/schema.rb, spec/controllers/integrated/file_taxes_next_year_controller_spec.rb, spec/controllers/integrated/remove_snap_member_controller_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/features/integrated_application_with_single_member_spec.rb, spec/features/integrated_application_with_two_members_spec.rb, spec/models/common_application_spec.rb, spec/pdf_components/healthcare_coverage_supplement_spec.rb, spec/services/application_pdf_assembler_spec.rb
As part of this, adds the healthcare supplement and indicates whether someone is filing taxes, and who that person is (in this case, always the primary member).
Also renames `snap_applying_x` to `food_applying_x` per comments in https://github.com/codeforamerica/michigan-benefits/pull/709.
=> Ask if primary member is filing taxes next year

config/routes.rb
We don't use these actions, and they're often broken. So, let's remove them.
'Edit' and 'New' links be gone:
[Finishes #155668442]
=> Disable new and edit actions in administrate

app/controllers/integrated/add_member_controller.rb, app/views/integrated/add_food_member/edit.html.erb, app/views/integrated/add_healthcare_member/edit.html.erb, app/views/integrated/add_household_member/edit.html.erb, app/views/integrated/add_tax_member/edit.html.erb, spec/controllers/integrated/add_food_member_controller_spec.rb, spec/controllers/integrated/add_healthcare_member_controller_spec.rb, spec/controllers/integrated/add_household_member_controller_spec.rb, spec/controllers/integrated/add_tax_member_controller_spec.rb, spec/support/shared_examples/add_member_controller.rb
If someone has already been added as a spouse, remove spouse as an option for future added members. Add option back in if spouse was removed.
=> Remove spouse as relationship option when spouse already in household

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/michigan-benefits/molecules/_form-molecules.scss, app/controllers/integrated/add_member_controller.rb, app/controllers/integrated/add_tax_member_controller.rb, app/forms/add_tax_member_form.rb, app/views/integrated/add_tax_member/edit.html.erb, spec/controllers/integrated/add_tax_member_controller_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb
- Uses GCF’s Follow Up molecule.
- To be accessible, creates a distinct `tax_relationship_spouse` radio set which then gets set to `tax_relationship` in the controller.
https://www.pivotaltracker.com/story/show/156242462
=> Reveal tax relationships based on relationship to member when adding a new member

Gemfile, Gemfile.lock
There's a known security vulnerability in delayed_job_web, that we addressed by disabling the web interface until it is resolved. Github is still warning us that the gem is in our gemfile.lock, though, so this commit removes the gem to resolve the warning.
[#155759158]
=> Remove delayed_job_web from Gemfile.lock

app/lib/gate_keeper.rb, app/models/snap_application.rb, config/routes.rb, spec/lib/gate_keeper_spec.rb, spec/models/snap_application_spec.rb
Previously, we blocked access to the combined application (`/sections/*`) on any environment where RAILS_ENV=production, which included our demo site.
In prep for an upcoming presentation, I'm unblocking that route in demo. Applications aren't in danger of sending anyway, since this is already blocked on demo.
While touching GateKeeper, I noticed that we had an unused 'NEW FORM' feature flag in SnapApplication PDF generation—think we added to build infrastructure for the new form before the integrated flow was under way. We aren't using the new Civilla PDF for the old application flows, so this commit removes the logical branch.
=> Unblock integrated flow on demo environment

app/views/layouts/application.html.erb, spec/features/staging_warning_spec.rb
For testing with Lighthouse on Monday, disable the example website banner.
Revert this commit after to reenable on staging and demo environments.
=> Disable banner on demo websites

app/controllers/concerns/type_checkbox.rb, app/models/expense.rb, app/models/income.rb, spec/controllers/integrated/housing_expenses_controller_spec.rb, spec/controllers/integrated/income_sources_controller_spec.rb, spec/controllers/integrated/utility_expenses_controller_spec.rb, spec/models/expense_spec.rb, spec/pdf_components/food_assistance_supplement_spec.rb
Fixes for Rubocop, since the feature PR I had intended to submit got swept up with the last merged PR before review/CI could catch it.
Opening this PR primarily to get visibility on the commit that snuck through the previous PR review [Here's that commit](https://github.com/codeforamerica/michigan-benefits/commit/a4eb6713839090738dfcb32e9c7d83b2bb5f6cc7)
And here's what it does—asks user about their housing expenses:
=> Rubocop fixes

app/controllers/forms_controller.rb, app/controllers/integrated/property_controller.rb, app/forms/form.rb, app/forms/form_navigation.rb, app/forms/property_form.rb, app/helpers/mb_form_builder.rb, app/models/common_application.rb, app/pdf_components/assistance_application_form.rb, app/views/integrated/housing_expenses/edit.html.erb, app/views/integrated/income_sources/edit.html.erb, app/views/integrated/property/edit.html.erb, app/views/integrated/utility_expenses/edit.html.erb, config/locales/en.yml, db/migrate/20180423230634_add_properties_to_common_application.rb, db/schema.rb, spec/controllers/integrated/how_many_babies_controller_spec.rb, spec/controllers/integrated/property_controller_spec.rb, spec/controllers/integrated/vehicles_controller_spec.rb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/features/integrated_application_with_single_member_spec.rb, spec/features/integrated_application_with_two_members_spec.rb, spec/forms/form_spec.rb, spec/helpers/mb_form_builder_spec.rb, spec/pdf_components/assistance_application_form_spec.rb
Also:
* Modifies form_attributes to accept array (e.g. `application_attributes(dogs: [])`)
* Creates new form builder method to use with the checkbox + none pattern.
* Expands support in checkbox_set to accept a simple array, rather than to assign methods/attributes directly to form (e.g. will result in post like `["foo", "bar"]` rather than `{ foo: "1", bar: "0" }`. This is useful for updating simple array attributes on one model, rather than updating a collection of models
=> Ask applicant if they own property

app/forms/mailing_address_form.rb, app/forms/residential_address_form.rb, app/views/integrated/mailing_address/edit.html.erb, spec/features/integrated_application_with_multiple_members_spec.rb, spec/features/integrated_application_with_single_member_spec.rb, spec/forms/mailing_address_form_spec.rb, spec/forms/residential_address_form_spec.rb
Previously, we only required that zip code be 5 digits. This makes sure that those 5 digits are all numbers!
Also adds a few tests and makes a small copy update.
[Fixes #156390099]
[Fixes #156390093]
=> Require zip code be a 5-digit number

DESIGN-README.md
Styleguide repo is currently in a private repository, which was pointed out to us via a Github issue. This commit removes the link until the repository is made public.
Resolves https://github.com/codeforamerica/michigan-benefits/issues/782
=> Update readme with styleguide repo

app/views/integrated/job_details/edit.html.erb
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Allowing_decimal_values
This is a browser validation that is currently not caught by our integration tests (driver doesn't do the same validation we're seeing in Chrome that caused the bug), so no tests are added.
Only allowed decimal value on hourly wage, because it didn't' seem to make sense to allow it for salary. The backend validation allows cents for both, though, because it's the same field under the hood and uses a regex that does allow decimal values (the field is a string).
[Fixes #158432889]
=> Allow cent amounts with HTML5 number input on hourly wage

app/assets/stylesheets/michigan-benefits/organisms/_step-header.scss, app/views/static_pages/privacy.html.erb
The 'This is an example website' banner was causing some funky CSS on the Privacy Policy page. This fixes it.
Simple change, so will merge after tests pass.
*Before*:
*After*:
=> Keep Privacy Policy banner at top on demo + staging

app/assets/stylesheets/michigan-benefits/atoms/_variables.scss, app/views/layouts/form.html.erb, app/views/layouts/step.html.erb, app/views/messages/new.html.erb, app/views/shared/_footer.html.erb, app/views/static_pages/clio.html.erb, app/views/static_pages/index.html.erb, app/views/static_pages/union.html.erb
Also adjust the height of the footer.
Office links are removed for in-flow pages so that they're not accidentally tapped on:
[#158482452]
=> Show office links in the footer on non-flow pages only.

app/models/common_application.rb, spec/factories/household_members.rb, spec/models/common_application_spec.rb, spec/models/household_member_spec.rb
Sets are fun! This updates the new integated flow scopes to what we intended:
* FAP-only returns applications that only have members applying for FAP
* Medicaid-only returns applications that only have members applying for Medicaid
* FAP and Medicaid returns applications that has memebers applying for either/both FAP and Medicaid
[Fixes #158617351]
=> Correct integrated application flow scopes

app/helpers/mb_form_builder.rb, spec/helpers/mb_form_builder_spec.rb
We were previously disabling autofill and a few other annoying-to-client attributes on most inputs, but had missed adding it to the date of birth text input. This commit adds it for DOB and refactors the standard set of options.
[Finishes #158670432]
=> Disable autofill on DOB fields

config/environments/production.rb
I missed requiring the SMTP config for production env when upgrading Rails to 5.2, which resulted in an error on Sentry in our staging env. This should fix that—we'll want to get in before we do the next production deploy.
=> Add missing SMTP config for production env

app/controllers/integrated/introduce_yourself_controller.rb, spec/controllers/integrated/review_healthcare_household_controller_spec.rb, spec/controllers/integrated/share_food_costs_with_household_controller_spec.rb, spec/controllers/medicaid/amounts_income_controller_spec.rb, spec/features/snap_application_with_maximum_info_spec.rb, spec/models/dhs1426_pdf_spec.rb, spec/models/medicaid_application_member_attributes_spec.rb, spec/rails_helper.rb
This contains Rubocop fixes (are my and @hartsick's Rubocop config different?) and sets `default_max_wait_time` to as low as it can be to pass the JS-dependent feature specs.
=> Reduce test time

.circleci/config.yml
We use Heroku's Github hook to automatically deploy any push to master, so this piece of config is no longer needed.
[Finishes #158200178]
=> Remove deploy config from Circle CI

app/assets/javascripts/application.js.erb, app/assets/stylesheets/molecules/_form-molecules.scss, app/controllers/feedbacks_controller.rb, app/forms/feedback_form.rb, app/views/feedbacks/_form.html.erb, app/views/feedbacks/_success.html.erb, app/views/feedbacks/create.js.erb, app/views/integrated/application_submitted/edit.html.erb, spec/controllers/integrated/feedbacks_controller_spec.rb, spec/forms/feedback_form_spec.rb
Renders an accessible radio button set and displays errors using our form builder.
I decided not to show a visible error if there's no application, since it seemed confusing to the user. Just fails silently.
Also fixes a related bug, where our radio button set didn't properly show when buttons are selected after an initial error submission (go to page, submit an invalid state, then try to select the button again to see this—the button won't be visibly selected, but it will submit the right value).
=> Feedback form accessible

app/assets/stylesheets/michigan-benefits/molecules/_form-molecules.scss, app/forms/feedback_form.rb, app/views/feedbacks/_form.html.erb, spec/forms/feedback_form_spec.rb
If user enters a comment or a rating, feedback submission is considered valid.
Also includes some minor styling changes.
[Fixes #159703918]
=> Require that any feedback be entered, not just rating
