codeforamerica/michigan-benefits

CONTRIBUTING.md
README.md

* This details how this team writes code

Add CONTRIBUTING doc

---

app/views/users/new.html.haml

**WHY**: This stuff is not currently functional.

Remove placeholder code

---

Gemfile
Gemfile.lock

**WHY**: used to look for file changes in the dev environment

Re-add listen gem

---

circle.yml

**WHY**: Was getting "Coverage results not found" error

Update circle config for codeclimate test reporter

---

app/controllers/send_application_controller.rb
spec/controllers/send_application_controller_spec.rb

* Was not sending keyword arg before - oops!

Call Job properly

---

README.md

* Centralize the non-code things necessary to get started on the team.
Changes
=======
* Add some items to ask for when joining the team to the `README.md` file.

Add an Onboarding Checklist

---

app/views/personal_detail/edit.html.erb

Change navigation text to "Introduction"

---

app/views/layouts/application.html.erb
app/views/pages/index.html.erb
app/views/shared/_demo_banner.html.erb

Add demo banner, replace image on home page

---

app/views/pages/index.html.erb

* this was added twice in
https://github.com/codeforamerica/michigan-benefits/pull/59/
accidentally

Remove accidentally added copy

---

app/controllers/contact_information_controller.rb
app/helpers/mb_form_builder.rb
app/steps/address.rb
app/steps/contact_information.rb
app/steps/step_navigation.rb
app/views/address/edit.html.erb
app/views/contact_information/edit.html.erb
db/migrate/20170807214127_add_phone_and_sms_subscribed_at_to_snap_applications.rb
db/schema.rb
spec/controllers/address_controller_spec.rb
spec/controllers/contact_information_controller_spec.rb
spec/controllers/personal_detail_controller_spec.rb
spec/features/snap_app_spec.rb

Adds phone number, sms subscribed (boolean), and email fields to a new 
"contact information" page, which comes before address page.

As an MDHHS worker, I want to know the clients phone number and email

---

.codeclimate.yml
app/assets/javascripts/upload_setup.js

* We are hardly writing js anyway
* It is failing in weird ways right now

Remove eslint check from rubocop

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/atoms/_legal-agreement.scss
app/assets/stylesheets/atoms/_typography.scss
app/assets/stylesheets/organisms/_legal.scss
app/controllers/legal_agreement_controller.rb
app/steps/legal_agreement.rb
app/steps/step_navigation.rb
app/views/legal_agreement/_terms.html.erb
app/views/legal_agreement/edit.html.erb
db/migrate/20170807235447_add_consent_to_terms_to_snap_applications.rb
db/schema.rb
spec/controllers/legal_agreement_controller_spec.rb
spec/features/snap_app_spec.rb

Add consent to legal terms page

---

app/assets/javascripts/upload_setup.js
app/assets/stylesheets/organisms/_document-preview.scss
app/assets/stylesheets/organisms/_form-card.scss
app/views/documents/edit.html.erb
app/views/shared/_commonly_requested_documents.html.erb

Change verbage and content around the documents page to reflect what
exists currently at GetCalFresh.
Trello:
* https://trello.com/c/PMl961LU/70-when-i-am-prompted-with-the-option-to-upload-documents-i-want-to-receive-helpful-guidance-about-what-is-actually-required-and-he
* https://trello.com/c/eKV6U8jR/71-as-a-client-i-want-guidance-about-which-documents-to-upload-when-prompted

Add commonly requested documents

---

config/application.rb

Rename app in config

---

spec/controllers/contact_information_controller_spec.rb
spec/controllers/legal_agreement_controller_spec.rb
spec/controllers/mailing_address_controller_spec.rb
spec/controllers/personal_detail_controller_spec.rb
spec/controllers/residential_address_controller_spec.rb
spec/controllers/send_application_controller_spec.rb
spec/controllers/sign_and_submit_controller_spec.rb
spec/rails_helper.rb
spec/support/shared_examples/step_controller.rb

* Can put more shared behavior in the future. Should make it easier to
add and test new steps.

Add shared example group for step controllers

---

app/controllers/introduce_yourself_controller.rb
app/controllers/personal_detail_controller.rb
app/helpers/mb_form_builder.rb
app/models/member.rb
app/models/snap_application.rb
app/steps/introduce_yourself.rb
app/steps/personal_detail.rb
app/steps/step_navigation.rb
app/views/introduce_yourself/edit.html.erb
app/views/personal_detail/edit.html.erb
db/migrate/20170811005112_create_members.rb
db/schema.rb
spec/controllers/introduce_yourself_controller_spec.rb
spec/controllers/mailing_address_controller_spec.rb
spec/controllers/personal_detail_controller_spec.rb
spec/controllers/residential_address_controller_spec.rb
spec/factories/member.rb
spec/features/snap_app_spec.rb

* Page asks for sex, marital status, SSN
* Introducing concept of "members" since we will soon be asking this
for multiple people.

Add personal detail page for app members

---

Gemfile
Gemfile.lock
app/controllers/personal_detail_controller.rb
app/models/member.rb
app/steps/personal_detail.rb
app/views/personal_detail/edit.html.erb
config/secrets.yml
db/migrate/20170811162824_encrypt_social_security_number.rb
db/schema.rb
spec/controllers/personal_detail_controller_spec.rb

Use attr_encrypted to encrypt SSN

---

app/controllers/address_controller.rb
app/controllers/application_controller.rb
app/controllers/introduce_yourself_controller.rb
app/controllers/personal_detail_controller.rb
app/controllers/standard_steps_controller.rb
app/views/shared/_debug.html.erb

* Per Joel feedback in https://github.com/codeforamerica/michigan-benefits/pull/83/files#r132675670

Small controller refactor

---

app/controllers/introduce_yourself_controller.rb
app/controllers/introduction_complete_controller.rb
app/models/dhs1171_pdf.rb
app/models/member.rb
app/models/null_member.rb
app/models/snap_application.rb
app/steps/introduce_yourself.rb
app/steps/introduction_complete.rb
app/steps/step_navigation.rb
app/views/introduce_yourself/edit.html.erb
app/views/introduction_complete/edit.html.erb
app/views/layouts/application.html.erb
app/views/personal_detail/edit.html.erb
db/migrate/20170811210655_move_name_to_members.rb
db/schema.rb
spec/controllers/introduce_yourself_controller_spec.rb
spec/controllers/introduction_complete_controller_spec.rb
spec/controllers/residential_address_controller_spec.rb
spec/factories/member.rb
spec/factories/snap_applications.rb
spec/features/snap_app_spec.rb
spec/models/dhs1171_pdf_spec.rb
spec/support/feature_helper.rb

Add introduction complete interstitial page

---

.rubocop.yml
app/controllers/introduce_yourself_controller.rb
app/controllers/mailing_address_controller.rb
app/controllers/personal_detail_controller.rb
app/controllers/residential_address_controller.rb
app/controllers/success_controller.rb
app/helpers/mb_form_builder.rb
app/helpers/steps_helper.rb
app/models/concerns/multiparameter_attribute_assignment.rb
app/models/dhs1171_pdf.rb
app/models/member.rb
app/steps/contact_information.rb
app/steps/legal_agreement.rb
app/steps/mailing_address.rb
config/initializers/assets.rb
config/initializers/backtrace_silencers.rb
config/initializers/request_forgery_protection.rb
config/initializers/wrap_parameters.rb
config/puma.rb
config/routes.rb
spec/controllers/legal_agreement_controller_spec.rb
spec/controllers/mailing_address_controller_spec.rb
spec/controllers/sign_and_submit_controller_spec.rb
spec/controllers/success_controller_spec.rb
spec/features/snap_app_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/feature_helper.rb
spec/support/generic_helper.rb
spec/support/match_html.rb

80 char limit, please!

---

app/controllers/household_add_member_controller.rb
app/controllers/household_members_overview_controller.rb
app/models/snap_application.rb
app/steps/household_add_member.rb
app/steps/household_members_overview.rb
app/steps/step_navigation.rb
app/views/household_add_member/edit.html.erb
app/views/household_members_overview/edit.html.erb
db/migrate/20170814185733_add_attributes_to_members.rb
db/schema.rb
spec/controllers/houseold_add_member_controller_spec.rb
spec/controllers/introduce_yourself_controller_spec.rb
spec/controllers/personal_detail_controller_spec.rb
spec/features/snap_app_spec.rb

* "household add member" is a substep of "household members overview"

Add details for household members

---

app/controllers/income_change_controller.rb
app/controllers/income_change_explanation_controller.rb
app/helpers/mb_form_builder.rb
app/steps/income_change.rb
app/steps/income_change_explanation.rb
app/steps/step_navigation.rb
app/views/income_change/edit.html.erb
app/views/income_change_explanation/edit.html.erb
db/migrate/20170814234130_add_income_change_to_snap_applications.rb
db/schema.rb
spec/features/snap_app_spec.rb

Add extra income / explanation page

---

app/controllers/income_details_per_member_controller.rb
app/models/member.rb
app/steps/income_details_per_member.rb
app/steps/step_navigation.rb
app/views/income_details_per_member/edit.html.erb
db/migrate/20170816000025_add_employment_fields_to_members.rb
db/schema.rb
spec/controllers/income_details_per_member_controller_spec.rb
spec/controllers/income_employment_status_controller_spec.rb
spec/features/snap_app_spec.rb
spec/rails_helper.rb
spec/support/step_helper.rb

Collect employment details for employed and self employed

---

app/controllers/household_more_info_per_member_controller.rb
app/helpers/mb_form_builder.rb
app/steps/household_more_info_per_member.rb
app/steps/step_navigation.rb
app/views/household_more_info_per_member/_member_checkboxes.html.erb
app/views/household_more_info_per_member/edit.html.erb
db/migrate/20170816190450_add_more_info_fields_to_members.rb
db/schema.rb
spec/controllers/household_more_info_per_member_controller_spec.rb
spec/features/member_not_citizen_spec.rb
spec/features/snap_app_spec.rb
spec/support/feature_helper.rb

* Ask about each person based on meta responses about household.

Add household "more info" questions per member

---

app/controllers/expenses_introduction_controller.rb
app/controllers/household_introduction_controller.rb
app/controllers/income_introduction_controller.rb
app/steps/introduction_complete.rb
app/steps/step_navigation.rb
app/views/expenses_introduction/edit.html.erb
app/views/household_introduction/edit.html.erb
app/views/income_introduction/edit.html.erb
app/views/introduction_complete/edit.html.erb
spec/controllers/introduction_complete_controller_spec.rb
spec/features/snap_app_spec.rb

* Part 4 references text and email subsriptions, not sure if we want to
do those yet
1:
2:
3:

Add interstitial pages for Parts 1, 2, 3

---

app/controllers/income_additional_controller.rb
app/controllers/income_additional_sources_controller.rb
app/steps/income_additional.rb
app/steps/income_additional_sources.rb
app/steps/step_navigation.rb
app/views/income_additional/edit.html.erb
app/views/income_additional_sources/edit.html.erb
app/views/income_details_per_member/edit.html.erb
db/migrate/20170816162458_add_additional_income_to_snap_applications.rb
db/migrate/20170816173900_add_additional_income_fields_to_snap_applications.rb
spec/features/snap_app_spec.rb

Add "additional sources of income" page

---

app/controllers/expenses_additional_controller.rb
app/controllers/income_additional_sources_controller.rb
app/controllers/income_other_assets_continued_controller.rb
app/controllers/income_other_assets_controller.rb
app/controllers/steps_controller.rb
app/steps/income_other_assets.rb
app/steps/income_other_assets_continued.rb
app/steps/step_navigation.rb
app/views/income_other_assets/edit.html.erb
app/views/income_other_assets_continued/edit.html.erb
db/migrate/20170818175444_add_income_fields_to_snap_applications.rb
db/schema.rb
spec/controllers/income_other_assets_controller_spec.rb
spec/features/snap_app_spec.rb

Add steps for other income

---

app/controllers/expenses_additional_controller.rb
app/steps/expenses_additional.rb
app/steps/expenses_additional_source.rb
app/views/expenses_additional/edit.html.erb
app/views/expenses_additional_sources/edit.html.erb
db/migrate/20170818220929_remove_tax_deductible_expenses.rb
db/schema.rb
spec/controllers/expenses_additional_controller_spec.rb
spec/features/snap_app_spec.rb
spec/steps/expenses_additional_source_spec.rb

* Remove fields for "Tax deductible"
* Only show follow up questions for expenses indicated (Eg: if no
medical expenses, don't ask for types of medical expenses)

Updates to expenses section

---

app/models/dhs1171_pdf.rb
app/models/snap_application_attributes.rb
app/models/snap_application_member_attributes.rb
spec/factories/member.rb
spec/models/dhs1171_pdf_spec.rb
spec/models/snap_application_attributes_spec.rb
spec/models/snap_application_member_attributes_spec.rb

* Rename class for member attributes
* Add class for snap app attributes
* Add spec for multiple household members

Refactor PDF filling code

---

db/migrate/20170825182343_add_default_to_members_buy_food_with.rb
db/schema.rb

Add default for "buy food with" attr on members

---

app/helpers/steps_helper.rb
app/views/general_anything_else/edit.html.erb

* Was created / merged after FE audit on Friday
Update look:

Update header style on newest page

---

app/helpers/mb_form_builder.rb
db/migrate/20170825210619_change_floats_to_integers.rb
db/schema.rb
spec/models/dhs1171_pdf_spec.rb
spec/models/employed_member_attributes_spec.rb

* Move from floats to integers
* Make inputs full width

Fix formatting of money input fields

---

app/mailers/application_mailer.rb

Send system emails from `hello@`

---

Gemfile
Gemfile.lock
app/models/dhs1171_pdf.rb
app/models/snap_application_extra_member_attributes.rb
app/models/snap_application_extra_member_pdf.rb
config/brakeman.ignore
spec/models/dhs1171_pdf_spec.rb
spec/models/snap_application_extra_member_attributes_spec.rb

**WHY**: Form only has place for 6 members in "Section C", but we allow
people to add unlimited household members in the web version of the app.

Append to 1171 PDF if more than 6 household members

---

Gemfile
Gemfile.lock

* Per setup rec from Heroku
* See https://devcenter.heroku.com/articles/sentry
=

Configure Sentry to capture unhandled errors

---

app/models/member.rb
app/views/income_details_per_member/edit.html.erb

* Make inputs for employment "money" fields
* Fix instance of wrong constant usage

2 small updates based on QA

---

app/mailers/application_mailer.rb

This reverts commit 8c8ac351123f267079a9776a0ed29275d1cc13c6.
We fixed the original problem, so this temporary solution is no longer needed.

Revert "Replace hello@michiganbenefits.org"

---

app/controllers/standard_steps_controller.rb
app/controllers/success_controller.rb

Waiting for a fax is not a great user experience when demoing.

Fax office immediately after applicant indicates they are done

---

app/models/verification_document.rb

Apparently most PDFs are identified as PBMs?

---

DESIGN-README.md

* Add Design README
* https://trello.com/c/LLWawjxt/212-contributor-process-for-design
Changes
=======
* Add onboarding resources and design process/workflow

Add Design Readme

---

app/lib/pdf_builder.rb
app/models/verification_document.rb

We're running into a possible issue where pdfs are not being attached. Adding debug logging statements so we have a better audit trail for this.

Log downloading documents and attaching them to PDF

---

Gemfile
Gemfile.lock
app/models/snap_application.rb
app/models/snap_application_attributes.rb
spec/models/dhs1171_pdf_spec.rb
spec/models/snap_application_attributes_spec.rb
spec/models/snap_application_spec.rb

**WHY**: Math is hard. And this reads better, anyway!

Show signature in EST on PDF

---

app/views/pages/index.html.erb

* Update copy to help user feel comfortable providing confidential information. 
* https://trello.com/c/2G0Jzyvp/221-home-as-a-user-i-want-to-feel-secure-about-providing-confidential-information-eg-social-security-bank-statements-etc-to-this-sit
Changes
=======
* Copy updates

Copy updates

---

DEPLOYING.md
bin/release
bin/release-diff
bin/setup
config/offices.yml
lib/tasks/one_offs.rake
spec/models/fax_recipient_spec.rb

**Why?** - Deploying is scary! Lists make it less scary. Automation makes it even less scarier; but I didn't want to dive too deep too fast.

Brief guide for deploying

---

app/assets/stylesheets/atoms/_form-elements.scss

* Make form borders consistent
* https://trello.com/c/mJSQIhjJ/234-personal-details-make-form-borders-consistent

Make form borders consistent

---

app/views/expenses_housing/edit.html.erb

* Update copy to be more clear for users
* https://trello.com/c/TFFAYEvx/161-update-housing-expenses-page

Update housing expense copy

---

app/assets/stylesheets/templates/_homepage.scss
app/views/pages/index.html.erb

* https://trello.com/c/vGjpPBDL/259-remove-fap-box-on-homepage-and-any-other-homepages
* https://trello.com/c/geFoOWoa/253-mobile-layout-on-staging
Changes
=======
* Remove FAP box
* Fix mobile spacing

Home page update: remove FAP box, fix mobile padding

---

bin/release

* Minor text UI tweaks - some double negatives were confusing.
Changes
=======
* Copy edits
Minor
-----
* Made the output a little less verbose

Edits to release script

---

app/views/layouts/application.html.erb

* Previous renaming had made it not show up

Show banner on home page

---

app/assets/stylesheets/michigan-benefits/organisms/_main-footer.scss
app/views/shared/_footer.html.erb

* https://trello.com/c/qtCshxNc/284-update-footer
* Simplify content
* Add office pages

Rc footer update

---

app/views/admin/snap_applications/index.html.erb
spec/factories/exports.rb
spec/factories/snap_applications.rb
spec/features/admin_dashboard_spec.rb
spec/jobs/fax_application_job_spec.rb
spec/models/export_spec.rb

* Previously they were only the current page
* https://trello.com/c/Z2pv4On3/273-admin-signed-stats-are-incorrect
Changes
=======
* Use a percentage of total instead of percentage of previous  cohort

Admin stats cover all applications

---

app/controllers/admin/application_controller.rb
app/dashboards/snap_application_dashboard.rb

* Default sort order to show most recently created first
* Show office location on the dashboard
* Ref for order code: https://github.com/thoughtbot/administrate/issues/442#issuecomment-249712581

Small admin tweaks

---

app/assets/stylesheets/atoms/_typography.scss

* Make links blue 
* https://trello.com/c/rwxeO1vP/240-update-links-to-the-blue

Update link colors to brand blue

---

lib/mi_bridges/driver.rb
lib/mi_bridges/driver/base_page.rb
lib/mi_bridges/driver/debugger_page.rb
lib/mi_bridges/driver/finish_page.rb
lib/mi_bridges/driver/school_details_page.rb
lib/mi_bridges/driver/submit_page.rb

* Allows us to fill the school page with the primary members school information
* Adds some sweet debugging ability while working on prototype pages
* https://trello.com/c/oKZY4ztn/278-drive-the-schools-page

Add School Enrollment Details to Driver

---

app/views/expenses_additional_sources/edit.html.erb
app/views/expenses_housing/edit.html.erb
app/views/sign_and_submit/edit.html.erb
spec/features/snap_application_with_maximum_info_spec.rb
spec/features/snap_application_with_minimal_info_spec.rb

* Update copy to make it more intuative/clear. 
* These changes were based on user feedback.
* https://trello.com/c/mxN3RiQK/289-expenses-update-copy-how-much-does-your-household-currently-pay-in-rent-or-mortgage-each-month
* https://trello.com/c/UD8WS1vf/296-expenses-update-copy-this-includes-arrearages-child-support-alimony-etc
* https://trello.com/c/P8kYZAT2/295-expenses-change-coolingto-air-conditioning
* https://trello.com/c/7UeCPd8V/291-signature-page-change-your-signature-to-sign-by-typing-your-full-legal-name

Update application copy

---

lib/mi_bridges/driver/base_page.rb
lib/mi_bridges/driver/household_member_questions_page.rb
lib/mi_bridges/driver/housing_bills_page.rb
lib/mi_bridges/driver/housing_utility_bills_page.rb
lib/mi_bridges/driver/job_income_information_page.rb
lib/mi_bridges/driver/liquid_assets_page.rb
lib/mi_bridges/driver/money_other_sources_page.rb
lib/mi_bridges/driver/other_assets_page.rb
lib/mi_bridges/driver/utility_bills_page.rb
lib/mi_bridges/driver/your_other_bills_expenses_page.rb

* Now that we are no longer using if, we can use named args

Rename args for "check_in_section" method

---

bin/release

* The `release` script doesn't work without something in the `if` branch.
Changes
=======
* Added back some trivial echoing.

Fix broken release script

---

app/assets/stylesheets/atoms/_buttons.scss
app/views/document_guide/edit.html.erb
spec/features/snap_application_with_maximum_info_spec.rb

* Update secondary button color to be more prominent
* https://trello.com/c/o9pNcXDj/271-buttons-update-secondary-button-color

Update secondary button color to light grey

---

bin/release
lib/mi_bridges/driver.rb
lib/mi_bridges/driver/debugger_page.rb
spec/factories/member.rb
spec/features/mi_bridges_driving_spec.rb
spec/spec_helper.rb

* Run as part of deploy script

Add contract test for MI Bridges driving code

---

app/assets/stylesheets/templates/_homepage.scss
app/views/pages/_home_page_bottom_section.html.erb

* Separate SNAP explanation from information about MichiganBenefits.
* Add info sectino on MichiganBenefits and privacy concerns
* https://trello.com/c/fO8I930e/225-home-as-a-user-i-want-a-clear-explanation-of-what-snap-is-and-how-this-site-helps

Add SNAP explanation and Michigan Benefits section

---

app/assets/stylesheets/organisms/_form-card.scss
app/helpers/mb_form_builder.rb
app/views/contact_information/edit.html.erb
app/views/expenses_additional/edit.html.erb
app/views/household_more_info_per_member/edit.html.erb
app/views/income_additional/edit.html.erb
app/views/income_details_per_member/edit.html.erb
app/views/personal_detail/edit.html.erb

* https://trello.com/c/P6e3PbqN/228-application-as-a-user-i-want-to-know-which-fields-are-required-throughout-the-application 
* Add Optional tag to application questions that are not required

Add Optional tags to non-required fields

---

.rubocop.yml
app/controllers/contact_confirm_phone_number_controller.rb
app/controllers/expenses_additional_sources_controller.rb
app/controllers/steps_controller.rb
app/controllers/success_controller.rb
app/helpers/mb_form_builder.rb
app/models/concerns/multiparameter_attribute_assignment.rb
app/models/export.rb
app/models/office_recipient.rb
app/validators/ten_digit_phone_number_validator.rb
lib/mi_bridges/driver.rb
spec/features/snap_application_with_maximum_info_spec.rb

* These popped up after we upgraded the gem

Fix rubocop errors

---

lib/mi_bridges/driver/relationship_information_page.rb
lib/mi_bridges/driver/services/submit_buy_food_with.rb
lib/mi_bridges/driver/services/submit_relationship.rb

**WHY**: There is a lot of logic here. Better to encapsulate in a
service obj.

Extract relationship/ buy food with sections into classes

---

lib/mi_bridges/driver/services/submit_relationship.rb

* Men are husbands, but women are spouses!

Update relationship mapping for women

---

app/controllers/admin/snap_applications_controller.rb
app/controllers/success_controller.rb
app/views/admin/snap_applications/_collection.html.erb
config/routes.rb
spec/controllers/success_controller_spec.rb
spec/features/admin_dashboard_spec.rb

**WHY**: we are emailing offices now

Turn off office fax

---

app/models/snap_application.rb

* When we delete a snap app, we don't want the addresses, members, and
exports for that snap app floating around.

Delete child records when deleting a snap app

---

app/steps/household_add_member.rb
app/views/household_add_member/edit.html.erb
spec/steps/household_add_member_spec.rb

* We do not require clients to submit an answer for this question, but
it's good to give them the option

Add "Other" as relationship option

---

lib/mi_bridges/driver/start_page.rb

* So they know it's in partnership with Civilla
* On start page

Add community partner ID when applying

---

app/controllers/income_additional_controller.rb
app/dashboards/snap_application_dashboard.rb
app/models/snap_application.rb
app/steps/income_additional.rb
app/steps/income_additional_sources.rb
app/views/income_additional_sources/edit.html.erb
db/migrate/20170926234635_remove_income_foster_care.rb
db/schema.rb
spec/models/dhs1171_pdf_spec.rb
spec/models/snap_application_spec.rb

**WHY**: as far as we can tell, it is not needed

Remove foster care income option

---

db/seeds.rb
lib/mi_bridges/driver.rb
lib/mi_bridges/driver/absent_parent_details_page.rb
lib/mi_bridges/driver/absent_parent_details_summary_page.rb
lib/mi_bridges/driver/absent_parent_information_page.rb
lib/mi_bridges/driver/absent_parent_summary_page.rb
lib/mi_bridges/driver/conception_page.rb
lib/mi_bridges/driver/information_about_the_child_page.rb

* We are filling in the minimal info possible, which means only filling
in required fields. This means that we have the following data for all
minors who are not living with both parents:
1. Indicating that the mother (if absent) was single - never married when pregnant
2. Indicating name unknown for all absent parents, which means we do not
need to include the required first and last name for absent parents.
Minor:
* also updated seeds so we have a minor in the "complete" application
Page 1:
Page 2:
Page 3:
Page 4:
Page 5:

Absent parent pages

---

app/steps/household_more_info_per_member.rb
app/steps/income_details_per_member.rb
app/steps/income_employment_status.rb
app/steps/many_members_step.rb
app/views/income_details_per_member/_header.html.erb
app/views/income_details_per_member/edit.html.erb
spec/controllers/income_details_per_member_controller_spec.rb
spec/steps/income_details_per_member_spec.rb

**WHY**: This is a required field in MI Bridges, so we need to collect
the info in order to drive applications successfully.

Validate employer name for employed members

---

lib/mi_bridges/driver/your_other_bills_expenses_page.rb

... in the "Other Bills / Expenses" page.
Not checking anything in that section resulted in an infinitely loop
asking for that section to be handled.

Fill in section re: dependent care bills

---

Gemfile
Gemfile.lock
app/jobs/submit_application_via_mi_bridges_job.rb
app/models/driver_application.rb
spec/models/driver_application_spec.rb
spec/models/export_factory_spec.rb
spec/models/null_member_spec.rb
spec/rails_helper.rb

* This doesn't get us to 100% but it was low hanging fruit

Add test coverage

---

db/seeds.rb
lib/mi_bridges/driver.rb
lib/mi_bridges/driver/people_listed_page.rb

* This tricky little optional checkbox needs to be checked to enroll
members in food assistance.

Actually enroll people in FAP :)

---

bin/re_drive
lib/mi_bridges/driver.rb
lib/mi_bridges/driver/go_back_to_application_page.rb
spec/features/mi_bridges_driving_spec.rb

* bin/re_drive goes through a sign in flow rather than sign up

Add script for re-driving a Snap Application

---

.overcommit.yml
db/migrate/20171005000507_add_tracking_number_to_driver_applications.rb
db/schema.rb
lib/mi_bridges/driver.rb
lib/mi_bridges/driver/services/find_tracking_number.rb
lib/mi_bridges/driver/view_track_and_print_your_application_page.rb
spec/fixtures/view_track_and_print_your_application.html
spec/lib/mi_bridges/driver/services/find_tracking_number_spec.rb

**WHY**: This is what MDHHS uses to track cases

Scrape Tracking number from post-submit page and save

---

app/controllers/medicaid/intro_location_controller.rb
app/steps/medicaid/intro_location.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/intro_location/edit.html.erb
config/initializers/extensions.rb
config/routes.rb
lib/mi_bridges.rb

* Every journey of a thousand miles begins with a single MEDICAID STEP

Add first Medicaid step

---

app/controllers/concerns/medicaid_flow.rb
app/controllers/medicaid/intro_location_controller.rb
app/controllers/medicaid/intro_location_help_controller.rb
app/steps/medicaid/step_navigation.rb
spec/controllers/medicaid/intro_location_controller_spec.rb
spec/controllers/medicaid/intro_location_help_controller_spec.rb

* This will be a blueprint for future skips

Add skip logic to medicaid controller

---

app/controllers/concerns/medicaid_flow.rb
app/controllers/medicaid/intro_location_controller.rb
app/steps/medicaid/insurance_current.rb
app/steps/medicaid/insurance_current_type.rb
app/steps/medicaid/intro_citizen.rb
db/migrate/20171012152903_add_yes_no_fields.rb
db/schema.rb

* Now, if you visit
`http://localhost:3000/steps/medicaid/intro-location` and click "yes" or
"no" it will save the data correctly.

Add database fields for yes/no views

---

app/controllers/medicaid/insurance_medical_expenses_controller.rb
app/steps/medicaid/income_job_number.rb
app/steps/medicaid/income_other_income_type.rb
app/steps/medicaid/income_self_employment.rb
app/steps/medicaid/intro_name.rb
app/steps/medicaid/tax_filing.rb
app/views/expenses_housing/edit.html.erb
app/views/medicaid/_next_step.html.erb
app/views/medicaid/income_job_number/edit.html.erb
app/views/medicaid/income_other_income_type/edit.html.erb
app/views/medicaid/insurance_current_type/edit.html.erb
app/views/medicaid/intro_citizen/edit.html.erb
app/views/medicaid/intro_name/edit.html.erb
db/migrate/20171012163307_add_input_fields_to_database.rb
db/schema.rb

* Name / gender fields
* Income types
* Job number
For now I am testing this all manually as I go. Hope is to get all steps functional and then write a large feature spec to cover it all

Hook up more pieces of medicaid flow to database

---

app/controllers/static_pages_controller.rb
app/controllers/steps_controller.rb

* Was broken because we weren't including the concern
* Also clear session vars for both types of flows on static pages so
that peoples' data is not overwritten

Fix steps controller

---

app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss
app/views/medicaid/intro_college/edit.html.erb
app/views/medicaid/tax_filing/edit.html.erb

Changes
=======
* Make Yes/No footer responsive
* Copy updates

Rc responsive styles

---

app/views/medicaid/confirmation/edit.html.erb

* Add illustration to confirmation page

Add celebration illustration to confirmation page

---

app/assets/stylesheets/michigan-benefits/atoms/_buttons.scss
app/views/medicaid/_next_step.html.erb
app/views/medicaid/amounts_overview/edit.html.erb
app/views/medicaid/confirmation/edit.html.erb
app/views/medicaid/contact_email/edit.html.erb
app/views/medicaid/contact_phone/edit.html.erb
app/views/medicaid/contact_social_security/edit.html.erb
app/views/medicaid/contact_text_messages/edit.html.erb
app/views/medicaid/intro_caretaker_member/edit.html.erb
app/views/medicaid/intro_household/edit.html.erb
app/views/medicaid/intro_household_member/edit.html.erb
app/views/medicaid/intro_location_help/edit.html.erb
app/views/pages/medicaid/amounts_income_all_members.erb

* Add confirmation illustration and footer partial

Add confirmation illustration and footer partial

---

app/views/medicaid/contact_email/edit.html.erb
app/views/medicaid/contact_phone/edit.html.erb
app/views/medicaid/contact_ss_dob/edit.html.erb
app/views/medicaid/contact_text_messages/edit.html.erb
app/views/medicaid/health_disability/edit.html.erb
app/views/medicaid/income_job_number/edit.html.erb
app/views/medicaid/insurance_current/edit.html.erb
app/views/medicaid/insurance_current_type/edit.html.erb
app/views/medicaid/intro_caretaker_member/edit.html.erb
app/views/medicaid/intro_household_member/edit.html.erb
app/views/medicaid/tax_filing/edit.html.erb

Changes
=======
* Add `form-card__content` class to make html consistent across views with body content

Make html body consistent

---

app/steps/medicaid/contact_email.rb
spec/steps/medicaid/contact_email_spec.rb
spec/steps/medicaid/contact_social_security_spec.rb

Validate SSN and email format

---

app/views/pages/medicaid/upload_paperwork.html.erb
app/views/pages/medicaid/upload_paperwork_intro.html.erb

Changes
=======
* Add Intro paperwork view
* Add upload paperwork view

Upload paperwork pages

---

app/views/medicaid/contact/edit.html.erb
app/views/medicaid/contact_homeless/edit.html.erb
app/views/medicaid/contact_mailing_address/edit.html.erb
app/views/medicaid/health_disability/edit.html.erb
app/views/medicaid/health_pregnancy/edit.html.erb
app/views/medicaid/income_job/edit.html.erb
app/views/medicaid/income_other_income/edit.html.erb
app/views/medicaid/income_self_employment/edit.html.erb
app/views/medicaid/insurance_current/edit.html.erb
app/views/medicaid/insurance_medical_expenses/edit.html.erb
app/views/medicaid/intro_caretaker/edit.html.erb
app/views/medicaid/intro_college/edit.html.erb
app/views/medicaid/intro_household/edit.html.erb
app/views/medicaid/intro_household_member/edit.html.erb
app/views/medicaid/intro_location_help/edit.html.erb
app/views/medicaid/tax_filing/edit.html.erb

* Also removed trello links from other pages

Small copy updates for address pages

---

app/controllers/medicaid/amounts_expenses_controller.rb
app/steps/medicaid/amounts_expenses.rb
app/views/medicaid/amounts_expenses/edit.html.erb
db/migrate/20171016213538_add_self_employment_expenses_to_medicaid_applications.rb
db/schema.rb
spec/controllers/medicaid/amounts_expenses_controller_spec.rb
spec/steps/medicaid/amounts_expenses_spec.rb

**WHY**: people need to report these if they are self employed

Add field for self employment expenses

---

app/controllers/medicaid/intro_household_controller.rb
app/controllers/steps_controller.rb
app/steps/medicaid/intro_household.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/intro_household/edit.html.erb
app/views/steps/index.html.erb

* Going to add ability to add members next

Add intro view for household (medicaid)

---

app/views/medicaid/income_job/edit.html.erb
app/views/medicaid/income_other_income/edit.html.erb
app/views/medicaid/income_self_employment/edit.html.erb
app/views/medicaid/insurance_medical_expenses/edit.html.erb

Changes
=======
* Small copy updates on income pages - https://trello.com/c/p5uVwQC1/415-update-help-text-on-do-you-currently-have-a-job-question
* Add Medical Expenses subheader copy - https://trello.com/c/PI7fGlOh/450-medicaid-flow-change-copy-on-retroactive-coverage-screen

Rc copy updates

---

app/controllers/medicaid/amounts_income_controller.rb
app/controllers/medicaid/income_job_number_continued_controller.rb
app/controllers/medicaid/income_job_number_controller.rb
app/helpers/mb_form_builder.rb
app/steps/medicaid/amounts_income.rb
app/steps/medicaid/income_job_number.rb
app/steps/medicaid/income_job_number_continued.rb
app/views/medicaid/amounts_income/edit.html.erb
app/views/medicaid/income_job_number/edit.html.erb
app/views/medicaid/income_job_number_continued/edit.html.erb
db/migrate/20171018232711_change_employed_monthly_income_to_array.rb
db/migrate/20171018234005_remove_unused_columns.rb
db/schema.rb
spec/controllers/medicaid/amounts_income_controller_spec.rb
spec/controllers/medicaid/income_job_number_continued_spec.rb
spec/controllers/medicaid/income_job_number_controller_spec.rb
spec/features/medicaid_spec.rb

* People can have multiple jobs, now they can report income for each job
individually.

Add income inputs for each job

---

spec/controllers/medicaid/amounts_income_controller_spec.rb

* When running the full test suite, a style violation was noted.
Changes
=======
* Break a long line into a several shorter ones.

Minor style fix

---

app/controllers/medicaid/insurance_needed_controller.rb
app/controllers/medicaid/many_member_steps_controller.rb
app/helpers/mb_form_builder.rb
app/steps/medicaid/insurance_needed.rb
app/steps/medicaid/step_navigation.rb
app/views/layouts/step.html.erb
app/views/medicaid/insurance_needed/edit.html.erb
db/migrate/20171019162840_add_requesting_health_insurance_to_members.rb
db/schema.rb
spec/controllers/medicaid/insurance_needed_controller_spec.rb
spec/features/medicaid_spec.rb
spec/steps/medicaid/insurance_needed_spec.rb

* We only show this page for multi-member households
* Defaults to "yes" for all household members but can uncheck a person to indicate that they are not requesting health coverage
* Error if all members are unchecked:

Tell us who in your household needs health insurance.

---

app/views/medicaid/income_job/edit.html.erb
app/views/medicaid/income_self_employment/edit.html.erb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb

Changes
=======
* Update jobs/employment copy

Update copy around jobs/employment

---

app/controllers/medicaid/health_flint_water_crisis_confirmation_controller.rb
app/controllers/medicaid/health_flint_water_crisis_controller.rb
app/steps/medicaid/health_flint_water_crisis.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/health_flint_water_crisis/edit.html.erb
app/views/medicaid/health_flint_water_crisis_confirmation/edit.html.erb
config/locales/en.yml
db/migrate/20171023164005_add_flint_water_crisis_to_medicaid_applications.rb
db/schema.rb
spec/controllers/medicaid/health_flint_water_crisis_confirmation_controller_spec.rb
spec/controllers/medicaid/health_flint_water_crisis_controller_spec.rb
spec/controllers/medicaid/health_pregnancy_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

Add Flint water crisis questions

---

app/views/medicaid/intro_name/edit.html.erb

* Add illustration to introduction page
* https://trello.com/c/Q8WGUw5b/412-medicaid-flow-include-illustration-voiceover-text-on-the-lets-start-with-some-information-about-you

Add introduction illustration

---

app/views/medicaid/intro_household/edit.html.erb

* Add greeting one the first page after the introduction.
* https://trello.com/c/B4hbs5K7/411-medicaid-flow-on-the-page-following-the-introduction-greet-the-user-with-their-first-name-above-the-question-title
* NOTE: this needs to be made dynamic before being merged in.

Add greeting after introduction

---

app/controllers/medicaid/health_pregnancy_controller.rb
app/controllers/medicaid/income_job_controller.rb
app/controllers/medicaid/income_self_employment_controller.rb
app/controllers/medicaid/intro_college_controller.rb

...to reduce code duplication.

Refactor update function for single member to use after_successful_update_hook

---

app/views/medicaid/income_job/edit.html.erb

* https://trello.com/c/p5uVwQC1/415-update-help-text-on-do-you-currently-have-a-job-question

Update Current Income subheader copy

---

app/controllers/document_guide_controller.rb
app/controllers/expenses_introduction_controller.rb
app/controllers/introduction_complete_controller.rb
app/controllers/medicaid/health_flint_water_crisis_confirmation_controller.rb
app/controllers/steps_controller.rb
app/steps/medicaid/citizen_member.rb
lib/mi_bridges/errors.rb
spec/controllers/steps_controller_spec.rb

... with a descriptive reason as to WHAT the step should be.
Also update the controllers to override the step_class with NullStep when
necessary.

Instead of defaulting to a NullStep, raise error

---

app/controllers/medicaid/health_disability_controller.rb
app/controllers/medicaid/health_disability_member_controller.rb
app/steps/medicaid/health_disability.rb
app/steps/medicaid/health_disability_member.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/health_disability/edit.html.erb
app/views/medicaid/health_disability_member/edit.html.erb
config/locales/en.yml
db/migrate/20171026150119_rename_disabled_to_anyone_disabled.rb
db/schema.rb
spec/controllers/medicaid/health_disability_controller_spec.rb
spec/controllers/medicaid/health_disability_member_controller_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

When asking a household of multiple members the question regarding
disabilities will now ask IF and WHO is disabled in the household.

Question re: disabilities open to multiple members

---

app/views/medicaid/amounts_income/edit.html.erb
app/views/medicaid/income_job/edit.html.erb
app/views/medicaid/income_job_number_member/edit.html.erb
app/views/success/edit.html.erb

- Update copy on Employment Amounts and Success pages
- https://trello.com/c/alBxXAui/519-copy-update-employment-amount-add-help-text-before-taxes-not-take-home-pay
- https://trello.com/c/jrp8tGqe/510-copy-update-your-county-will-provide-you-with-a-list-of-documents-that-you-need-to-submit-to-verify-your-eligibility

Copy updates based on office feedback

---

app/views/income_change_explanation/edit.html.erb
app/views/medicaid/income_job_number_member/edit.html.erb

* https://trello.com/c/zx8088zU/505-fix-security-footer

Add closing tags to fix security footer bug

---

app/controllers/medicaid/amounts_expenses_controller.rb
app/controllers/medicaid/expenses_alimony_member_controller.rb
app/steps/medicaid/expenses_alimony.rb
app/steps/medicaid/expenses_alimony_member.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/amounts_expenses/edit.html.erb
app/views/medicaid/expenses_alimony/edit.html.erb
app/views/medicaid/expenses_alimony_member/edit.html.erb
config/locales/en.yml
db/migrate/20171027185101_rename_pay_child_support_to_anyone_pay_child_support.rb
db/schema.rb
spec/controllers/medicaid/amounts_expenses_controller_spec.rb
spec/controllers/medicaid/expenses_alimony_controller_spec.rb
spec/controllers/medicaid/expenses_alimony_member_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

... ask who in the household is paying alimony, child support, arrears.

If someone pays alimony/child support/etc, ask who

---

app/dashboards/snap_application_dashboard.rb
spec/controllers/admin/snap_application_controller_spec.rb

Change some fields to NOT be searchable so that the rest of the fields
will work.
Add some (regression) tests

Fix the snap application search

---

app/controllers/medicaid/income_other_income_controller.rb
app/controllers/medicaid/income_other_income_member_controller.rb
app/steps/medicaid/income_other_income_member.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/income_other_income_member/edit.html.erb
db/migrate/20171027185102_add_other_income_to_members.rb
db/schema.rb
spec/controllers/medicaid/income_other_income_controller_spec.rb
spec/controllers/medicaid/income_other_income_member_controller_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/steps/medicaid/income_other_income_member_spec.rb

* Adds page with checkboxes to indicate *who* has other income
* next up is to indicate what type of other income for each member

Part II: "other income" for multi member flow

---

app/controllers/medicaid/intro_caretaker_controller.rb
app/controllers/medicaid/intro_caretaker_member_controller.rb
app/models/medicaid_application.rb
app/steps/medicaid/intro_caretaker.rb
app/steps/medicaid/intro_caretaker_member.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/intro_caretaker/edit.html.erb
app/views/medicaid/intro_caretaker_member/edit.html.erb
db/migrate/20171031203213_add_caretaker_or_parent_to_members.rb
db/migrate/20171031203404_rename_caretaker_or_parent_to_anyone_caretaker_or_parent.rb
db/schema.rb
spec/controllers/medicaid/intro_caretaker_controller_spec.rb
spec/controllers/medicaid/intro_caretaker_member_controller_spec.rb
spec/controllers/medicaid/intro_citizen_member_controller_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/steps/medicaid/intro_caretaker_member_spec.rb

Add caretaker or parent questions into multi-member flow

---

app/controllers/medicaid/legal_agreement_controller.rb
app/steps/medicaid/legal_agreement.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/legal_agreement/edit.html.erb
db/migrate/20171031220756_add_consent_to_terms_to_medicaid_applications.rb
db/schema.rb
spec/controllers/medicaid/contact_social_security_controller_spec.rb
spec/controllers/medicaid/legal_agreement_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb

Add legal agreement consent step to Medicaid flow

---

app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss
app/assets/stylesheets/michigan-benefits/organisms/_main-footer.scss
app/assets/stylesheets/michigan-benefits/organisms/_step-header.scss
app/controllers/medicaid_steps_controller.rb
app/controllers/snap_steps_controller.rb
app/controllers/steps_controller.rb
app/models/medicaid_application.rb
app/models/snap_application.rb
app/views/layouts/step.html.erb
app/views/shared/_footer.html.erb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/snap_application_with_minimal_info_spec.rb

- Center page title
- Add "Back" copy to make back button more clear
- Move application title (e.g., Medicaid Application) to footer
- https://trello.com/c/HZYSIubX/511-when-i-need-to-navigate-back-in-the-application-i-want-the-back-button-to-be-more-visible

Update header nav

---

app/controllers/medicaid/sign_and_submit_controller.rb
app/steps/medicaid/sign_and_submit.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/_next_step.html.erb
app/views/medicaid/sign_and_submit/edit.html.erb
db/migrate/20171101005455_add_signature_to_medicaid_application.rb
db/schema.rb
spec/controllers/medicaid/legal_agreement_controller_spec.rb
spec/controllers/medicaid/sign_and_submit_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb

Add sign and submit step to Medicaid flow

---

app/services/ssn_migrater.rb
lib/tasks/one_offs.rake
spec/services/ssn_migrater_spec.rb

Add one-off rake task to convert ssn to last_four_ssn

---

app/controllers/medicaid/contact_social_security_controller.rb
app/controllers/medicaid_steps_controller.rb
app/models/concerns/social_security_number.rb
app/models/member.rb
app/steps/concerns/step_social_security_number.rb
app/steps/household_add_member.rb
app/steps/medicaid/contact_social_security.rb
app/steps/medicaid/insurance_current_type.rb
app/steps/medicaid/insurance_needed.rb
app/steps/personal_detail.rb
app/views/medicaid/amounts_income/edit.html.erb
app/views/medicaid/contact_social_security/edit.html.erb
app/views/medicaid/contact_ss_dob/edit.html.erb
app/views/medicaid/income_job_number_member/_header.html.erb
app/views/medicaid/income_job_number_member/edit.html.erb
config/locales/en.yml
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/features/member_not_citizen_spec.rb
spec/models/member_spec.rb
spec/rails_helper.rb
spec/steps/medicaid/contact_social_security_spec.rb
spec/support/medicaid_application_form_helper.rb

* As a multi-member Medicaid applicant, I want to be able in input
Social Security and DOB for each household member.
* Finishes #152457770

Medicaid MM: Last 4 SSN and DOB for all household members

---

db/seeds.rb

And add an unemployment income value for further testing.
This is a pretty rinky-dink PR since Christa took care of all the SSN seed updates :)

Add unemployment income data to medicaid application

---

config/application.rb
spec/controllers/income_employment_status_controller_spec.rb

* So they don't show up in logs

Filter `last_four_ssn` parameters

---

CONTRIBUTING.md

**WHY**:
So people know how to create admin accounts.
Finishes #152446453

Add docs for admin dashboard / admin accounts

---

app/controllers/medicaid/contact_mailing_address_controller.rb
app/steps/medicaid/contact_home_address.rb
app/views/medicaid/contact_home_address/edit.html.erb
db/migrate/20171106225616_add_mailing_address_same_as_residental_address_to_medicaid_application.rb
db/schema.rb
spec/controllers/medicaid/contact_mailing_address_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb

Indicate if mailing address same as residential

---

app/views/medicaid/income_job/edit.html.erb
app/views/medicaid/income_job_number_member/edit.html.erb

* https://trello.com/c/nL9ANXqf/119-employment-as-a-client-i-need-to-know-that-temporary-jobs-count-as-employment
* add "temporary" to employment description

Small copy update

---

CONTRIBUTING.md
README.md

Update Contributing with Tracker info

---

app/controllers/medicaid/intro_marital_status_member_controller.rb
app/steps/medicaid/intro_marital_status_member.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/intro_marital_status_member/edit.html.erb
spec/controllers/medicaid/intro_marital_status_member_controller_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/steps/medicaid/intro_marital_status_member_spec.rb

Indicate *who* is married in Medicaid flow

---

app/views/medicaid/expenses_alimony_member/edit.html.erb
app/views/medicaid/expenses_student_loan_member/edit.html.erb
app/views/medicaid/health_disability_member/edit.html.erb
app/views/medicaid/health_pregnancy_member/edit.html.erb
app/views/medicaid/income_other_income_member/edit.html.erb
app/views/medicaid/income_self_employment_member/edit.html.erb
app/views/medicaid/insurance_current_member/edit.html.erb
app/views/medicaid/insurance_needed/edit.html.erb
app/views/medicaid/intro_caretaker_member/edit.html.erb
app/views/medicaid/intro_citizen_member/edit.html.erb
app/views/medicaid/intro_college_member/edit.html.erb

Move validation errors to below inputs

---

app/steps/contact_confirm_phone_number.rb
app/steps/contact_information.rb
app/steps/medicaid/contact_email.rb
app/steps/medicaid/contact_phone.rb
app/steps/medicaid/insurance_current_member.rb
app/steps/medicaid/insurance_current_type.rb
app/steps/medicaid/sign_and_submit.rb
app/steps/sign_and_submit.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/steps/medicaid/contact_phone_spec.rb

- https://trello.com/c/zDcx0QSF/98-validations-and-help-text-audit#comment-5a0399a17de3e695c60f317a

Update validation copy

---

app/controllers/medicaid/intro_marital_status_indicate_spouse_controller.rb
app/models/member.rb
app/views/medicaid/intro_marital_status_indicate_spouse/edit.html.erb
spec/models/member_spec.rb

Do not show unmarried members in spouse options

---

app/dashboards/snap_application_dashboard.rb
db/seeds.rb

* Fixes broken seeds and creates a local Admin User
* Adds office_location to admin view for SnapApplication!
Fixes this bug: https://www.pivotaltracker.com/story/show/152566845

Ch admin office location not shown

---

app/controllers/medicaid/amounts_expenses_controller.rb
app/controllers/medicaid/expenses_alimony_controller.rb
app/models/member.rb
app/steps/medicaid/amounts_expenses.rb
app/views/medicaid/amounts_expenses/edit.html.erb
config/locales/en.yml
db/migrate/20171109193950_add_expense_amounts_to_members.rb
db/schema.rb
spec/controllers/medicaid/amounts_expenses_controller_spec.rb
spec/controllers/medicaid/expenses_alimony_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/steps/medicaid/amounts_expenses_spec.rb

* [Finishes #152510521]
* We did not add any validations to these inputs, just changed the
wording and design and in some cases moved the field to the member class

Update `amounts-expenses` page for multi-member flow

---

app/controllers/admin/application_controller.rb

[Finishes #152367850]
Signed-off-by: Joel Oliveira <joel.oliveira@gmail.com>

Tag logging statements in admin with user email

---

app/helpers/mb_form_builder.rb
app/steps/medicaid/amounts_income.rb
app/views/medicaid/amounts_income/edit.html.erb
db/migrate/20171109155919_add_employer_information_to_members.rb
db/schema.rb
spec/controllers/medicaid/amounts_income_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/steps/medicaid/amounts_income_spec.rb

For however many jobs a person has we must ask who the employer is, and
how often they are paid by that company.
* Change the select field type in the form builder to allow for multiple
values in the database

Ask for employer name + pay frequency for each job

---

app/dashboards/snap_application_dashboard.rb

From application#show
https://www.pivotaltracker.com/story/show/152566845
[Fixes #152566845]

Move office location to SNAP application index

---

app/steps/medicaid/step_navigation.rb
app/views/medicaid/paperwork/edit.html.erb
app/views/medicaid/paperwork_guide/edit.html.erb
spec/controllers/medicaid/contact_social_security_controller_spec.rb
spec/controllers/medicaid/paperwork_controller_spec.rb
spec/controllers/medicaid/sign_and_submit_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* For Medicaid flow, I want to submit paperwork before signing the legal
agreement
* [Finishes #152768357]
* https://www.pivotaltracker.com/story/show/152768357

Submit paperwork before Rights & Responsibilities

---

app/models/member.rb
app/steps/medicaid/insurance_current_type.rb
app/views/medicaid/insurance_current_type/edit.html.erb

* Use a method in the step to show radio options
* [Finishes #152621191]
* https://www.pivotaltracker.com/story/show/152621191

Add Medicare as current insurance type option

---

bin/release

Four sets of eyes is enough to auto-merge, right??

Bg everyone release script changes

---

app/controllers/medicaid/contact_introduction_controller.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/amounts_overview/edit.html.erb
app/views/medicaid/contact_introduction/edit.html.erb
spec/controllers/medicaid/amounts_expenses_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* Before "contact" section
* [Finishes #152656451]

Add `steps/medicaid/contact-introduction` page

---

app/controllers/medicaid/income_introduction_controller.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/income_introduction/edit.html.erb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* [Finishes #152656208]
* `/steps/medicaid/income-introduction`

Add income & expenses intro page

---

app/controllers/medicaid/paperwork_and_legal_introduction_controller.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/paperwork_and_legal_introduction/edit.html.erb
spec/controllers/medicaid/contact_social_security_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* `/steps/medicaid/paperwork-and-legal-introduction`
* [Finishes #152657089]

Add paperwork and legal introduction page

---

app/controllers/medicaid/tax_claimed_as_dependent_controller.rb
app/steps/medicaid/step_navigation.rb
app/steps/medicaid/tax_claimed_as_dependent.rb
app/views/medicaid/tax_claimed_as_dependent/edit.html.erb
db/migrate/20171115000034_add_claimed_as_dependent_to_member.rb
db/schema.rb
spec/controllers/medicaid/tax_claimed_as_dependent_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

https://www.pivotaltracker.com/story/show/152453132
[Finishes #152453132]

Allow primary member to say if claimed as dependent

---

app/controllers/medicaid/tax_filing_with_household_members_controller.rb
app/steps/medicaid/step_navigation.rb
app/steps/medicaid/tax_filing_with_household_members.rb
app/views/medicaid/tax_filing_with_household_members/edit.html.erb
db/migrate/20171115005618_add_filing_taxes_with_household_members_to_medicaid_applications.rb
db/schema.rb
spec/controllers/medicaid/tax_claimed_as_dependent_controller_spec.rb
spec/controllers/medicaid/tax_filing_with_household_members_controller_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

[Finishes #152601325]
https://www.pivotaltracker.com/story/show/152601325

Ask if applicant is filing taxes with any household members

---

app/controllers/medicaid/tax_filing_with_household_members_member_controller.rb
app/steps/medicaid/step_navigation.rb
app/steps/medicaid/tax_filing_with_household_members_member.rb
app/views/medicaid/tax_filing_with_household_members_member/edit.html.erb
db/migrate/20171115014535_add_filing_taxes_with_primary_member_to_members.rb
db/schema.rb
spec/controllers/medicaid/tax_filing_with_household_members_controller_spec.rb
spec/controllers/medicaid/tax_filing_with_household_members_member_controller_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* Only ask IF:
- multi-member application
- plan on filing taxes
- plan on filing with other household members
* [Finishes #152562742]
* https://www.pivotaltracker.com/story/show/152562742
validation:

Specify which members I file taxes with

---

app/controllers/medicaid/tax_introduction_controller.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/health_flint_water_crisis_confirmation/edit.html.erb
app/views/medicaid/tax_introduction/edit.html.erb
config/locales/en.yml
spec/controllers/medicaid/health_flint_water_crisis_confirmation_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* Breather page
* [Finishes #152656335]

Add intro page for Medicaid tax section

---

circle.yml

- found [a great article](http://adarsh.io/automatically-check-gem-vulnerabilities-in-circle-ci/) by someone cool named Adarsh Pandit
- it had excellent details on how to run bundle audits on Circle CI
- decided to implement Adarsh's recommendations
- pretty happy that his article existed
- thank you @adarsh!
[Finishes #152771780]

Run bundle audit on Circle CI

---

app/views/medicaid/health_flint_water_crisis_confirmation/edit.html.erb

Fix small HTML issue

---

app/models/medicaid_application_member_attributes.rb
app/models/member.rb
spec/models/medicaid_application_member_attributes_spec.rb

* We do not require birthdays in the 1426 flow, so we need to write PDF
filling logic that works if there is no birthday present
* Part of https://www.pivotaltracker.com/story/show/152727221

Account for `nil` birthday possibilities for 1426

---

app/views/medicaid/income_job/edit.html.erb

Update employment help text

---

app/controllers/admin/addresses_controller.rb
app/dashboards/address_dashboard.rb
config/routes.rb

[Finishes #152855577]
Adding an address dashboard fixes the bug where viewing a Medicaid
Application record in the admin 500'd out.

Add address dashboard

---

app/controllers/medicaid/health_pregnancy_member_controller.rb
app/steps/medicaid/health_pregnancy_member.rb

* These were sharing the same step but almost none of the logic
[#152942073]

Decouple HealthPregnancy and HealthPregnancyMember

---

app/models/member.rb
spec/models/member_spec.rb

- checks to ensure that any set of choices for the other_income_types
array are a subset of predefined options
- adds an error if not
- I don't know ruby and patched together advice from the internet.
So please let me know how I can do better

Validate other_income_types

---

app/assets/stylesheets/atoms/_typography.scss

- https://trello.com/c/yt2UVE8V/124-update-link-hover-color

Change link hover color to match current color pallet

---

Gemfile
Gemfile.lock
circle.yml

Add tracker-git to mark stories as "Delivered" after staging deploy

---

Gemfile.lock

Update tracker-git to restrict to specified branches and commits

---

app/controllers/introduction_complete_controller.rb
app/controllers/medicaid/contact_introduction_controller.rb
app/controllers/medicaid/health_introduction_controller.rb
app/controllers/medicaid/income_introduction_controller.rb
app/controllers/medicaid/paperwork_and_legal_introduction_controller.rb
app/controllers/medicaid/tax_introduction_controller.rb
app/controllers/medicaid/welcome_controller.rb
app/steps/medicaid/step_navigation.rb
app/views/medicaid/health_introduction/edit.html.erb
spec/controllers/medicaid/intro_caretaker_member_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb

* [Finishes #152655651]
* This is using less inheritance than other breather pages and can serve
as a model for the refactor described in
https://www.pivotaltracker.com/story/show/152867437 once this is
finalized (to follow)

Add health introduction breather page

---

app/assets/stylesheets/atoms/_form-elements.scss

Outlines for focused radio and checkbox inputs

---

CONTRIBUTING.md

Adds some macOS-specific dependencies I ran into while installing on a completely fresh version of macOS.

Add some instructions for macOS setup

---

app/decorators/member_decorator.rb
app/models/extra_member_attributes.rb
app/models/medicaid_application_member_attributes.rb
app/models/member.rb
app/models/verification_document.rb
db/migrate/20171121231237_remove_birthday_from_medicaid_applications.rb

* Perhaps we should store view-specific methods like this in decorators?
cc @hartsick  @luigi

Refactor: move `formatted_birthday` to decorator

---

app/steps/contact_confirm_phone_number.rb
app/steps/contact_information.rb
app/steps/medicaid/contact_phone.rb
app/views/contact_information/edit.html.erb
app/views/medicaid/contact_phone/edit.html.erb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/steps/medicaid/contact_phone_spec.rb

* Makes phone number a non-required field.
* [Finishes #152981586]
* Also added 'optional' text to inputs to be consistent with other optional inputs

Remove validations on phone number for SNAP/Medicaid

---

Gemfile
Gemfile.lock
circle.yml

https://www.pivotaltracker.com/story/show/153103465
[Finishes #153103465]

Remove auto-delivery for stories when deployed to staging env

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/atoms/_form-elements.scss
app/assets/stylesheets/michigan-benefits/atoms/_typography.scss
app/helpers/mb_form_builder.rb
app/views/contact_confirm_phone_number/edit.html.erb
app/views/income_details_per_member/_header.html.erb
app/views/income_details_per_member/_household_member_group.html.erb
app/views/income_details_per_member/edit.html.erb
app/views/medicaid/insurance_current_member/edit.html.erb
app/views/medicaid/tax_filing_with_household_members_relationship/edit.html.erb
config/locales/en.yml
spec/features/medicaid_application_with_multiple_members_spec.rb

* Showing how I will tackle the rest of
https://www.pivotaltracker.com/story/show/152761627 before going through
each page, since it will require a lot of manual work.
* Any objections to this approach?

WIP add questions as `legend ` elements in fieldsets

---

app/helpers/mb_form_builder.rb
app/views/contact_information/edit.html.erb
app/views/medicaid/contact_phone/edit.html.erb
app/views/medicaid/contact_text_messages/edit.html.erb
spec/helpers/mb_form_builder_spec.rb

This is currently failing on purpose. It's unclear to me what would be the right way to test MbFormBuilder content.  I'd appreciate some help with pointing me in the right direction for testing.

+1 phone prefix via new phone_number_field

---

app/steps/step_navigation.rb
app/views/document_guide/edit.html.erb
app/views/medicaid/paperwork/edit.html.erb
app/views/medicaid/paperwork_guide/edit.html.erb
spec/controllers/general_anything_else_controller_spec.rb
spec/controllers/sign_and_submit_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/features/snap_application_with_maximum_info_spec.rb
spec/features/snap_application_with_minimal_info_spec.rb

* Documents before legal / signing
* Also 2 small copy changes per ticket
* [Finishes #152768809]
https://www.pivotaltracker.com/story/show/152768809

Change step order for SNAP flow

---

Gemfile
Gemfile.lock
app/controllers/admin/application_controller.rb
app/controllers/application_controller.rb
config/initializers/lograge.rb

* To help with debugging
* Using https://github.com/roidrage/lograge, which also makes Rails logs
easier to read.
* Example output:
```
method=PUT path=/steps/medicaid/intro-name format=html controller=Medicaid::IntroNameController action=update status=302 duration=22.50 view=0.00 db=5.76 location=http://localhost:3000/steps/medicaid/intro-household application_id=4 application_type=MedicaidApplication
```
[Finishes #152975087]
https://www.pivotaltracker.com/story/show/152975087

Add current application id and type to logs

---

config/environments/development.rb
config/environments/test.rb

* Fail tests if translations are not found
* Fail to render page in development if translations are not found
[#153101043]

Translation missing errors

---

DEPLOYING.md
bin/release
circle.yml

* CI auto deploys production branch to pre-production
* Release script promotes pre-production instance instead of staging
[#152985452]

Pre-production instance set up

---

Brewfile
bin/release
bin/setup

Manage brew dependencies via Brewfile
[#152619811]
Do not show env var diff if env vars are the same
[#152897582]

Release script changes

---

bin/release

Only show diff for buildpacks if there is a diff

---

bin/release

Reindentation caused release script to break.

---

Brewfile
app/controllers/income_additional_sources_controller.rb
app/views/income_additional_sources/edit.html.erb
config/environments/production.rb
config/environments/staging.rb
spec/controllers/income_additional_sources_controller_spec.rb

* Add helper text to show additional income is optional
* Refactor income_additional_sources_controller
* Add unit test coverage
* Rubocop changes from previous commits

Additional income none

---

app/controllers/medicaid/income_job_number_continued_controller.rb
app/controllers/medicaid/income_job_number_controller.rb

Refactor to use update_application

---

app/views/medicaid/income_job_number_member/edit.html.erb
spec/helpers/mb_form_builder_spec.rb

* This way we can differentiate between when jobs were entered or not.
* Add form builder spec for this change
[#153069646]

0 instead of nil for # of jobs

---

.env.sample
Gemfile
Gemfile.lock
config/initializers/slack.rb
config/secrets.yml
lib/summarizer/application_summary.rb
lib/tasks/slack.rake
spec/lib/summarizer/application_summary_spec.rb

[PAIR] Initial daily summary for our Slack integration

---

lib/mi_bridges/driver/base_page.rb
lib/mi_bridges/driver/job_income_information_page.rb
lib/mi_bridges/driver/people_listed_page.rb
lib/mi_bridges/driver/personal_information_page.rb

* Including citizenship, ssn
Part of [#153486893], updated through MiBridges::Driver::MoneyOtherSourcesPage, with id: 13

Fill in non-required fields that we're able to fill in

---

app/services/update_member_data.rb
spec/services/update_member_data_spec.rb

Prevent rake task from breaking with  nil names

---

app/controllers/household_members_overview_controller.rb
app/helpers/steps_helper.rb
app/steps/household_members_overview.rb
app/views/household_members_overview/edit.html.erb

* Make the way we show names more consistent!
* [Finishes #153189719]
https://www.pivotaltracker.com/story/show/153189719

Update capitalization usage for names throughout app

---

db/migrate/20171212175033_remove_employment_fields_for_medicaid_applications.rb
db/schema.rb

Removed unused employer array fields from Medicaid applications members.

---

app/helpers/mb_form_builder.rb
app/views/expenses_additional/edit.html.erb
app/views/household_more_info_per_member/edit.html.erb
app/views/medicaid/contact_social_security/edit.html.erb
app/views/medicaid/contact_text_messages/edit.html.erb
app/views/medicaid/expenses_alimony_member/edit.html.erb
app/views/medicaid/expenses_student_loan_member/edit.html.erb
app/views/medicaid/health_disability_member/edit.html.erb
app/views/medicaid/health_pregnancy_member/edit.html.erb
app/views/medicaid/income_job_number_member/edit.html.erb
app/views/medicaid/income_other_income_member/edit.html.erb
app/views/medicaid/income_self_employment_member/edit.html.erb
app/views/medicaid/insurance_needed/edit.html.erb
app/views/medicaid/intro_caretaker_member/edit.html.erb
app/views/medicaid/intro_citizen_member/edit.html.erb
app/views/medicaid/intro_college_member/edit.html.erb
app/views/medicaid/intro_marital_status_member/edit.html.erb
app/views/medicaid/tax_filing_with_household_members_member/edit.html.erb
config/locales/en.yml
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/helpers/mb_form_builder_spec.rb

- Manually checked views and ensured each fieldset has a legend or is
converted to a div.
- Added tests for mb_form_builder to ensure that fieldsets with legends
exist where appropriate
- Added translations for some page legends & titles
[Finishes #152761627]
Signed-off-by: Luigi Ray-Montañez <luigi@codeforamerica.org>

[PAIR] All fieldsets have legends

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/atoms/_buttons.scss
app/assets/stylesheets/michigan-benefits/atoms/_variables.scss
app/views/legal_agreement/edit.html.erb
app/views/medicaid/legal_agreement/edit.html.erb
app/views/shared/_terms.html.erb

* Fix invalid HTML as detected by WAVE
* Fix contrast issue
* Contrast issue brought up issue with our overrides, which was that we
load our overrides last in the manifest file so that they take
precedent, which means that our variable overrides were not loaded until
after all of the base styles. Now, we are loading our variable overrides
above the base styles so that the base styles that use variables are
using our overrides rather than the original colors.
* [Finishes #153764205]
* [Finishes #153764168]

Update legal agreement pages for a11y

---

spec/helpers/mb_form_builder_spec.rb

Sorry, don't know how I missed these in an earlier PR.

Rubocop fixes

---

app/lib/mi_bridges/driver/base_page.rb
app/lib/mi_bridges/driver/household_member_questions_page.rb
app/lib/mi_bridges/driver/relationship_information_page.rb

* Before, we were defaulting to primary member if anyone was disabled
* Now, we check the box for each disabled member.
* [Finishes #153569244]
https://www.pivotaltracker.com/story/show/153569244

Check "disabled" box for each disabled member

---

app/lib/mi_bridges/driver/school_enrollment_page.rb
spec/features/mi_bridges_driving_spec.rb

* On SchoolEnrollmentPage, match each member from
SNAP application.
* Fix failure in Driving Spec from earlier PR.
[#153565851]
https://www.pivotaltracker.com/story/show/153565851

[PAIR] MIBridges: Fill in school data for each member.

---

app/lib/mi_bridges/driver.rb
spec/lib/mi_bridges/driver_spec.rb

* This is mostly mocking and stubbing.
* [#153527657]

Add unit test for MiBridges driver

---

app/assets/stylesheets/templates/_homepage.scss

Pointed out by @racheledelman !
[#154034941]

Reindent CSS and remove empty selector

---

app/helpers/mb_form_builder.rb
spec/helpers/mb_form_builder_spec.rb

* Created method called aria_labelledby
* Moved __label id to the question instead of <label>
[#152814700]

[PAIR] Adds aria-labelledby support for mb_textarea + mb_select

---

app/models/new_dhs1171_pdf.rb
app/models/snap_application.rb
spec/models/snap_application_spec.rb

Add environment variable for new civilla form

---

app/lib/find_chrome.rb

* By doing this, we will not see the finding chrome text on every test
run

Find chrome executable on demand

---

bin/debug_prod
config/environments/production_debug.rb
config/secrets.yml

Sometimes we need to troubleshoot problems using production data. This script and related Rails environment allows us to connect to the remote production database using our local code to ease troubleshooting and keep data in the DB. It also doesn't leave environment variables from prod sitting around in our local sessions.
With great power comes great responsibility (and I'm open to not merging this into code base, but wanted to offer it as a point of discussion!). What do y'all think? @luigi @bengolder 
[#154448184]

Create script and environment for debugging with production data

---

config/initializers/twilio.rb

Need to set the credentials on staging too.
[Resolves #154097546]

Configure Twilio for staging environment

---

app/lib/feature.rb
app/lib/gate_keeper.rb
app/models/office_recipient.rb
app/models/snap_application.rb
app/views/layouts/application.html.erb
bin/release
bin/setup
spec/features/staging_warning_spec.rb
spec/lib/gate_keeper_spec.rb
spec/models/office_recipient_spec.rb

Opening this PR to give visibility as to what I'm working toward! Will update as I've got new commits ✨

Create demo site that mirrors production, but doesn't send applications

---

app/views/medicaid/amounts_expenses/edit.html.erb

- Rachel wrote some great copy.
- We copied and pasted the copy over the other copy of the copy.
- We commited.
- We succeeded.
This commit message is longer than the code change.
[Finishes #153883225]

Better indicate what self-employed expenses are.

---

app/views/household_more_info_per_member/edit.html.erb
config/locales/en.yml
spec/features/member_not_citizen_spec.rb

Previously we asked if they weren't. This surfaced a Rails bug (or misuse), but also pointed out that the question was confusing, anyway. So, we changed the copy.
[Fixes #154786875]

Ask SNAP applicants if they *are* a citizen

---

app/controllers/stats/numbers_controller.rb
app/services/median_time_to_complete_calculator.rb
app/views/stats/numbers/index.html.erb
spec/features/numbers_dashboard_spec.rb
spec/services/median_time_to_complete_calculcator_spec.rb

Add median time-to-complete to dashboard

---

Gemfile
Gemfile.lock
app/steps/medicaid/step_navigation.rb
app/steps/step_navigation.rb
app/views/document_guide/edit.html.erb
app/views/documents/edit.html.erb
app/views/medicaid/paperwork/edit.html.erb
app/views/medicaid/paperwork_and_legal_introduction/edit.html.erb
app/views/medicaid/paperwork_guide/edit.html.erb
spec/controllers/general_anything_else_controller_spec.rb
spec/controllers/medicaid/paperwork_controller_spec.rb
spec/controllers/medicaid/sign_and_submit_controller_spec.rb
spec/controllers/sign_and_submit_controller_spec.rb
spec/features/medicaid_application_with_maximum_info_spec.rb
spec/features/medicaid_application_with_minimal_info_spec.rb
spec/features/medicaid_application_with_multiple_members_spec.rb
spec/features/snap_application_with_maximum_info_spec.rb
spec/features/snap_application_with_minimal_info_spec.rb

- we now submit docs before signing and submitting
- differentiate content for tablet vs desktop
[Finishes #154671167]

Update end-of-app page ordering

---

app/assets/stylesheets/michigan-benefits/atoms/_typography.scss
app/controllers/household_remove_member_controller.rb
app/controllers/medicaid/intro_household_remove_member_controller.rb
app/steps/household_remove_member.rb
app/steps/medicaid/intro_household_remove_member.rb
app/steps/medicaid/step_navigation.rb
app/steps/step_navigation.rb
app/views/household_members_overview/edit.html.erb
app/views/medicaid/intro_household/edit.html.erb
spec/controllers/household_remove_member_controller_spec.rb
spec/controllers/medicaid/intro_household_remove_member_controller_spec.rb

* In both SNAP and Medicaid flows
* Adds a controller and step for each flow
* Uses `aria-labelledby` on the remove link
https://www.pivotaltracker.com/story/show/154656640

Add a remove link for household members

---

app/assets/javascripts/upload_setup.js
app/controllers/messages_controller.rb
app/jobs/sms_message_job.rb
app/views/documents/edit.html.erb
app/views/medicaid/paperwork/edit.html.erb
app/views/messages/new.html.erb
app/views/shared/_uploadable_uploading.html.erb
db/migrate/20180213225556_add_screenshots_to_messages.rb
db/schema.rb
spec/features/messages_spec.rb
spec/support/fake_twilio_client.rb

Caseworker can upload screenshots to message system

---

app/services/median_time_to_complete_calculator.rb
spec/services/median_time_to_complete_calculcator_spec.rb

Add seconds to median times in numbers dashboard

---

app/controllers/messages_controller.rb
app/helpers/mb_form_builder.rb
app/models/message.rb
app/views/messages/new.html.erb
config/secrets.yml
spec/features/messages_spec.rb
spec/helpers/mb_form_builder_spec.rb
spec/support/feature_helper.rb

Add custom phone number field to caseworker message tool

---

app/controllers/forms_controller.rb
app/controllers/integrated/introduce_yourself_controller.rb
app/controllers/integrated/living_situation_controller.rb
app/forms/form_navigation.rb
app/forms/living_situation_form.rb
app/models/common_application.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/living_situation/edit.html.erb
db/migrate/20180228214136_add_living_situation_to_common_application.rb
db/schema.rb
spec/controllers/integrated/living_situation_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Indicate living situation

---

app/pdf_components/assistance_application_form.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Add sixth member and more to PDF "Notes" page

---

app/helpers/mb_form_builder.rb
app/models/common_application.rb
app/views/integrated/household_members_overview/edit.html.erb
spec/features/integrated_application_with_single_member_spec.rb

[#155522444]
Signed-off-by: Christa Harstock <christa@codeforamerica.org>
Co-authored-by: Christa Harstock <christa@codeforamerica.org>

Update copy when application has stable housing.

---

app/dashboards/member_dashboard.rb
bin/debug_prod

Stops spring and prevents spring from being run when connecting to production database.
Also removes unused attribute from admin member dashboard. 
[#155641559]

Update production debugging script

---

.rubocop.yml
app/controllers/integrated/buy_and_prepare_food_with_other_person_controller.rb
app/controllers/integrated/food_assistance_controller.rb
app/controllers/integrated/introduce_yourself_controller.rb
app/controllers/integrated/living_situation_controller.rb
app/forms/buy_and_prepare_food_with_other_person_form.rb
app/forms/form_navigation.rb
app/helpers/mb_form_builder.rb
app/models/common_application.rb
app/models/household_member.rb
app/models/integrated/pdf_attributes.rb
app/pdf_components/food_assistance_supplement.rb
app/services/application_pdf_assembler.rb
app/views/integrated/buy_and_prepare_food_with_other_person/edit.html.erb
db/migrate/20180314145539_add_buy_and_prepare_food_with_to_household_member.rb
db/schema.rb
lib/generators/section/section_generator.rb
lib/generators/section/templates/form_controller.template.rb
lib/generators/section/templates/form_controller_spec.template.rb
spec/controllers/integrated/buy_and_prepare_food_with_other_person_controller_spec.rb
spec/controllers/integrated/food_assistance_controller_spec.rb
spec/controllers/integrated/introduce_yourself_controller_spec.rb
spec/controllers/integrated/living_situation_controller_spec.rb
spec/factories/household_members.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/helpers/mb_form_builder_spec.rb
spec/models/common_application_spec.rb
spec/pdf_components/food_assistance_supplement_spec.rb
spec/services/application_pdf_assembler_spec.rb

...ask them if they buy and prepare food together. This builds the SNAP household, and marks the related fields on the PDF.

If two members are applying for food assistance

---

app/controllers/forms_controller.rb
app/controllers/integrated/buy_and_prepare_food_separately_controller.rb
app/controllers/integrated/share_food_costs_with_household_controller.rb
app/forms/buy_and_prepare_food_separately_form.rb
app/forms/form.rb
app/forms/form_navigation.rb
app/forms/share_food_costs_with_household_form.rb
app/views/integrated/buy_and_prepare_food_separately/edit.html.erb
app/views/integrated/share_food_costs_with_household/edit.html.erb
db/migrate/20180314200722_add_all_share_food_costs_to_navigator.rb
db/schema.rb
spec/controllers/integrated/buy_and_prepare_food_separately_controller_spec.rb
spec/controllers/integrated/buy_and_prepare_food_with_other_person_controller_spec.rb
spec/controllers/integrated/food_assistance_controller_spec.rb
spec/controllers/integrated/share_food_costs_with_household_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/forms/form_spec.rb

Indicate household members who buy and prepare food separately

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/atoms/_card.scss
app/assets/stylesheets/michigan-benefits/atoms/_icons.scss
app/assets/stylesheets/michigan-benefits/atoms/_typography.scss
app/controllers/integrated/add_snap_member_controller.rb
app/controllers/integrated/remove_snap_member_controller.rb
app/controllers/integrated/review_food_assistance_members_controller.rb
app/forms/add_snap_member_form.rb
app/forms/form_navigation.rb
app/forms/remove_snap_member_form.rb
app/views/integrated/add_snap_member/edit.html.erb
app/views/integrated/review_food_assistance_members/edit.html.erb
spec/controllers/integrated/add_snap_member_controller_spec.rb
spec/controllers/integrated/remove_snap_member_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Also provide options to add and remove members from application.
[#155714372]
Signed-off-by: Christa Harstock <christa@codeforamerica.org>
Co-authored-by: Christa Harstock <christa@codeforamerica.org>

Show recap of Food Assistance household & application.

---

app/controllers/integrated/healthcare_controller.rb
app/controllers/integrated/introduce_yourself_controller.rb
app/forms/form_navigation.rb
app/forms/healthcare_form.rb
app/models/common_application.rb
app/models/household_member.rb
app/models/integrated/pdf_attributes.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/healthcare/edit.html.erb
db/migrate/20180320173759_add_requesting_healthcare_to_household_member.rb
db/schema.rb
spec/controllers/integrated/healthcare_controller_spec.rb
spec/controllers/integrated/introduce_yourself_controller_spec.rb
spec/factories/common_applications.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/common_application_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Allows user to select who in their household is applying for healthcare, and defaults them to applying for healthcare.
Also deletes some integration tests that seemed duplicative.

Apply for healthcare

---

app/controllers/integrated/include_anyone_else_on_taxes_controller.rb
app/forms/form_navigation.rb
app/forms/include_anyone_else_on_taxes_form.rb
app/views/integrated/include_anyone_else_on_taxes/edit.html.erb
db/migrate/20180320224323_add_anyone_else_on_tax_return_to_application_navigator.rb
db/schema.rb
spec/controllers/integrated/include_anyone_else_on_taxes_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

[Finishes #155716182]
Co-authored-by: Luigi Ray-Montanez <luigi@codeforamerica.org>

Indicate who else will be on my tax return

---

app/controllers/integrated/describe_tax_relationships_controller.rb
app/forms/describe_tax_relationships_form.rb
app/forms/form_navigation.rb
app/models/common_application.rb
app/models/household_member.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/describe_tax_relationships/edit.html.erb
db/migrate/20180321002715_add_tax_relationship_to_household_member.rb
db/schema.rb
spec/controllers/integrated/describe_tax_relationships_controller_spec.rb
spec/controllers/integrated/include_anyone_else_on_taxes_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/forms/describe_tax_relationships_form_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

https://www.pivotaltracker.com/story/show/155716327

Indicate how household members are included on tax return

---

app/controllers/integrated/tax_household_intro_controller.rb
app/forms/form_navigation.rb
app/views/integrated/tax_household_intro/edit.html.erb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

With placeholder text.
[Finishes #156045571]

Add introduction to tax questions

---

app/controllers/integrated/anyone_caretaker_controller.rb
app/controllers/integrated/describe_tax_relationships_controller.rb
app/controllers/integrated/multiple_members_controller.rb
app/controllers/integrated/who_is_caretaker_controller.rb
app/controllers/integrated/who_is_married_controller.rb
app/forms/anyone_caretaker_form.rb
app/forms/form_navigation.rb
app/forms/who_is_caretaker_form.rb
app/models/household_member.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/anyone_caretaker/edit.html.erb
app/views/integrated/who_is_caretaker/edit.html.erb
app/views/integrated/who_is_married/edit.html.erb
db/migrate/20180328001006_add_anyone_caretaker_to_application_navigator.rb
db/migrate/20180328002301_add_caretaker_to_household_member.rb
db/schema.rb
spec/controllers/integrated/anyone_caretaker_controller_spec.rb
spec/controllers/integrated/who_is_caretaker_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/forms/who_is_caretaker_form_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

For multi-member family, ask if anyone is a caretaker and if so, who.
Includes refactor of multi-member controller (previously in https://github.com/codeforamerica/michigan-benefits/pull/723, but I closed in favor of including here).
Skips steps if single-member family.

 Ask if anyone is a caretaker, and who

---

app/controllers/integrated/anyone_student_controller.rb
app/controllers/integrated/are_you_student_controller.rb
app/controllers/integrated/who_is_student_controller.rb
app/forms/anyone_student_form.rb
app/forms/are_you_student_form.rb
app/forms/form_navigation.rb
app/forms/who_is_student_form.rb
app/models/household_member.rb
app/pdf_components/assistance_application_form.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/anyone_student/edit.html.erb
app/views/integrated/are_you_student/edit.html.erb
app/views/integrated/who_is_student/edit.html.erb
db/migrate/20180329004046_add_student_attributes_to_navigator_and_member.rb
db/schema.rb
spec/controllers/integrated/anyone_student_controller_spec.rb
spec/controllers/integrated/are_you_student_controller_spec.rb
spec/controllers/integrated/who_is_student_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/forms/who_is_student_form_spec.rb
spec/pdf_components/assistance_application_form_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

Updates all members to student: 'no' when user indicates no one is a student in household.
[Finishes #156045589]

Ask if anyone is a student, and who

---

app/controllers/integrated/are_you_citizen_controller.rb
app/controllers/integrated/everyone_citizen_controller.rb
app/controllers/integrated/immigration_info_controller.rb
app/controllers/integrated/who_is_not_citizen_controller.rb
app/forms/are_you_citizen_form.rb
app/forms/everyone_citizen_form.rb
app/forms/form_navigation.rb
app/forms/immigration_info_form.rb
app/forms/who_is_not_citizen_form.rb
app/models/household_member.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/are_you_citizen/edit.html.erb
app/views/integrated/everyone_citizen/edit.html.erb
app/views/integrated/immigration_info/edit.html.erb
app/views/integrated/who_is_not_citizen/edit.html.erb
db/migrate/20180329203347_add_citizen_attributes_to_member_and_navigator.rb
db/schema.rb
spec/controllers/integrated/are_you_citizen_controller_spec.rb
spec/controllers/integrated/everyone_citizen_controller_spec.rb
spec/controllers/integrated/immigration_info_controller_spec.rb
spec/controllers/integrated/who_is_not_citizen_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/forms/who_is_not_citizen_form_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Includes refactor of assistance_application_form_spec.rb
[#156045606]
Signed-off-by: Christa Harstock <christa@codeforamerica.org>
Co-authored-by: Christa Harstock <christa@codeforamerica.org>

Integrated flow: Citizenship questions

---

app/controllers/integrated/anyone_veteran_controller.rb
app/controllers/integrated/are_you_veteran_controller.rb
app/controllers/integrated/who_is_veteran_controller.rb
app/forms/anyone_veteran_form.rb
app/forms/are_you_veteran_form.rb
app/forms/form_navigation.rb
app/forms/who_is_veteran_form.rb
app/models/household_member.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/anyone_veteran/edit.html.erb
app/views/integrated/are_you_veteran/edit.html.erb
app/views/integrated/who_is_veteran/edit.html.erb
db/migrate/20180330193810_add_veteran_attributes_to_member_and_navigator.rb
db/schema.rb
spec/controllers/integrated/anyone_veteran_controller_spec.rb
spec/controllers/integrated/are_you_veteran_controller_spec.rb
spec/controllers/integrated/who_is_veteran_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/forms/who_is_veteran_form_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Nothing interesting. Just the standard stuff!

Integrated app: Veterans questions

---

app/controllers/integrated/anyone_foster_care_controller.rb
app/controllers/integrated/were_you_foster_care_controller.rb
app/controllers/integrated/who_was_foster_care_controller.rb
app/forms/anyone_foster_care_form.rb
app/forms/form_navigation.rb
app/forms/were_you_foster_care_form.rb
app/forms/who_was_foster_care_form.rb
app/models/household_member.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/anyone_foster_care/edit.html.erb
app/views/integrated/were_you_foster_care/edit.html.erb
app/views/integrated/who_was_foster_care/edit.html.erb
db/migrate/20180330230846_add_foster_care_attributes_to_member_and_navigator.rb
db/schema.rb
spec/controllers/integrated/anyone_foster_care_controller_spec.rb
spec/controllers/integrated/were_you_foster_care_controller_spec.rb
spec/controllers/integrated/who_was_foster_care_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/household_member_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

Adds #age method to household_member.
[#156045620]

Integrated flow: foster care

---

app/controllers/integrated/anyone_healthcare_enrolled_controller.rb
app/controllers/integrated/are_you_healthcare_enrolled_controller.rb
app/controllers/integrated/who_is_healthcare_enrolled_controller.rb
app/forms/anyone_healthcare_enrolled_form.rb
app/forms/are_you_healthcare_enrolled_form.rb
app/forms/form_navigation.rb
app/forms/who_is_healthcare_enrolled_form.rb
app/models/household_member.rb
app/models/integrated/pdf_attributes.rb
app/pdf_components/assistance_application_form.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/anyone_healthcare_enrolled/edit.html.erb
app/views/integrated/are_you_healthcare_enrolled/edit.html.erb
app/views/integrated/who_is_healthcare_enrolled/edit.html.erb
db/migrate/20180404181931_add_healthcare_enrolled_attributes.rb
db/schema.rb
spec/controllers/integrated/anyone_healthcare_enrolled_controller_spec.rb
spec/controllers/integrated/are_you_healthcare_enrolled_controller_spec.rb
spec/controllers/integrated/who_is_healthcare_enrolled_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

Integrated flow: Currently enrolled in health insurance?

---

app/controllers/integrated/anyone_have_medical_bills_controller.rb
app/controllers/integrated/do_you_have_medical_bills_controller.rb
app/controllers/integrated/who_has_medical_bills_controller.rb
app/forms/anyone_have_medical_bills_form.rb
app/forms/do_you_have_medical_bills_form.rb
app/forms/form_navigation.rb
app/forms/who_has_medical_bills_form.rb
app/models/household_member.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/anyone_have_medical_bills/edit.html.erb
app/views/integrated/do_you_have_medical_bills/edit.html.erb
app/views/integrated/who_has_medical_bills/edit.html.erb
db/migrate/20180404195131_add_medical_bill_attributes.rb
db/schema.rb
spec/controllers/integrated/anyone_have_medical_bills_controller_spec.rb
spec/controllers/integrated/do_you_have_medical_bills_controller_spec.rb
spec/controllers/integrated/who_has_medical_bills_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

https://www.pivotaltracker.com/story/show/156389926

 Integrated flow:  Ask if anyone has medical bills from last three months

---

app/controllers/integrated/anyone_flint_water_controller.rb
app/controllers/integrated/are_you_flint_water_controller.rb
app/controllers/integrated/who_is_flint_water_controller.rb
app/forms/anyone_flint_water_form.rb
app/forms/are_you_flint_water_form.rb
app/forms/form_navigation.rb
app/forms/who_is_flint_water_form.rb
app/models/household_member.rb
app/models/snap_application.rb
app/pdf_components/assistance_application_form.rb
app/pdf_components/healthcare_coverage_supplement.rb
app/views/integrated/anyone_flint_water/edit.html.erb
app/views/integrated/are_you_flint_water/edit.html.erb
app/views/integrated/who_is_flint_water/edit.html.erb
db/migrate/20180405183241_add_flint_water_attributes.rb
db/schema.rb
spec/controllers/integrated/anyone_flint_water_controller_spec.rb
spec/controllers/integrated/are_you_flint_water_controller_spec.rb
spec/controllers/integrated/who_is_flint_water_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb
spec/pdf_components/healthcare_coverage_supplement_spec.rb

Ask Flint Water question

---

app/controllers/integrated/has_your_income_changed_controller.rb
app/controllers/integrated/tell_us_income_changed_controller.rb
app/forms/form_navigation.rb
app/forms/has_your_income_changed_form.rb
app/forms/tell_us_income_changed_form.rb
app/models/common_application.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/has_your_income_changed/edit.html.erb
app/views/integrated/tell_us_income_changed/edit.html.erb
db/migrate/20180405225938_add_income_changed_attributes.rb
db/schema.rb
lib/generators/section/section_generator.rb
spec/controllers/integrated/has_your_income_changed_controller_spec.rb
spec/controllers/integrated/tell_us_income_changed_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb
spec/rails_helper.rb

Integrated flow: Has your income changed?

---

app/controllers/integrated/do_you_have_job_controller.rb
app/controllers/integrated/how_many_jobs_controller.rb
app/forms/do_you_have_job_form.rb
app/forms/form_navigation.rb
app/forms/how_many_jobs_form.rb
app/helpers/mb_form_builder.rb
app/models/common_application.rb
app/models/household_member.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/do_you_have_job/edit.html.erb
app/views/integrated/how_many_jobs/edit.html.erb
db/migrate/20180410200150_add_job_attributes.rb
db/schema.rb
spec/controllers/integrated/do_you_have_job_controller_spec.rb
spec/controllers/integrated/how_many_jobs_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/common_application_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Updates mb_incrementer to take in a hide_label parameter
[#156389971]

Integrated flow: How many jobs?

---

app/controllers/integrated/anyone_self_employed_controller.rb
app/controllers/integrated/are_you_self_employed_controller.rb
app/controllers/integrated/who_is_self_employed_controller.rb
app/forms/anyone_self_employed_form.rb
app/forms/are_you_self_employed_form.rb
app/forms/form_navigation.rb
app/forms/who_is_self_employed_form.rb
app/models/common_application.rb
app/models/household_member.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/anyone_self_employed/edit.html.erb
app/views/integrated/are_you_self_employed/edit.html.erb
app/views/integrated/who_is_self_employed/edit.html.erb
db/migrate/20180411173903_add_self_employed_attributes.rb
db/schema.rb
spec/controllers/integrated/anyone_self_employed_controller_spec.rb
spec/controllers/integrated/are_you_self_employed_controller_spec.rb
spec/controllers/integrated/who_is_self_employed_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Integrated: Are you / Is anyone self-employed?

---

app/controllers/integrated/introduce_yourself_controller.rb
app/controllers/integrated/reside_in_state_controller.rb
app/forms/form_navigation.rb
app/models/common_application.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/reside_in_state/edit.html.erb
spec/controllers/integrated/introduce_yourself_controller_spec.rb
spec/controllers/integrated/remove_household_member_controller_spec.rb
spec/controllers/integrated/reside_in_state_controller_spec.rb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_non_resident_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/common_application_spec.rb

Reorder integrated flow

---

app/forms/form_navigation.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Remove tax household intro from the flow.

---

citizen.yml

* just a little Friday cleanup
* happy Friday, peeps!

Remove unused `citizen.yml` file

---

config.ru

Re-add config.ru

---

app/views/integrated/income_sources/edit.html.erb

Add help text to income sources question

---

app/views/layouts/application.html.erb
spec/features/staging_warning_spec.rb

Re-adds banner to staging and demo sites, since accessibility testing is now complete.

Revert "Disable banner on demo websites"

---

app/controllers/integrated/childcare_expenses_controller.rb
app/controllers/integrated/dependent_care_expenses_controller.rb
app/forms/childcare_expenses_form.rb
app/forms/dependent_care_expenses_form.rb
app/forms/form_navigation.rb
app/models/expense.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/childcare_expenses/edit.html.erb
app/views/integrated/dependent_care_expenses/edit.html.erb
spec/controllers/integrated/childcare_expenses_controller_spec.rb
spec/controllers/integrated/dependent_care_expenses_controller_spec.rb
spec/controllers/integrated/utility_expenses_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/expense_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Ask if applicant has dependent care expenses for multi-member household

---

app/models/expense.rb

Adds some new options to give full parity to PDF, at Rachel's request!

Add mobile home lot rent and land contract to housing expense options

---

app/controllers/concerns/single_expense.rb
app/controllers/integrated/child_support_controller.rb
app/controllers/integrated/childcare_expenses_controller.rb
app/controllers/integrated/dependent_care_expenses_controller.rb
app/forms/child_support_form.rb
app/forms/form_navigation.rb
app/models/expense.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/child_support/edit.html.erb
config/locales/en.yml
spec/controllers/integrated/child_support_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/expense_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Also extracts single-expense controller actions into shared concern.

Ask applicant if they pay child support

---

app/controllers/concerns/single_expense.rb
app/controllers/integrated/alimony_controller.rb
app/controllers/integrated/child_support_controller.rb
app/controllers/integrated/childcare_expenses_controller.rb
app/controllers/integrated/dependent_care_expenses_controller.rb
app/forms/alimony_form.rb
app/forms/child_support_form.rb
app/forms/form_navigation.rb
app/models/expense.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/alimony/edit.html.erb
app/views/integrated/child_support/edit.html.erb
config/locales/en.yml
spec/controllers/integrated/alimony_controller_spec.rb
spec/controllers/integrated/child_support_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/expense_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

 Ask applicant if they pay alimony

---

app/controllers/concerns/single_expense.rb
app/controllers/integrated/alimony_controller.rb
app/controllers/integrated/child_support_controller.rb
app/controllers/integrated/childcare_expenses_controller.rb
app/controllers/integrated/dependent_care_expenses_controller.rb
app/controllers/integrated/student_loan_interest_controller.rb
app/forms/alimony_form.rb
app/forms/child_support_form.rb
app/forms/form_navigation.rb
app/forms/student_loan_interest_form.rb
app/models/expense.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/alimony/edit.html.erb
app/views/integrated/child_support/edit.html.erb
app/views/integrated/student_loan_interest/edit.html.erb
config/locales/en.yml
spec/controllers/integrated/alimony_controller_spec.rb
spec/controllers/integrated/child_support_controller_spec.rb
spec/controllers/integrated/student_loan_interest_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/models/expense_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

 Ask applicant if they have deductible student loan interest

---

app/controllers/integrated/money_in_accounts_controller.rb
app/forms/form_navigation.rb
app/forms/money_in_accounts_form.rb
app/views/integrated/money_in_accounts/edit.html.erb
config/locales/en.yml
db/migrate/20180423214751_add_money_in_accounts_to_navigator.rb
db/schema.rb
spec/controllers/integrated/money_in_accounts_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Stores on navigator, because we will ask user for definitive information about accounts later.

Ask applicant if they have money in accounts

---

app/controllers/integrated/amount_in_accounts_controller.rb
app/controllers/integrated/money_in_accounts_controller.rb
app/forms/amount_in_accounts_form.rb
app/forms/form_navigation.rb
app/forms/money_in_accounts_form.rb
app/models/common_application.rb
app/views/integrated/amount_in_accounts/edit.html.erb
app/views/integrated/money_in_accounts/edit.html.erb
config/locales/en.yml
db/migrate/20180423214751_add_money_in_accounts_to_navigator.rb
db/migrate/20180423220751_add_amount_threshold_to_application.rb
db/schema.rb
spec/controllers/integrated/amount_in_accounts_controller_spec.rb
spec/controllers/integrated/money_in_accounts_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

When user has indicated that they have money in accounts.
Bases off https://github.com/codeforamerica/michigan-benefits/pull/762
Does not write to PDF yet, because we don't have the needed information about income to complete the relevant question.

Ask applicant if they have more than $100 in accounts

---

app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss
app/controllers/integrated/amount_in_accounts_controller.rb
app/controllers/integrated/money_in_accounts_controller.rb
app/controllers/integrated/vehicles_controller.rb
app/forms/amount_in_accounts_form.rb
app/forms/form_navigation.rb
app/forms/money_in_accounts_form.rb
app/forms/vehicles_form.rb
app/models/common_application.rb
app/views/integrated/amount_in_accounts/edit.html.erb
app/views/integrated/money_in_accounts/edit.html.erb
app/views/integrated/vehicles/edit.html.erb
app/views/layouts/form.html.erb
config/locales/en.yml
db/migrate/20180423214751_add_money_in_accounts_to_navigator.rb
db/migrate/20180423220751_add_amount_threshold_to_application.rb
db/migrate/20180423223206_add_vehicles_to_navigator.rb
db/schema.rb
spec/controllers/integrated/amount_in_accounts_controller_spec.rb
spec/controllers/integrated/money_in_accounts_controller_spec.rb
spec/controllers/integrated/vehicles_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Doesn't fill out PDF for now -- just the navigator. Adding vehicles soon to come!
Based off of https://github.com/codeforamerica/michigan-benefits/pull/762

 Ask applicant if they own any vehicles

---

app/views/integrated/money_in_accounts/edit.html.erb
app/views/integrated/vehicles/edit.html.erb

[Fixes #156390019]
[Fixes #156390026]
Will merge once CI passes

Move yes/no buttons to footer

---

app/controllers/integrated/legal_agreement_controller.rb
app/controllers/integrated/sign_submit_controller.rb
app/forms/form_navigation.rb
app/forms/legal_agreement_form.rb
app/forms/sign_submit_form.rb
app/models/common_application.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/legal_agreement/edit.html.erb
app/views/integrated/sign_submit/edit.html.erb
app/views/static_pages/privacy.html.erb
db/migrate/20180425213023_add_signature.rb
db/schema.rb
spec/controllers/integrated/legal_agreement_controller_spec.rb
spec/controllers/integrated/sign_submit_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Also updates the privacy policy.
[#156390127]

Integrated app: Terms & Signature

---

app/models/common_application.rb
app/models/office_recipient.rb
spec/models/office_recipient_spec.rb

Check for mailing zip if there is no residential zip

---

app/assets/stylesheets/michigan-benefits/molecules/_form-molecules.scss
app/forms/job_details_form.rb
spec/controllers/integrated/job_details_controller_spec.rb
spec/forms/job_details_form_spec.rb

Also a CSS spacing fix.
https://www.pivotaltracker.com/story/show/156390039

Validate presence of employer name

---

app/views/integrated/are_you_self_employed/edit.html.erb

Update help text for self-employment question

---

app/controllers/integrated/childcare_expenses_details_controller.rb
app/forms/childcare_expenses_details_form.rb
app/forms/form_navigation.rb
app/helpers/mb_form_builder.rb
app/models/employment.rb
app/models/expense.rb
app/models/household_member.rb
app/models/integrated/pdf_attributes.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/childcare_expenses_details/edit.html.erb
db/migrate/20180516184028_create_expenses_household_members.rb
db/schema.rb
spec/controllers/integrated/childcare_expenses_details_controller_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/forms/childcare_expenses_details_form_spec.rb
spec/helpers/mb_form_builder_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

[Finishes #156961615]
Paired on this with @bengolder! Forgot to update my local commit info.

Ask about childcare expenses

---

app/views/integrated/how_many_jobs/edit.html.erb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Update question copy

---

app/controllers/integrated/add_vehicle_controller.rb
app/controllers/integrated/remove_vehicle_controller.rb
app/controllers/integrated/vehicles_overview_controller.rb
app/forms/add_vehicle_form.rb
app/forms/form_navigation.rb
app/forms/remove_vehicle_form.rb
app/models/common_application.rb
app/models/household_member.rb
app/models/vehicle.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/add_vehicle/edit.html.erb
app/views/integrated/vehicles_overview/edit.html.erb
config/locales/en.yml
db/migrate/20180517233951_create_vehicles.rb
db/migrate/20180518004805_create_household_members_vehicles.rb
db/schema.rb
spec/controllers/integrated/add_vehicle_controller_spec.rb
spec/controllers/integrated/remove_vehicle_controller_spec.rb
spec/controllers/integrated/vehicles_overview_controller_spec.rb
spec/factories/vehicles.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/forms/add_vehicle_form_spec.rb
spec/models/vehicle_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Creates an "off main" flow for adding vehicle records to an application.
Fills the PDF too, of course. Modeled after household member flow.

Add vehicle assets

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_line-item.scss
app/controllers/integrated/accounts_overview_controller.rb
app/controllers/integrated/add_account_controller.rb
app/controllers/integrated/remove_account_controller.rb
app/forms/add_account_form.rb
app/forms/form_navigation.rb
app/forms/remove_account_form.rb
app/models/account.rb
app/models/common_application.rb
app/models/household_member.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/accounts_overview/edit.html.erb
app/views/integrated/add_account/edit.html.erb
app/views/integrated/amount_in_accounts/edit.html.erb
config/locales/en.yml
db/migrate/20180525003105_create_accounts.rb
db/migrate/20180525153022_create_accounts_household_members.rb
db/schema.rb
spec/controllers/integrated/accounts_overview_controller_spec.rb
spec/controllers/integrated/add_account_controller_spec.rb
spec/controllers/integrated/remove_account_controller_spec.rb
spec/factories/accounts.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/forms/add_account_form_spec.rb
spec/models/account_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Mostly follows the example of vehicle assets.
https://www.pivotaltracker.com/story/show/156390077

Integrated: Tell us about your accounts

---

app/views/integrated/accounts_overview/edit.html.erb

Don't show names on account for single member household

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Uses a partial to render a placeholder progress bar

Transition: Tell us about your household

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/finishing_up_controller.rb
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/health_and_insurance_controller.rb
app/controllers/integrated/household_bills_controller.rb
app/controllers/integrated/income_and_employment_controller.rb
app/controllers/integrated/savings_and_assets_controller.rb
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/finishing_up/edit.html.erb
app/views/integrated/getting_to_know_you/edit.html.erb
app/views/integrated/health_and_insurance/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/income_and_employment/edit.html.erb
app/views/integrated/savings_and_assets/edit.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Based off of https://github.com/codeforamerica/michigan-benefits/pull/798
This is the final transition page story!

 Add 'Finishing up' transition page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/getting_to_know_you/edit.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Based on https://github.com/codeforamerica/michigan-benefits/pull/793#pullrequestreview-124206238

 Add "Getting to know you" transition page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/household_bills_controller.rb
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/getting_to_know_you/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Based on https://github.com/codeforamerica/michigan-benefits/pull/794

 Add 'Household bills' transition page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/health_and_insurance_controller.rb
app/controllers/integrated/household_bills_controller.rb
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/getting_to_know_you/edit.html.erb
app/views/integrated/health_and_insurance/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Based on https://github.com/codeforamerica/michigan-benefits/pull/795

 Add 'Health and insurance' transition page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/health_and_insurance_controller.rb
app/controllers/integrated/household_bills_controller.rb
app/controllers/integrated/savings_and_assets_controller.rb
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/getting_to_know_you/edit.html.erb
app/views/integrated/health_and_insurance/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/savings_and_assets/edit.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Based off of https://github.com/codeforamerica/michigan-benefits/pull/796

 Add 'Savings and assets' transition page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/michigan-benefits/molecules/_progress-bar.scss
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/health_and_insurance_controller.rb
app/controllers/integrated/household_bills_controller.rb
app/controllers/integrated/income_and_employment_controller.rb
app/controllers/integrated/savings_and_assets_controller.rb
app/controllers/integrated/your_household_controller.rb
app/forms/form_navigation.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/getting_to_know_you/edit.html.erb
app/views/integrated/health_and_insurance/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/income_and_employment/edit.html.erb
app/views/integrated/savings_and_assets/edit.html.erb
app/views/integrated/your_household/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Based on https://github.com/codeforamerica/michigan-benefits/pull/797

 Add 'Income and employment' transition page

---

app/controllers/integrated/introduce_yourself_controller.rb
app/controllers/integrated/welcome_controller.rb
app/controllers/integrated/which_programs_controller.rb
app/forms/form_navigation.rb
app/forms/which_programs_form.rb
app/helpers/mb_form_builder.rb
app/views/integrated/which_programs/edit.html.erb
db/migrate/20180530183937_add_applying_for_to_navigator.rb
db/schema.rb
spec/controllers/integrated/introduce_yourself_controller_spec.rb
spec/controllers/integrated/welcome_controller_spec.rb
spec/controllers/integrated/which_programs_controller_spec.rb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_non_resident_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/forms/which_programs_form_spec.rb
spec/helpers/mb_form_builder_spec.rb

Choose which programs you want

---

app/controllers/integrated/reside_out_of_state_controller.rb
app/views/integrated/reside_out_of_state/edit.html.erb
spec/features/integrated_application_food_only_two_members_spec.rb
spec/features/integrated_application_non_resident_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb

Show proper offramp for non-residents with SNAP/Medicaid/both

---

app/controllers/integrated/anything_else_controller.rb
app/forms/anything_else_form.rb
app/forms/form_navigation.rb
app/pdf_components/assistance_application_form.rb
app/views/integrated/anything_else/edit.html.erb
db/migrate/20180605180927_add_additional_information_to_common_application.rb
db/schema.rb
spec/controllers/integrated/anything_else_controller_spec.rb
spec/features/integrated_application_food_only_spec.rb
spec/features/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application_with_single_member_spec.rb
spec/features/integrated_application_with_two_members_spec.rb
spec/forms/anything_else_form_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Ask applicants if there's anything else

---

Gemfile
Gemfile.lock
config/routes.rb
spec/features/admin_user_delayed_job_spec.rb

https://www.pivotaltracker.com/story/show/155759158

Re-enable delayed_job_web

---

app/controllers/integrated/finishing_up_controller.rb
app/controllers/integrated/getting_to_know_you_controller.rb
app/controllers/integrated/health_and_insurance_controller.rb
app/controllers/integrated/household_bills_controller.rb
app/controllers/integrated/income_and_employment_controller.rb
app/controllers/integrated/savings_and_assets_controller.rb
app/controllers/integrated/transition_controller.rb
app/controllers/integrated/your_household_controller.rb
app/models/common_application.rb
app/views/integrated/_progress_bar.html.erb
app/views/integrated/finishing_up/edit.html.erb
app/views/integrated/health_and_insurance/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/income_and_employment/edit.html.erb
app/views/integrated/savings_and_assets/edit.html.erb
app/views/integrated/your_household/edit.html.erb
circle.yml
spec/controllers/integrated/getting_to_know_you_controller_spec.rb
spec/controllers/integrated/health_and_insurance_controller_spec.rb
spec/controllers/integrated/household_bills_controller_spec.rb
spec/controllers/integrated/income_and_employment_controller_spec.rb
spec/controllers/integrated/savings_and_assets_controller_spec.rb
spec/controllers/integrated/transition_controller_spec.rb
spec/controllers/integrated/your_household_controller_spec.rb
spec/features/integrated_application_medicaid_only_spec.rb

Calculate progress bar for transition pages

---

app/assets/stylesheets/michigan-benefits/organisms/_form-card.scss

Corrects rejection of https://www.pivotaltracker.com/story/show/156744317

Expand gap between big buttons

---

app/assets/stylesheets/michigan-benefits/atoms/_form-elements.scss
app/helpers/mb_form_builder.rb
spec/helpers/mb_form_builder_spec.rb

Disabled checkboxes should be lightened by 50%.

---

app/controllers/integrated/income_sources_controller.rb
app/models/additional_income.rb
app/views/integrated/income_sources/edit.html.erb
spec/controllers/integrated/income_sources_controller_spec.rb
spec/factories/common_applications.rb
spec/features/integrated_application_medicaid_only_spec.rb

Medicaid-only flow: Remove non-taxable income sources

---

app/controllers/forms_controller.rb
app/helpers/application_helper.rb
app/views/application_mailer/office_integrated_application_notification.html.erb
app/views/integrated/application_submitted/edit.html.erb
app/views/integrated/sign_submit/edit.html.erb
config/offices.yml
spec/controllers/forms_controller_spec.rb
spec/models/office_recipient_spec.rb

See individual commits for details.

Copychangemania!

---

app/views/integrated/application_submitted/edit.html.erb

Switch "slab" section for div for better spacing.
[#157953514]
Signed-off-by: Whitney Schaefer <whitney@codeforamerica.org>
Co-authored-by: Whitney Schaefer <whitney@codeforamerica.org>

Remove interview section when Medicaid-only.

---

app/views/static_pages/clio.html.erb
app/views/static_pages/index.html.erb
app/views/static_pages/union.html.erb
spec/features/integrated_application/integrated_application_food_only_spec.rb
spec/features/integrated_application/integrated_application_medicaid_only_spec.rb
spec/features/integrated_application/integrated_application_non_resident_spec.rb

[#157953054]
Signed-off-by: Whitney Schaefer <whitney@codeforamerica.org>
Co-authored-by: Whitney Schaefer <whitney@codeforamerica.org>

Don't auto-select programs from main button on home page and office pages.

---

Gemfile
Gemfile.lock
app/controllers/integrated/healthcare_controller.rb
app/dashboards/common_application_dashboard.rb
app/fields/address_field.rb
app/forms/which_programs_form.rb
app/models/common_application.rb
app/models/integrated/pdf_attributes.rb
app/pdf_components/assistance_application_form.rb
app/views/fields/address_field/_form.html.erb
app/views/fields/address_field/_index.html.erb
app/views/fields/address_field/_show.html.erb
spec/controllers/integrated/decline_healthcare_controller_spec.rb
spec/controllers/integrated/describe_tax_relationships_controller_spec.rb
spec/features/integrated_application/integrated_application_non_resident_spec.rb
spec/models/common_application_spec.rb
spec/pdf_components/assistance_application_form_spec.rb

Make CommonApplication admin dashboard more useful!

---

app/controllers/stats/numbers_controller.rb
app/models/common_application.rb
app/views/stats/numbers/index.html.erb
spec/factories/common_applications.rb
spec/features/numbers_dashboard_spec.rb
spec/models/common_application_spec.rb

[finishes #158376446]
Signed-off-by: Whitney Schaefer <whitney@codeforamerica.org>

Add combined app info to numbers

---

app/views/layouts/form.html.erb

Show office links on Application Submitted page

---

app/views/integrated/how_many_jobs/edit.html.erb

[Finishes #158445430]
Co-authored-by: Luigi Ray-Montanez <luigi@codeforamerica.org>

Show job description help text for multi-member household

---

app/controllers/stats/numbers_controller.rb
app/views/stats/numbers/index.html.erb
spec/features/numbers_dashboard_spec.rb

Some renaming, and archiving old flows.
I'm a little concerned about the median times for the integrated flow types being calculated correctly (seemed wonky locally). Stopped short of writing integration tests that actually test the median time calculation, but would appreciate a second set of eyes.

Update /numbers with integrated flow

---

lib/summarizer/application_summary.rb
spec/factories/common_applications.rb
spec/lib/summarizer/application_summary_spec.rb

Update benny-bot to report on integrated applications

---

app/models/household_member.rb
app/views/integrated/alimony_details/edit.html.erb
app/views/integrated/anyone_flint_water/edit.html.erb
app/views/integrated/anyone_student/edit.html.erb
app/views/integrated/are_you_flint_water/edit.html.erb
app/views/integrated/are_you_student/edit.html.erb
app/views/integrated/describe_tax_relationships/edit.html.erb
app/views/integrated/file_taxes_next_year/edit.html.erb
spec/features/integrated_application/integrated_application_food_only_spec.rb
spec/features/integrated_application/integrated_application_medicaid_only_spec.rb
spec/features/integrated_application/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application/integrated_application_with_single_member_spec.rb
spec/features/integrated_application/integrated_application_with_two_members_spec.rb

Various copy changes

---

lib/generators/section/who_is/who_is_generator.rb
spec/features/snap_application_with_minimal_info_spec.rb

Just some small fixes to make `rake` runs more stable.

Rubocop heredoc fix

---

app/forms/office_location_form.rb
spec/forms/office_location_form_spec.rb

Require client to choose a location

---

config/offices.yml
spec/models/office_recipient_spec.rb

Change the Clio email address

---

app/views/integrated/anyone_flint_water/edit.html.erb
app/views/integrated/are_you_flint_water/edit.html.erb
spec/features/integrated_application/integrated_application_medicaid_only_spec.rb
spec/features/integrated_application/integrated_application_with_multiple_members_spec.rb
spec/features/integrated_application/integrated_application_with_single_member_spec.rb
spec/features/integrated_application/integrated_application_with_two_members_spec.rb

Revert to previous question for Flint Water Crisis.

---

app/controllers/integrated/application_submitted_controller.rb

Addresses https://sentry.io/app73768247herokucom-6k/michigan-benefits-production/issues/657602539/?environment=production

Assign feedback form on both edit and update

---

app/assets/stylesheets/michigan-benefits/tooltipster.scss
app/helpers/mb_form_builder.rb
app/views/feedbacks/_form.html.erb
app/views/integrated/anyone_married/edit.html.erb
app/views/integrated/anyone_pregnant/edit.html.erb
app/views/integrated/anyone_student/edit.html.erb
app/views/integrated/anyone_veteran/edit.html.erb
app/views/integrated/anything_else/edit.html.erb
app/views/integrated/application_submitted/edit.html.erb
app/views/integrated/buy_and_prepare_food_with_other_person/edit.html.erb
app/views/integrated/file_taxes_this_year/edit.html.erb
app/views/integrated/household_bills/edit.html.erb
app/views/integrated/household_members_overview/edit.html.erb
app/views/integrated/how_many_jobs/edit.html.erb
app/views/integrated/introduce_yourself/edit.html.erb
app/views/integrated/job_details/edit.html.erb
app/views/integrated/living_situation/edit.html.erb
app/views/integrated/office_location/edit.html.erb
app/views/integrated/property/edit.html.erb
app/views/integrated/provide_ssn/edit.html.erb
app/views/integrated/residential_address/edit.html.erb
app/views/integrated/utility_expenses/edit.html.erb
app/views/integrated/welcome/edit.html.erb
app/views/integrated/which_programs/edit.html.erb
app/views/integrated/who_is_student/edit.html.erb
app/views/integrated/your_household/edit.html.erb
app/views/static_pages/index.html.erb

Add annotations

---

app/views/static_pages/index.html.erb
spec/features/flow_closed_spec.rb

Show Flow closed content when FLOW_CLOSED_ENABLED is true

---

app/assets/stylesheets/michigan-benefits/tooltipster.scss

Update the tooltip colors

---

app/views/integrated/living_situation/edit.html.erb

Combine the two tooltips

---

config/routes.rb
spec/features/office_specific_landing_pages_spec.rb

/clio and /union are now closed.
